(function() {
var _UDS_CONST_LOCALE = 'pt-BR';
var _UDS_CONST_SHORT_DATE_PATTERN = 'DMY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('Imagem'); 
var _UDS_MSG_SEARCHER_WEB = ('Web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blog'); 
var _UDS_MSG_SEARCHER_VIDEO = ('V\u00eddeo'); 
var _UDS_MSG_SEARCHER_LOCAL = ('Local'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('salvar'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('guardar'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('incluir'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('copiar'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('fechar'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Links patrocinados'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('veja mais...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('recortado do Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('Local da pesquisa'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Desativar consulta de endere\u00e7o'); 
var _UDS_MSG_SEARCHER_NEWS = ('Not\u00edcias'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' minutos atr\u00e1s');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 hora atr\u00e1s'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' horas atr\u00e1s');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('todos os ' + NUMBER + ' relacionados');} 
var _UDS_MSG_NEWS_RELATED = ('Artigos relacionados'); 
var _UDS_MSG_BRANDING_STRING = ('powered by Google'); 
var _UDS_MSG_SORT_BY_DATE = ('Classificar por data'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Jan'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Fev'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Mar'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Abr'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('Mai'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Jun'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Jul'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Ago'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Set'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Out'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Nov'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Dez'); 
var _UDS_MSG_DIRECTIONS = ('como chegar'); 
var _UDS_MSG_CLEAR_RESULTS = ('limpar resultados'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('mostrar um resultado'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('mostrar mais resultados'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('mostrar todos os resultados'); 
var _UDS_MSG_SETTINGS = ('configura\u00e7\u00f5es'); 
var _UDS_MSG_SEARCH = ('pesquisar'); 
var _UDS_MSG_SEARCH_UC = ('Pesquisar'); 
var _UDS_MSG_POWERED_BY = ('powered by'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Banco de empresas fornecido pela ' + LOCAL_RESULTS_PROVIDER);} 
var _UDS_MSG_SEARCHER_BOOK = ('Livro'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('P\u00e1gina ' + FOUND_ON_PAGE);} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' p\u00e1ginas');} 
var _UDS_MSG_SEARCHER_BY = ('por'); 
var _UDS_MSG_SEARCHER_CODE = ('C\u00f3digo'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Licen\u00e7a desconhecida'); 
var _UDS_MSG_SEARCHER_GSA = ('Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('Mais resultados'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Anteriores'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Pr\u00f3ximos'); 
var _UDS_MSG_GET_DIRECTIONS = ('Rota'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('Para c\u00e1'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('Daqui'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('Limpar resultados'); 
var _UDS_MSG_SEARCH_THE_MAP = ('pesquisar o mapa'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('percorrer os resultados'); 
var _UDS_MSG_EDIT_TAGS = ('editar tags'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('marcar esta pesquisa'); 
var _UDS_MSG_SEARCH_STRING = ('string de pesquisa'); 
var _UDS_MSG_OPTIONAL_LABEL = ('marcador opcional'); 
var _UDS_MSG_DELETE = ('excluir'); 
var _UDS_MSG_DELETED = ('exclu\u00eddo'); 
var _UDS_MSG_CANCEL = ('cancelar'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('fa\u00e7a upload do seu v\u00eddeo'); 
var _UDS_MSG_IM_DONE_WATCHING = ('acabei de assistir'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('fechar reprodutor de v\u00eddeo'); 
var _UDS_MSG_NO_RESULTS = ('Nenhum resultado'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('Este Mecanismo de pesquisa personalizado est\u00e1 carregando. Tente novamente em alguns segundos.'); 
var _UDS_MSG_COUPONS = ('Cupons'); 
var _UDS_MSG_BACK = ('voltar'); 
var _UDS_MSG_SUBSCRIBE = ('Inscrever-se'); 
var _UDS_MSG_SEARCHER_PATENT = ('Patente'); 
var _UDS_MSG_USPAT = ('Pat. EUA'); 
var _UDS_MSG_USPAT_APP = ('Solicit. de Pat. EUA'); 
var _UDS_MSG_PATENT_FILED = ('Arquivado'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('An\u00fancios Google'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('Definir local padr\u00e3o'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('\u00daltimas not\u00edcias'); 
var _UDS_MSG_NEWSCAT_WORLD = ('Mundo'); 
var _UDS_MSG_NEWSCAT_NATION = ('Pa\u00eds'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Neg\u00f3cios'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Ci\u00eancia/Tecnologia'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Entretenimento'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('Sa\u00fade'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Esportes'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Pol\u00edtica');
var b=true,c=null,g=false,i=encodeURIComponent,j=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,k=window,m=google,ba=navigator,o=undefined,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,p=document,fa=decodeURIComponent,q=Math;function ga(a,d){return a.onload=d}function ha(a,d){return a.onreadystatechange=d}function ia(a,d){return a.input=d}function ja(a,d){return a.width=d}function r(a,d){return a.innerHTML=d}function ka(a,d){return a.value=d}function la(a,d){return a.type=d}
function ma(a,d){return a.visibility=d}function s(a,d){return a.title=d}function t(a,d){return a.className=d}function na(a,d){return a.checked=d}function oa(a,d){return a.onclick=d}function pa(a,d){return a.display=d}function qa(a,d){return a.execute=d}function u(a,d){return a.height=d}
var v="appendChild",ra="push",sa="clearTimeout",w="input",x="width",ta="round",z="replace",ua="floor",va="content",xa="value",ya="indexOf",za="match",Aa="readyState",Ba="focus",A="createElement",C="setAttribute",Ca="cloneNode",Da="type",Ea="recordStat",Fa="ServiceBase",Ga="getTime",D="length",Ha="title",E="prototype",F="cursor",Ia="className",Ja="Version",Ka="checked",La="setTimeout",Ma="document",Na="split",Oa="userAgent",Pa="location",Qa="getComputedStyle",G="style",Ra="close",H="search",I="call",
J="loader",Sa="currentStyle",Ta="console",Ua="action",Va="apply",Wa="navigator",K="CurrentLocale",L="execute",Xa="height",Ya="toLowerCase",Za="event",M;if(!m[H].NoOldNames){j("UDS_ServiceBase",m[J][Fa]);j("UDS_OriginalAppPath",m[J].OriginalAppPath);j("UDS_ApiKey",m[J].ApiKey);j("UDS_KeyVerified",m[J].KeyVerified);j("UDS_LoadFailure",m[J].LoadFailure);j("UDS_CurrentLocale",ea);j("UDS_ShortDatePattern",aa);j("UDS_Version",m[H][Ja]);j("UDS_JSHash",m[H].JSHash)}if(!N)var N=j;if(!O)var O=google_exportProperty;var P={};P.blank="&nbsp;";P.image=_UDS_MSG_SEARCHER_IMAGE;P.web=_UDS_MSG_SEARCHER_WEB;P.blog=_UDS_MSG_SEARCHER_BLOG;P.video=_UDS_MSG_SEARCHER_VIDEO;P.local=_UDS_MSG_SEARCHER_LOCAL;P.news=_UDS_MSG_SEARCHER_NEWS;P.book=_UDS_MSG_SEARCHER_BOOK;P.patent="Patent";P["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;P.cse="Custom Search Control";P.save=_UDS_MSG_SEARCHCONTROL_SAVE;P.keep=_UDS_MSG_SEARCHCONTROL_KEEP;P.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;P.copy=_UDS_MSG_SEARCHCONTROL_COPY;P.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
P["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;P["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;P.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;P["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;P["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;P["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;P.pbg=_UDS_MSG_BRANDING_STRING;P["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;P["n-hours-ago"]=_UDS_MSG_HOURS_AGO;P["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;P["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
P["related-articles"]=_UDS_MSG_NEWS_RELATED;P["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var Q=[];Q[0]=_UDS_MSG_MONTH_ABBR_JAN;Q[1]=_UDS_MSG_MONTH_ABBR_FEB;Q[2]=_UDS_MSG_MONTH_ABBR_MAR;Q[3]=_UDS_MSG_MONTH_ABBR_APR;Q[4]=_UDS_MSG_MONTH_ABBR_MAY;Q[5]=_UDS_MSG_MONTH_ABBR_JUN;Q[6]=_UDS_MSG_MONTH_ABBR_JUL;Q[7]=_UDS_MSG_MONTH_ABBR_AUG;Q[8]=_UDS_MSG_MONTH_ABBR_SEP;Q[9]=_UDS_MSG_MONTH_ABBR_OCT;Q[10]=_UDS_MSG_MONTH_ABBR_NOV;Q[11]=_UDS_MSG_MONTH_ABBR_DEC;P["month-abbr"]=Q;P.directions=_UDS_MSG_DIRECTIONS;
P["clear-results"]=_UDS_MSG_CLEAR_RESULTS;P["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;P["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;P["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;P.settings=_UDS_MSG_SETTINGS;P.search=_UDS_MSG_SEARCH;P["search-uc"]=_UDS_MSG_SEARCH_UC;P["powered-by"]=_UDS_MSG_POWERED_BY;P.sa=_UDS_MSG_SEARCHER_GSA;P.by=_UDS_MSG_SEARCHER_BY;P.code=_UDS_MSG_SEARCHER_CODE;P["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;P["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
P.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;P.next=_UDS_MSG_SEARCHCONTROL_NEXT;P["get-directions"]=_UDS_MSG_GET_DIRECTIONS;P["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;P["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;P["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;P["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;P["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;P["edit-tags"]=_UDS_MSG_EDIT_TAGS;P["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;P["search-string"]=_UDS_MSG_SEARCH_STRING;P["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
P["delete"]=_UDS_MSG_DELETE;P.deleted=_UDS_MSG_DELETED;P.cancel=_UDS_MSG_CANCEL;P["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;P["im-done"]=_UDS_MSG_IM_DONE_WATCHING;P["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;P["no-results"]=_UDS_MSG_NO_RESULTS;P["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;P.back=_UDS_MSG_BACK;P.subscribe=_UDS_MSG_SUBSCRIBE;P["us-pat"]="US Pat.";P["us-pat-app"]="US Pat. App";P["us-pat-filed"]="Filed";function $a(a,d){var e=function(){};e.prototype=d[E];a.prototype=new e;a[E].Mg=function(f){var h=Array[E].splice[Va](arguments,[1,arguments[D]]);return f[Va](a,h)}}var _json_cache_defeater_=(new Date)[Ga](),_json_request_require_prep=b;function ab(a,d){bb("msie")&&cb("msie 6.0")?k[La](R(this,db,[a,d]),0):db(a,d)}function eb(a){_json_request_require_prep=g;ab(a,c);_json_request_require_prep=b}
function db(a,d){var e=p.getElementsByTagName("head")[0];e||(e=p.body.parentNode[v](p[A]("head")));var f=p[A]("script");la(f,"text/javascript");f.charset="utf-8";a=_json_request_require_prep?a+"&key="+m[J].ApiKey+"&v="+d:a;if(fb()||gb())a=a+"&nocache="+_json_cache_defeater_++;f.src=a;var h=function(){ga(f,c);f.parentNode.removeChild(f);delete f};a=function(l){l=(l?l:k[Za]).target?(l?l:k[Za]).target:(l?l:k[Za]).srcElement;if(l[Aa]=="loaded"||l[Aa]=="complete"){ha(l,c);h()}};if(ba.product=="Gecko")ga(f,
h);else ha(f,a);e[v](f)}function hb(a,d){return function(){return d[Va](a,arguments)}}function R(a,d,e){return function(){return d[Va](a,e)}}function ib(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function jb(a,d){if(a)try{ib(a);a[v](d)}catch(e){}return d}function T(a,d){try{a[v](d)}catch(e){}return d}function kb(a){return p.createTextNode(a?a:"")}function U(a,d){var e=p[A]("div");if(a)r(e,a);if(d)t(e,d);return e}function lb(a,d){var e=p[A]("div");a&&T(e,kb(a));if(d)t(e,d);return e}
function V(a){var d=p[A]("div");if(a)t(d,a);return d}function mb(a,d){var e=p[A]("span");a&&T(e,kb(a));if(d)t(e,d);return e}function nb(a,d,e){var f=p[A]("table");f[C]("cellSpacing",a?a:0);f[C]("cellPadding",d?d:0);if(e)t(f,e);return f}function ob(a,d,e){(a=a.insertRow(-1))||alert(a);for(var f=0;f<d;f++)X(a,e);return a}function X(a,d){a=a.insertCell(-1);if(d)t(a,d);return a}function pb(a){var d=p[A]("td");if(a)t(d,a);return d}
function qb(a,d,e,f){var h=p[A]("img");h.src=a;if(d)ja(h,d);if(e)u(h,e);if(f)t(h,f);return h}function rb(a,d,e,f,h){var l=p[A]("a");l.href=a;if(d)f?T(l,mb(d,f)):T(l,kb(d));if(e)l.target=e;if(h)s(l,h);return l}function Y(a,d,e,f,h){var l=U(c,f),n=p[A]("a");n.href=a;r(n,d);if(f)t(n,f);if(e)n.target=e;if(h)s(n,h);l[v](n);return l}function sb(a,d,e,f,h){var l=U(c,f),n=p[A]("a");n.href=a;d&&T(n,kb(d));if(f)t(n,f);if(e)n.target=e;if(h)s(n,h);l[v](n);return l}
function tb(a){var d=p[A]("form");if(a)t(d,a);return d}function ub(a,d){var e=p[A]("input");la(e,"submit");ka(e,a);if(d)t(e,d);return e}function vb(a,d,e){var f=p[A]("input");f[C]("autoComplete","off");la(f,"text");if(a==-1)Z(f,"util-css-expand");else f.size=a>0?a:10;d&&wb(f,d);if(e)ka(f,e);return f}function xb(a,d,e,f){var h=p[A]("input");la(h,"checkbox");h.name=a;ka(h,d);if(f)t(h,f);if(e)na(h,e);return h}function yb(a,d){t(a,d)}function wb(a,d){Z(a,d)}function zb(a,d){$(a,d)}
function Z(a,d){var e;a:{if(!(a==c||a[Ia]==c)){e=a[Ia][Na](" ");for(var f=0;f<e[D];f++)if(e[f]==d){e=b;break a}}e=g}e||(a.className+=" "+d)}function $(a,d){if(a[Ia]!=c){for(var e=a[Ia][Na](" "),f=[],h=g,l=0;l<e[D];l++)if(e[l]!=d)e[l]&&f[ra](e[l]);else h=b;if(h)t(a,f.join(" "))}}function Ab(a){if(Bb!="")return Bb;var d=a[Ya]()[Na](".");if(d[D]<2)Bb=".com";a=d.pop();d=d.pop();return Bb=a[D]==2?Cb[d]&&Cb[d][a]==1?"."+d+"."+a:"."+a:".com"}
var Bb="",Cb={pf:{Vg:1,Zg:1,hh:1,id:1,ih:1,"in":1,kh:1,mh:1,nh:1,oh:1,rh:1,Ah:1,Ph:1,Th:1,Uh:1,Yh:1,Zh:1,bi:1},Wg:{Ng:1,Pg:1,Rg:1,Sg:1,Tg:1,Ug:1,pf:1,$g:1,"do":1,ah:1,bh:1,dh:1,eh:1,fh:1,gh:1,lh:1,sh:1,th:1,uh:1,vh:1,wh:1,xh:1,yh:1,zh:1,Ch:1,Dh:1,Eh:1,Fh:1,Gh:1,Hh:1,Kh:1,Mh:1,Oh:1,Qh:1,Rh:1,Sh:1,Wh:1,Xh:1,ai:1},Bh:{Og:1}};function bb(a){if(a in Db)return Db[a];return Db[a]=ba[Oa][Ya]()[ya](a)!=-1}function cb(a){if(a in Eb)return Eb[a];return Eb[a]=ba.appVersion[Ya]()[ya](a)!=-1}var Db={},Eb={};
function fb(){return bb("msie")}function gb(){return bb("safari")||bb("konqueror")}var Fb,Gb;if(k.Lg){Fb=b;if(k.XMLHttpRequest)Gb=b}function Hb(a){this.bc=a+"branding";this.Sb=a+"branding-vertical";this.jh=a+"branding-img";this.Vh=a+"branding-user-defined";this.qe=a+"branding-img-noclear";this.of=a+"branding-clickable";this.text=a+"branding-text"};m[H].a=function(){this.fa=this.Xg=c;this.Fc=this.Gg=0;this.ke=b;this.M={width:100,height:75};this.Fa=m[H].a.db;this.we=1;this.S(m[H].a.X);this.$d();this.gwsUrl=this.u=this.H=this.Lh=this.w=this.Kb=this.Cb=this.bb=this.tc=this.Pb=this.ic=this.gc=c;this.pa=[];this.me=typeof k==="object"&&k[Pa]&&k[Pa].hostname&&k[Pa].hostname!=""?Ab(k[Pa].hostname):".com";this.rb=this.lb=c};N("google.search.Search",m[H].a);m[H].a.Jc=m[J][Fa];O(m[H].a,"BASE",m[H].a.Jc);m[H].a.la="large";O(m[H].a,"LARGE_RESULTSET",m[H].a.la);
m[H].a.X="small";O(m[H].a,"SMALL_RESULTSET",m[H].a.X);m[H].a.Ma="filtered_cse";O(m[H].a,"FILTERED_CSE_RESULTSET",m[H].a.Ma);m[H].a.Te=8;O(m[H].a,"LARGE_RESULTS",m[H].a.Te);m[H].a.cf=4;O(m[H].a,"SMALL_RESULTS",m[H].a.cf);m[H].a.Ne=10;O(m[H].a,"FILTERED_CSE_RESULTS",m[H].a.Ne);m[H].a.od=5E3;O(m[H].a,"KEEP_SWEEPER_DELAY",m[H].a.od);m[H].a.We="_top";O(m[H].a,"LINK_TARGET_TOP",m[H].a.We);m[H].a.Ve="_self";O(m[H].a,"LINK_TARGET_SELF",m[H].a.Ve);m[H].a.Ue="_parent";O(m[H].a,"LINK_TARGET_PARENT",m[H].a.Ue);
m[H].a.db="_blank";O(m[H].a,"LINK_TARGET_BLANK",m[H].a.db);m[H].a.eb="order-by-relevance";O(m[H].a,"ORDER_BY_RELEVANCE",m[H].a.eb);m[H].a.ma="order-by-date";O(m[H].a,"ORDER_BY_DATE",m[H].a.ma);m[H].a.rd="order-by-ascending-date";O(m[H].a,"ORDER_BY_ASCENDING_DATE",m[H].a.rd);m[H].a.Db="restrict-type";O(m[H].a,"RESTRICT_TYPE",m[H].a.Db);m[H].a.Ub="restrict-safesearch";O(m[H].a,"RESTRICT_SAFESEARCH",m[H].a.Ub);m[H].a.Wb="active";O(m[H].a,"SAFESEARCH_STRICT",m[H].a.Wb);m[H].a.Vb="off";
O(m[H].a,"SAFESEARCH_OFF",m[H].a.Vb);m[H].a.Ad="moderate";O(m[H].a,"SAFESEARCH_MODERATE",m[H].a.Ad);m[H].a.Na="restrict-extended";O(m[H].a,"RESTRICT_EXTENDED_ARGS",m[H].a.Na);m[H].a.Ag=P;O(m[H].a,"strings",m[H].a.Ag);m[H].a[E].dg=function(){var a=this.na+"?hl="+m[H][K]+"&source=uds";a+=this.u?this.u:"&q=";return this.wa&&this.wa!=""?this.wa:a};m[H].a[E].sg=function(a){this.H=a==c||a==""?c:a};O(m[H].a[E],"setQueryAddition",m[H].a[E].sg);
m[H].a[E].ya=function(a,d,e){a=m[H].a.Jc+this.Ba+"?callback="+a+"&context="+d+"&lstkp="+this.nf()+"&rsz="+this.za+"&hl="+m[H][K];if(this.wb)a+="&source="+i(this.wb);if(this.me)a+="&gss="+this.me;if(m[H].JSHash)a+="&sig="+m[H].JSHash;if(e)a+="&start="+e;return a};m[H].a[E].wg=function(a){this.wb=a};O(m[H].a[E],"setSearcherSrc",m[H].a[E].wg);m[H].a[E].xb=function(a){this.Fa=a};O(m[H].a[E],"setLinkTarget",m[H].a[E].xb);M=m[H].a[E];M.s=function(){return this.Fa&&this.Fa!=""?this.Fa:c};
M.Lf=function(){this.Gg++;this.Fc++;this.Kb&&k[sa](this.Kb);this.Kb=k[La](R(this,this[L],[c]),m[H].a.od)};M.nf=function(){k[sa](this.Kb);var a=this.Fc;this.Fc=0;return a};M.nc=function(){if(this.gc==c)this.gc="gsc-"+this.w+"Result";return this.gc};M.ia=function(){if(this.ic==c)this.ic="gs-"+this.w+"Result";return this.ic};M.Hf=function(){if(this.Pb==c)this.Pb=P[this.w];return this.bb?this.bb:this.Pb};M.Ff=function(){if(this.tc==c)this.tc=P[this.w];return this.bb?this.bb:this.tc};M.Gf=function(){return this.za};
O(m[H].a[E],"getResultSetSize",m[H].a[E].Gf);m[H].a[E].S=function(a){switch(a){case m[H].a.la:this.za=m[H].a.la;break;default:case m[H].a.X:this.za=m[H].a.X;break}};O(m[H].a[E],"setResultSetSize",m[H].a[E].S);qa(m[H].a[E],function(a){var d=(new Date)[Ga]();this.Ec=d%100==1?d:-1;d=this.ha(a,c,c);d+=this.Wa?"&"+this.Wa:"";if(k._googleudsextrastuff)d+=k._googleudsextrastuff;this.cursor=c;this.Rf=a;ab(d,m[H][Ja]);if(this.pa&&this.pa[D]>0)for(d=0;d<this.pa[D];d++)this.pa[d][L](a)});
O(m[H].a[E],"execute",m[H].a[E][L]);m[H].a[E].ne=function(a){if(this[F]&&a<this[F].pages[D]){a=this.ha(this.Rf,c,c,this[F].pages[a].start);this.cursor=c;ab(a,m[H][Ja])}};O(m[H].a[E],"gotoPage",m[H].a[E].ne);m[H].a[E].ef=function(a){this.pa&&this.pa[ra](a)};O(m[H].a[E],"addRelatedSearcher",m[H].a[E].ef);m[H].a[E].Ef=function(a,d,e){return this.ha(a,d,e)+"&key="+m[J].ApiKey+"&v="+m[H][Ja]};O(m[H].a[E],"getExecuteUrl",m[H].a[E].Ef);
m[H].a[E].ta=function(a){var d=Y("http://code.google.com/apis/ajaxsearch/faq.html",P.watermark+" - "+this.qf(),"_blank","gs-watermark");T(a,d)};m[H].a[E].qf=function(){var a=new Date;return a.getMonth()+1+"/"+a.getFullYear()};
m[H].a[E].Va=function(a){var d;d=a.getFullYear();var e=a.getMonth(),f=P["month-abbr"][e];a=a.getDate();if(a<10)a="0"+a;switch(m[H].ShortDatePattern){case "MDY":d=f+" "+a+", "+d;break;case "YMD":if(m[H][K]=="zh-CN"||m[H][K]=="zh-TW"||m[H][K]=="ja"||m[H][K]=="ko"){f=Ib[m[H][K]];d=d+f.year+(e+1)+f.month+a+f.day}else d=d+" "+f+" "+a;break;default:case "DMY":d=a+" "+f+" "+d;break}return d};O(m[H].a[E],"formatToShortDate",m[H].a[E].Va);
var Ib={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};m[H].a.pd=36E5;m[H].a.bf=6E4;m[H].a.af=864E5;
m[H].a[E].mc=function(a){var d=(new Date)[Ga](),e=a[Ga]();if(d<e)return P["n-minutes-ago"](2);d=d-e;if(d<m[H].a.pd){a=q[ua](d/m[H].a.bf);a=a<=1?2:a;return P["n-minutes-ago"](a)}if(d<m[H].a.af){a=q[ua](d/m[H].a.pd);if(a<=1)return P["one-hour-ago"];else{a=a;return P["n-hours-ago"](a)}}return this.Va(a)};O(m[H].a[E],"formatToRelativeDate",m[H].a[E].mc);m[H].a[E].$d=function(){this.Ih=this.gwsUrl=c;this.results=[]};O(m[H].a[E],"clearResults",m[H].a[E].$d);
m[H].a[E].zf=function(){this.ae&&this.ae();if(this.Ec!=-1){m[J][Ea]("asa_"+this.w,"req."+((new Date)[Ga]()-this.Ec),b);this.Ec=-1}};
m[H].a[E].W=function(a,d,e,f){if(!(a==c&&d==204)){this.gwsUrl=c;if(this.results&&this.results[D]>0)for(var h=0;h<this.results[D];h++)this.results[h].html&&Jb(this.results[h].html);if(a&&a.results&&a.results[D]>0){this.results=a.results;if(a[F]&&a[F].moreResultsUrl)this.gwsUrl=this.wa&&this.wa!=""?this.wa:a[F].moreResultsUrl;else if(this.u&&this.na)this.gwsUrl=this.dg()}else this.results=[];this.completionStatus=d;this.hashStatus=f;this.Yg=e;this.ze=a&&a.resultAttribution&&a.resultAttribution!=c&&
a.resultAttribution!=""?a.resultAttribution:c;if(a&&a[F]&&a[F].pages&&a[F].pages[D]>0)this.cursor=a[F];else typeof this[F]!="undefined"&&delete this[F];if(a&&a.context)this.context=a.context;else typeof this.context!="undefined"&&delete this.context;if(a&&a.promotions)this.promotions=a.promotions;else typeof this.promotions!="undefined"&&delete this.promotions;if(a&&a.omittedResults)this.omittedResults=a.omittedResults;else typeof this.omittedResults!="undefined"&&delete this.omittedResults;this.ke&&
this.hf();this.zf()}};O(m[H].a[E],"onSearchComplete",m[H].a[E].W);m[H].a[E].le=function(){var a=c;if(this.ze)a=U(this.ze,"gs-results-attribution");return a};O(m[H].a[E],"getAttribution",m[H].a[E].le);m[H].a[E].hf=function(){var a,d;for(a=0;a<this.results[D];a++){d=this.results[a];this.C(d)}};m[H].a[E].zb=function(a,d,e){e||(e=[c]);this.ae=R(a,d,e)};O(m[H].a[E],"setSearchCompleteCallback",m[H].a[E].zb);
m[H].a.ka=function(a,d){var e=g,f;if(a[D])for(var h=0;h<a[D];h++)if(a[h]==c){a[h]=d;f=h;e=b;break}if(!e){f=a[D];a[ra](d)}return f};O(m[H].a,"AllocateCompletionMapContext",m[H].a.ka);m[H].a[E].Bb=function(a){this.bb=a};O(m[H].a[E],"setUserDefinedLabel",m[H].a[E].Bb);m[H].a[E].yg=function(a){this.Cb=a};O(m[H].a[E],"setUserDefinedClassSuffix",m[H].a[E].yg);m[H].a[E].qg=function(){this.ke=g};O(m[H].a[E],"setNoHtmlGeneration",m[H].a[E].qg);
m[H].a.$a=function(a,d,e,f,h){var l=q.min(q.min(e[x]/a,e[Xa]/d),1),n={};ja(n,q[ta](a*l));u(n,q[ta](d*l));if(f){ja(f,n[x]);u(f,n[Xa]);if(h)f[G].left=(e[x]-n[x])/2+"px"}return n};O(m[H].a,"scaleImage",m[H].a.$a);m[H].a.Qd=1;O(m[H].a,"VERTICAL_BRANDING",m[H].a.Qd);m[H].a.Oe=2;O(m[H].a,"HORIZONTAL_BRANDING",m[H].a.Oe);
m[H].a.Cf=function(a,d,e){var f=d&&d==m[H].a.Qd,h=new Hb("gsc-");d=V(h.bc);var l=nb(c,c,h.bc);T(d,l);f=!f;if(!f){Z(d,h.Sb);Z(l,h.Sb)}var n=ob(l,0),y,B;if(f)B=y=n;else{y=n;B=ob(l,0)}var W="/css/small-logo.png",S=51;n=15;if(e)if(typeof e=="string")if(e[za](/^http:\/\/www\.youtube\.com/)){W="/css/youtube-logo-55x24.png";S=55;n=24;Z(d,h.bc+"-youtube");if(!f){Z(d,h.Sb+"-youtube");Z(l,h.Sb+"-youtube")}}f=X(y,h.text);l=X(B,h.qe);y=U(P["powered-by"],h.text);W=m[J][Fa]+W;S=S;n=n;B=h.qe;if(Fb&&!Gb){B=V(B);
B[G].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+W+'")';ja(B[G],S+"px");u(B[G],n+"px")}else B=qb(W,c,c,B);n=B;T(f,y);if(e){f="http://www.google.com";if(typeof e=="string"&&(e[za](/^http:\/\/[a-z]*\.google\.com/)||e[za](/^http:\/\/www\.youtube\.com/)))f=e;e=rb(f,c,"_BLANK");t(e,h.of);T(e,n);T(l,e)}else T(l,n);if(a){a=typeof a=="string"?p.getElementById(a):a;ib(a);T(a,d)}return d};O(m[H].a,"getBranding",m[H].a.Cf);m[H].a.setOnLoadCallback=function(a,d){m.setOnLoadCallback(a,d)};
O(m[H].a,"setOnLoadCallback",m[H].a.setOnLoadCallback);var Kb;function Jb(a){Kb||(Kb=p[A]("DIV"));Kb[v](a);r(Kb,"")}m[H].a[E].Af=function(a){var d=this.lb;if(a)d=a;a={};var e=V(this.ia());Z(e,"gs-result");Z(e,"gs-error-result");d=U(d,"gs-snippet");T(e,d);a.html=e;return a};m[H].a[E].Bf=function(a){var d=this.rb;if(a)d=a;a={};var e=V(this.ia());Z(e,"gs-result");Z(e,"gs-no-results-result");d=U(d,"gs-snippet");T(e,d);a.html=e;return a};j("google.search.CurrentLocale",ea);
j("google.search.ShortDatePattern",aa);m[H].q=function(){m[H].a[I](this);this.w="blog";this.Ba="/GblogSearch";this.na="http://blogsearch.google.com/blogsearch";this.l=c;this.N=g;this.Ta=b;this.fa=hb(this,m[H].q[E].oa);this.Sa="gsc-blogConfig";this.o=c};N("google.search.BlogSearch",m[H].q);$a(m[H].q,m[H].a);m[H].q.B="GblogSearch";O(m[H].q,"RESULT_CLASS",m[H].q.B);m[H].q.n=[];m[H].q.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].q.n[l];m[H].q.n[l]=c;a.W(d,e,f,h)};O(m[H].q,"RawCompletion",m[H].q.I);
m[H].q[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].q.n,this):e;d=this.ya(d==c?"google.search.BlogSearch.RawCompletion":d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;if(this.l)a=a+" blogurl:"+this.l;a="&q="+i(a);if(this.N)a+="&scoring=d";d+=a;this.u=a}return d};
m[H].q[E].C=function(a){a.html&&delete a.html;var d=V(this.ia());Z(d,"gs-result");var e;e=Y(a.postUrl,a[Ha],this.s(),"gs-title");T(d,e);e=new Date(a.publishedDate);e=U(this.Va(e),"gs-publishedDate");T(d,e);e=new Date(a.publishedDate);e=U(this.mc(e),"gs-relativePublishedDate");T(d,e);e=U(a[va],"gs-snippet");T(d,e);e=Y(a.blogUrl,a.blogUrl,this.s(),"gs-visibleUrl");T(d,e);a.html=d;this.ta(a.html)};O(m[H].q[E],"createResultHtml",m[H].q[E].C);m[H].q[E].qa=function(a){this.l=a==c||a==""?c:a};
O(m[H].q[E],"setSiteRestriction",m[H].q[E].qa);m[H].q[E].K=function(a){this.N=a==m[H].a.ma?b:g};O(m[H].q[E],"setResultOrder",m[H].q[E].K);
m[H].q[E].oa=function(a,d){if(d){if(this.o==c){d=V("gsc-configSetting");this.o=xb(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.o);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,ub(P[Ra],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else na(this.o,this.N);this.o[Ba]()}else if(this.o)this.o[Ka]?this.K(m[H].a.ma):this.K(m[H].a.eb)};m[H].k=function(){m[H].a[I](this);this.w="book";this.Ba="/GbookSearch";this.na="http://books.google.com/books";this.Jb=g;this.Gc=c};N("google.search.BookSearch",m[H].k);$a(m[H].k,m[H].a);m[H].k.B="GbookSearch";O(m[H].k,"RESULT_CLASS",m[H].k.B);m[H].k.Pd="user-list";O(m[H].k,"USER_LIST",m[H].k.Pd);m[H].k.Hd=1;O(m[H].k,"TYPE_ALL_BOOKS",m[H].k.Hd);m[H].k.Ld=2;O(m[H].k,"TYPE_FULL_VIEW_BOOKS",m[H].k.Ld);m[H].k.n=[];
m[H].k.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].k.n[l];m[H].k.n[l]=c;a.W(d,e,f,h)};O(m[H].k,"RawCompletion",m[H].k.I);m[H].k[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].k.n,this):e;d=this.ya(d==c?"google.search.BookSearch.RawCompletion":d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a);if(this.Jb)a+="&as_brr=1";if(this.Gc)a=a+"&as_list="+this.Gc;d+=a;this.u=a}return d};
m[H].k[E].C=function(a){a.html&&delete a.html;a.thumbnailHtml=this.hc(a);var d=V(this.ia());Z(d,"gs-result");var e=V("gs-text-box"),f=nb(),h=ob(f,0),l=X(h,"gs-image-box");h=X(h,"gs-text-box");T(l,a.thumbnailHtml[Ca](b));T(h,e);T(d,f);f=Y(a.unescapedUrl,a[Ha],this.s(),"gs-title");T(e,f);f=U(P.by+"&nbsp;"+a.authors,"gs-author");T(e,f);f=V("gs-spacer");T(e,f);if(a.publishedYear){f=U(a.publishedYear,"gs-publishedDate");T(e,f)}if(ca(a.pageCount,10)>0){f=U("-&nbsp;"+P["page-count"](a.pageCount),"gs-pageCount");
T(e,f)}f=Y("http://books.google.com","books.google.com",this.s(),"gs-visibleUrl");T(e,f);a.html=d;this.ta(a.html)};O(m[H].k[E],"createResultHtml",m[H].k[E].C);
m[H].k[E].hc=function(a){var d=V("gs-image-box gs-book-image-box"),e=V("gs-row-1"),f=qb("http://books.google.com/googlebooks/pages-trans.gif",c,c,"gs-pages");T(e,f);f=qb("http://books.google.com/googlebooks/p_edge-trans.gif",c,c,"gs-page-edge");T(e,f);T(d,e);e=V("gs-row-2");f=m[H].a.$a(a.tbWidth,a.tbHeight,this.M);f=qb(a.tbUrl,f[x],f[Xa],"gs-image");a=rb(a.unescapedUrl,c,this.s(),"gs-image");t(a,"gs-image");T(a,f);T(e,a);T(d,e);return d};
m[H].k[E].R=function(a,d){if(a==m[H].a.Db)if(d)if(d==m[H].k.Hd)this.Jb=g;else if(d==m[H].k.Ld)this.Jb=b;else this.R(a,c);else this.Jb=g;else if(a==m[H].k.Pd)this.Gc=d&&d[za](/^[a-zA-Z0-9\-_]*$/)?d:c};O(m[H].k[E],"setRestriction",m[H].k[E].R);m[H].c=function(){m[H].a[I](this);this.we=2;this.w="image";this.Ba="/GimageSearch";this.na="http://images.google.com/images";this.l=this.yc=this.lc=this.rc=this.pc=this.oc=this.qc=this.Ha=c;this.M={width:112,height:84}};N("google.search.ImageSearch",m[H].c);$a(m[H].c,m[H].a);m[H].c.B="GimageSearch";O(m[H].c,"RESULT_CLASS",m[H].c.B);m[H].c.yd="restrict-imagesize";O(m[H].c,"RESTRICT_IMAGESIZE",m[H].c.yd);m[H].c.Se=["icon"];O(m[H].c,"IMAGESIZE_SMALL",m[H].c.Se);m[H].c.Re=["small","medium","large","xlarge"];
O(m[H].c,"IMAGESIZE_MEDIUM",m[H].c.Re);m[H].c.Qe=["xxlarge"];O(m[H].c,"IMAGESIZE_LARGE",m[H].c.Qe);m[H].c.Pe=["huge"];O(m[H].c,"IMAGESIZE_EXTRA_LARGE",m[H].c.Pe);m[H].c.vd="restrict-coloration";O(m[H].c,"RESTRICT_COLORIZATION",m[H].c.vd);m[H].c.Kc="mono";O(m[H].c,"COLORIZATION_BLACK_AND_WHITE",m[H].c.Kc);m[H].c.Mc="gray";O(m[H].c,"COLORIZATION_GRAYSCALE",m[H].c.Mc);m[H].c.Lc="color";O(m[H].c,"COLORIZATION_COLOR",m[H].c.Lc);m[H].c.ud="restrict-colorfilter";O(m[H].c,"RESTRICT_COLORFILTER",m[H].c.ud);
m[H].c.Vc="red";O(m[H].c,"COLOR_RED",m[H].c.Vc);m[H].c.Sc="orange";O(m[H].c,"COLOR_ORANGE",m[H].c.Sc);m[H].c.Yc="yellow";O(m[H].c,"COLOR_YELLOW",m[H].c.Yc);m[H].c.Rc="green";O(m[H].c,"COLOR_GREEN",m[H].c.Rc);m[H].c.Wc="teal";O(m[H].c,"COLOR_TEAL",m[H].c.Wc);m[H].c.Oc="blue";O(m[H].c,"COLOR_BLUE",m[H].c.Oc);m[H].c.Uc="purple";O(m[H].c,"COLOR_PURPLE",m[H].c.Uc);m[H].c.Tc="pink";O(m[H].c,"COLOR_PINK",m[H].c.Tc);m[H].c.Xc="white";O(m[H].c,"COLOR_WHITE",m[H].c.Xc);m[H].c.Qc="gray";
O(m[H].c,"COLOR_GRAY",m[H].c.Qc);m[H].c.Nc="black";O(m[H].c,"COLOR_BLACK",m[H].c.Nc);m[H].c.Pc="brown";O(m[H].c,"COLOR_BROWN",m[H].c.Pc);m[H].c.xd="restrict-filetype";O(m[H].c,"RESTRICT_FILETYPE",m[H].c.xd);m[H].c.bd="jpg";O(m[H].c,"FILETYPE_JPG",m[H].c.bd);m[H].c.cd="png";O(m[H].c,"FILETYPE_PNG",m[H].c.cd);m[H].c.ad="gif";O(m[H].c,"FILETYPE_GIF",m[H].c.ad);m[H].c.$c="bmp";O(m[H].c,"FILETYPE_BMP",m[H].c.$c);m[H].c.zd="restrict-imagetype";O(m[H].c,"RESTRICT_IMAGETYPE",m[H].c.zd);m[H].c.ed="face";
O(m[H].c,"IMAGETYPE_FACES",m[H].c.ed);m[H].c.dd="clipart";O(m[H].c,"IMAGETYPE_CLIPART",m[H].c.dd);m[H].c.fd="lineart";O(m[H].c,"IMAGETYPE_LINEART",m[H].c.fd);m[H].c.gd="news";O(m[H].c,"IMAGETYPE_NEWS",m[H].c.gd);m[H].c.hd="photo";O(m[H].c,"IMAGETYPE_PHOTO",m[H].c.hd);m[H].c.td="restrict";O(m[H].c,"RESTRICT",m[H].c.td);m[H].c.wd="cc_attribute";O(m[H].c,"RESTRICT_CREATIVE_COMMONS",m[H].c.wd);m[H].c.n=[];m[H].c.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].c.n[l];m[H].c.n[l]=c;a.W(d,e,f,h)};
O(m[H].c,"RawCompletion",m[H].c.I);
m[H].c[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].c.n,this):e;d=this.ya(d==c?"google.search.ImageSearch.RawCompletion":d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a);if(this.Ha)a=a+"&safe="+this.Ha;if(this.qc)a=a+"&imgsz="+i(this.qc);if(this.oc)a=a+"&imgc="+i(this.oc);if(this.pc)a=a+"&imgcolor="+i(this.pc);if(this.rc)a=a+"&imgtype="+i(this.rc);if(this.lc)a=a+"&as_filetype="+i(this.lc);if(this.yc)a=a+"&restrict="+i(this.yc);if(this.l)a=a+"&as_sitesearch="+i(this.l);d+=a;this.u=a;if(f&&f!=
0)this.u=this.u+"&start="+f}return d};
m[H].c[E].C=function(a){a.html&&delete a.html;var d=V(this.ia());Z(d,"gs-result");var e=V("gs-image-box"),f=m[H].a.$a(a.tbWidth,a.tbHeight,this.M),h=qb(a.tbUrl,f[x],f[Xa],"gs-image");h[G].left=(this.M[x]-f[x])/2+"px";s(h,a.titleNoFormatting+" ("+a.visibleUrl+")");f=rb(a.unescapedUrl,c,this.s(),"gs-image");t(f,"gs-image");T(f,h);T(e,f);T(d,e);e=V("gs-text-box");h=U(a[va],"gs-snippet");s(h,a.contentNoFormatting);T(e,h);h=U(a[x]+" x "+a[Xa],"gs-size");T(e,h);h=Y(a.originalContextUrl,a.visibleUrl,this.s(),
"gs-visibleUrl");s(h,a.visibleUrl);T(e,h);T(d,e);a.html=d;this.ta(a.html)};O(m[H].c[E],"createResultHtml",m[H].c[E].C);m[H].c[E].qa=function(a){this.l=a};O(m[H].c[E],"setSiteRestriction",m[H].c[E].qa);
m[H].c[E].R=function(a,d){if(a==m[H].a.Ub)this.Ha=d?d==m[H].a.Wb||d==m[H].a.Vb?d:c:c;else if(a==m[H].c.yd)this.qc=d?d.join("|"):c;else if(a==m[H].c.vd)this.oc=d?d==m[H].c.Kc||d==m[H].c.Mc||d==m[H].c.Lc?d:c:c;else if(a==m[H].c.ud)this.pc=d?d==m[H].c.Vc||d==m[H].c.Sc||d==m[H].c.Yc||d==m[H].c.Rc||d==m[H].c.Wc||d==m[H].c.Oc||d==m[H].c.Uc||d==m[H].c.Tc||d==m[H].c.Xc||d==m[H].c.Qc||d==m[H].c.Nc||d==m[H].c.Pc?d:c:c;else if(a==m[H].c.xd)this.lc=d?d==m[H].c.bd||d==m[H].c.cd||d==m[H].c.ad||d==m[H].c.$c?d:c:
c;else if(a==m[H].c.zd)this.rc=d?d==m[H].c.ed||d==m[H].c.dd||d==m[H].c.fd||d==m[H].c.gd||d==m[H].c.hd?d:c:c;else if(a==m[H].c.td)this.yc=d?d==m[H].c.wd?d:c:c};O(m[H].c[E],"setRestriction",m[H].c[E].R);m[H].e=function(){m[H].a[I](this);this.ba=c;this.aa="San Francisco, CA";this.ea={y:37.77916,x:-122.42009};this.Ra=c;this.qb=b;this.fb=g;this.Za=c;this.Ta=b;this.fa=hb(this,this.oa);this.Sa="gsc-locationConfig";this.w="local";this.Ba="/GlocalSearch";this.na="http://www.google.com/local";this.Pa=this.G=c};N("google.search.LocalSearch",m[H].e);$a(m[H].e,m[H].a);m[H].e.B="GlocalSearch";O(m[H].e,"RESULT_CLASS",m[H].e.B);m[H].e.Kd="blended";O(m[H].e,"TYPE_BLENDED_RESULTS",m[H].e.Kd);m[H].e.Nd="kmlonly";
O(m[H].e,"TYPE_KMLONLY_RESULTS",m[H].e.Nd);m[H].e.Od="localonly";O(m[H].e,"TYPE_LOCALONLY_RESULTS",m[H].e.Od);m[H].e.Hc="disabled";O(m[H].e,"ADDRESS_LOOKUP_DISABLED",m[H].e.Hc);m[H].e.Ic="enabled";O(m[H].e,"ADDRESS_LOOKUP_ENABLED",m[H].e.Ic);m[H].e.Ed=17;O(m[H].e,"STATIC_MAP_ZOOM_FARTHEST",m[H].e.Ed);m[H].e.df=4;O(m[H].e,"STATIC_MAP_ZOOM_DEFAULT",m[H].e.df);m[H].e.Dd=0;O(m[H].e,"STATIC_MAP_ZOOM_CLOSEST",m[H].e.Dd);m[H].e.$b=8;O(m[H].e,"STATIC_MAP_MAX_POINTS",m[H].e.$b);m[H].e.cg=3.141592653589;
m[H].e.yf=6367E3;m[H].e.Eg=16093;m[H].e.n=[];m[H].e.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].e.n[l];m[H].e.n[l]=c;a.resultViewport=d&&d.viewport?d.viewport:c;a.W(d,e,f,h)};O(m[H].e,"RawCompletion",m[H].e.I);
m[H].e[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].e.n,this):e;d=this.ya(d==c?"google.search.LocalSearch.RawCompletion":d,e,f);f="";if(a){f="&q="+i(a);d+=f}this.$h=c;if(this.ba){var h;if(this.qb){e=this.ba.getCenterLatLng();h=this.ba.getSpanLatLng();a="&sll="+e.y+","+e.x;a+="&sspn="+h[Xa]+","+h[x]}else{e=this.ba.getCenter();h=this.ba.getBounds().toSpan().toUrlValue();a="&sll="+e.y+","+e.x;a+="&sspn="+h}a+=m[H].e.cc(e.y,e.x);d+=a;f+=a}else if(this.ea){a="&sll="+this.ea.y+","+this.ea.x;if(this.Ra)a=
a+"&sspn="+this.Ra.lat+","+this.Ra.lng;a+=m[H].e.cc(this.ea.y,this.ea.x);d+=a;f+=a}else if(this.aa){a="&near="+i(this.aa);d+=a;f+=a}if(this.fb){d+="&nogeocode=t";f+="&nogeocode=t"}if(this.Za){d+="&mrt="+i(this.Za);f+="&mrt="+i(this.Za)}if(f)this.u=f;return d};m[H].e.cc=function(a,d){var e=2*m[H].e.Eg/m[H].e.yf*2*m[H].e.cg,f=d-e,h=a+e;d=d+e;return"&gll="+q[ua]((a-e)*1E6)+","+q[ua](f*1E6)+","+q[ua](h*1E6)+","+q[ua](d*1E6)+"&llsep=500,500"};O(m[H].e,"centerToGll",m[H].e.cc);
m[H].e[E].C=function(a){a.html&&delete a.html;var d=V(this.ia());Z(d,"gs-result");var e;e=Y(a.url,a[Ha],this.s(),"gs-title");T(d,e);if(a.listingType=="kml"&&a[va]&&a[va]!=""){e=U(a[va],"gs-snippet");T(d,e)}var f=V("gs-address");if(a.addressLines&&a.addressLines[D]>0)for(var h=0;h<a.addressLines[D];h++){e=a.addressLines[h];var l="gs-addressLine";if(h==0)l="gs-street gs-addressLine";else if(h==1)l="gs-city gs-addressLine";e=U(e,l);T(f,e)}else{e=U(a.streetAddress,"gs-street");T(f,e);h="";if(a.city!=
""){h=a.city;if(a.region!="")h+=", "}e=U(h,"gs-city");T(f,e);e=U(a.region,"gs-region");T(f,e)}e=U(a.country,"gs-country");T(f,e);T(d,f);if(a.phoneNumbers&&a.phoneNumbers[D]){h=f=c;e=a.phoneNumbers[0];for(var n=0;n<a.phoneNumbers[D];n++){l=a.phoneNumbers[n];if(l[Da]=="main"){f=l;break}if(l[Da]==""||l[Da]=="mobile"&&h==c)h=l}l=f?f:h?h:e;e=U(l.number,"gs-phone");T(d,e)}if(a.ddUrl&&a.ddUrl!=""){e=Y(a.ddUrl,P.directions,this.s(),"gs-directions");T(d,e)}if(a.ddUrlToHere&&a.ddUrlToHere!=""&&a.ddUrlFromHere&&
a.ddUrlFromHere!=""){e=V("gs-directions-to-from");f=U(P["get-directions"]+":","gs-label");e[v](f);f=Y(a.ddUrlToHere,P["to-here"],this.s(),"gs-secondary-link");e[v](f);f=U("-","gs-spacer");e[v](f);f=Y(a.ddUrlFromHere,P["from-here"],this.s(),"gs-secondary-link");e[v](f);T(d,e)}a.html=d;this.ta(a.html)};O(m[H].e[E],"createResultHtml",m[H].e[E].C);
m[H].e[E].Ce=function(a){if(a.centerAndZoom){this.qb=b;this.ba=a;this.ea=c;this.aa="";if(this.G)this.G=c}else if(a.setCenter){this.qb=g;this.ba=a;this.Ra=this.ea=c;this.aa="";if(this.G)this.G=c}else if(a.x&&a.y){this.qb=b;this.ea=a;this.ba=this.Ra=c;this.aa="";if(this.G)this.G=c}else if(a!=c&&a!=""){this.qb=b;this.ba=c;this.aa=a;this.ea=c;if(this.G)this.G=c;var d=new m[H].e;d.zb(this,this.gf,[d,a]);d[L](a)}};O(m[H].e[E],"setCenterPoint",m[H].e[E].Ce);
m[H].e[E].gf=function(a,d){if(a.results&&a.results[D]){var e={};e.y=da(a.results[0].lat);e.x=da(a.results[0].lng);this.ea=e;this.aa=d;this.Ta=b;this.ba=c;if(a.resultViewport){d={};d.ph=da(a.resultViewport.span.lat)/2;d.qh=da(a.resultViewport.span.lng)/2;this.Ra=d}}};
m[H].e[E].oa=function(a,d){if(d){if(this.G==c){d=c;if(this.ba==c){var e=V("gsc-configSetting");this.G=vb(c,"gsc-configSettingInput",this.aa==""?c:this.aa);T(e,U(P["search-location"],"gsc-configSettingInputLabel"));T(e,this.G);T(a,e);d=this.G}e=V("gsc-configSetting");this.Pa=xb(c,"0",this.fb,"gsc-configSettingCheckbox");T(e,this.Pa);T(e,U(P["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(d==c)d=this.Pa;var f=U(c,"gsc-configSettingSubmit");T(f,ub(P[Ra],"gsc-configSettingSubmit"));T(e,
f);T(a,e);d[Ba]()}}else{if(this.G){if(this.G[xa]){this.aa=this.G[xa];this.Ce(this.aa)}this.G=c}if(this.Pa){this.fb=this.Pa[Ka];this.Pa=c}ib(a)}};m[H].e[E].lg=function(a){if(a==m[H].e.Hc)this.fb=b;else if(a==m[H].e.Ic)this.fb=g};O(m[H].e[E],"setAddressLookupMode",m[H].e[E].lg);m[H].e.ye=function(a,d,e,f){var h=a.staticMapUrl;h=h[z](/&h=\d*/,"&h="+d);h=h[z](/&w=\d*/,"&w="+e);if(f&&f>=m[H].e.Dd&&f<=m[H].e.Ed)h=h[z](/&zl=\d*/,"&zl="+f);return a.staticMapUrl=h};O(m[H].e,"resizeStaticMapUrl",m[H].e.ye);
m[H].e.rf=function(a,d,e,f){var h="",l="http://mt.google.com/mapdata?cc=us&tstyp=5&zl=4&w=150&h=100",n={};n.staticMapUrl=l;l=m[H].e.ye(n,d,e,f);if(f==c)l=l[z](/&zl=\d*/,"");d=a[D];if(d>m[H].e.$b)d=m[H].e.$b;for(e=0;e<d;e++){n=a[e];if(n.lat&&n.lng)if(typeof n.lat=="string"){f=da(n.lat);n=da(n.lng)}else{f=n.lat;n=n.lng}else if(n.x&&n.y){f=n.y;n=n.x}else return c;n=n*1E6;f="&Point=b&Point.latitude_e6=__LAT__&Point.longitude_e6=__LNG__&Point.iconid=__ICONID__&Point=e"[z](/__LAT__/,q[ua](f*1E6));f=f[z](/__LNG__/,
q[ua](n));n=51+e;if(d==1)n=15;f=f[z](/__ICONID__/,n);h+=f}return l+h};O(m[H].e,"computeStaticMapUrl",m[H].e.rf);m[H].e[E].R=function(a,d){if(a==m[H].a.Db)if(d){this.Za=c;this.Za=d==m[H].e.Kd||d==m[H].e.Nd||d==m[H].e.Od?d:c}else this.Za=c};O(m[H].e[E],"setRestriction",m[H].e[E].R);m[H].m=function(){m[H].a[I](this);this.w="news";this.Ba="/GnewsSearch";this.na="http://news.google.com/nwshp";this.Nh=c;this.ab="site:";this.N=g;this.Ta=b;this.fa=hb(this,this.oa);this.Sa="gsc-newsConfig";this.F=this.o=c};N("google.search.NewsSearch",m[H].m);$a(m[H].m,m[H].a);m[H].m.B="GnewsSearch";O(m[H].m,"RESULT_CLASS",m[H].m.B);m[H].m.sd="GnewsSearch.quote";O(m[H].m,"QUOTE_RESULT_CLASS",m[H].m.sd);m[H].m.n=[];
m[H].m.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].m.n[l];m[H].m.n[l]=c;a.W(d,e,f,h)};O(m[H].m,"RawCompletion",m[H].m.I);
m[H].m[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].m.n,this):e;d=this.ya(d==c?"google.search.NewsSearch.RawCompletion":d,e,f);if(a||!a&&this.F){e=c;if(a)e=a;if(this.H)e=e==c?this.H:e+" "+this.H;if(this.l)e=e==c?this.ab+this.l:e+" "+this.ab+this.l;a=e?"&q="+i(e):"";if(this.N)a+="&scoring=d";if(this.F){e="";for(var h in this.F)if(h.charAt(0)==":")e+="&"+this.F[h];a+=e}if(this.l&&this.ab=="source:")d=d[z](/&hl=.*&/,"&hl=en&");d+=a;this.u=a;if(f&&f!=0)this.u=this.u+"&start="+f}return d};
m[H].m[E].C=function(a){a.html&&delete a.html;if(a.GsearchResultClass!=m[H].m.sd){var d=V(this.ia());Z(d,"gs-result");var e;e=Y(a.unescapedUrl,a[Ha],this.s(),"gs-title");T(d,e);e=U(a.publisher,"gs-publisher");T(d,e);e=a[Pa][Na](",");if(e[D]>1){e=U(", "+e[e[D]-1],"gs-location");T(d,e)}e=new Date(a.publishedDate);e=U(" - "+this.Va(e),"gs-publishedDate");T(d,e);e=new Date(a.publishedDate);e=U(" - "+this.mc(e),"gs-relativePublishedDate");T(d,e);e=U(a[va],"gs-snippet");T(d,e);if(a.clusterUrl&&a.clusterUrl!=
""){e=Y(a.clusterUrl,P["related-articles"]+"&nbsp;&raquo;",this.s(),"gs-clusterUrl");T(d,e)}a.html=d;this.ta(a.html)}};O(m[H].m[E],"createResultHtml",m[H].m[E].C);m[H].m[E].qa=function(a){if(a==c||a==""){this.l=c;this.ab="site:"}else if(a[za]("[./:]")){this.ab="site:";this.l=a}else{this.ab="source:";this.l=a[z](/\s/g,"_")}};O(m[H].m[E],"setSiteRestriction",m[H].m[E].qa);m[H].m[E].K=function(a){this.N=a==m[H].a.ma?b:g};O(m[H].m[E],"setResultOrder",m[H].m[E].K);
m[H].m[E].oa=function(a,d){if(d){if(this.o==c){d=V("gsc-configSetting");this.o=xb(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.o);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,ub(P[Ra],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else na(this.o,this.N);this.o[Ba]()}else if(this.o)this.o[Ka]?this.K(m[H].a.ma):this.K(m[H].a.eb)};m[H].m[E].jf={geo:b,qsid:b,quotesearch:b,topic:b,ned:b,scoring:b,as_mind:b,as_minm:b,as_miny:b,as_maxd:b,as_maxm:b,as_maxy:b};
m[H].m[E].R=function(a,d){if(a==m[H].a.Na)if(d)for(var e in d){a=d[e];if(typeof this.jf[e]!="undefined"){this.F=this.F||{};this.F[":"+e]=e+"="+i(a)}}else this.F=c};O(m[H].m[E],"setRestriction",m[H].m[E].R);m[H].h=function(){m[H].a[I](this);this.w="patent";this.Ba="/GpatentSearch";this.na="http://www.google.com/patents";this.Je="";this.tb=c;this.Ta=b;this.fa=hb(this,this.oa);this.Sa="gsc-patentConfig";this.o=c};N("google.search.PatentSearch",m[H].h);$a(m[H].h,m[H].a);m[H].h.B="GpatentSearch";O(m[H].h,"RESULT_CLASS",m[H].h.B);m[H].h.Id=1;O(m[H].h,"TYPE_ANY_STATUS",m[H].h.Id);m[H].h.Md=2;O(m[H].h,"TYPE_ISSUED_PATENTS",m[H].h.Md);m[H].h.Jd=3;O(m[H].h,"TYPE_APPLICATIONS",m[H].h.Jd);m[H].h.n=[];
m[H].h.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].h.n[l];m[H].h.n[l]=c;a.W(d,e,f,h)};O(m[H].h,"RawCompletion",m[H].h.I);m[H].h[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].h.n,this):e;d=this.ya(d==c?"google.search.PatentSearch.RawCompletion":d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a)+this.Je;if(this.tb)a+=this.tb;d+=a;this.u=a}return d};
m[H].h[E].C=function(a){a.html&&delete a.html;a.thumbnailHtml=this.hc(a);var d=V(this.ia());Z(d,"gs-result");var e=V("gs-text-box"),f=nb(),h=ob(f,0),l=X(h,"gs-image-box");h=X(h,"gs-text-box");T(l,a.thumbnailHtml[Ca](b));T(h,e);T(d,f);l=Y(a.unescapedUrl,a[Ha],this.s(),"gs-title");T(e,l);f=V("gs-patent-info gs-metadata");T(e,f);l=c;l=a.patentNumber?a.patentStatus=="issued"?P["us-pat"]+"&nbsp;"+a.patentNumber:P["us-pat-app"]+"&nbsp;"+a.patentNumber:P["us-pat-app"]+"&nbsp; N/A";l=U(l,"gs-patent-number");
T(f,l);if(a.applicationDate){l=U(" - "+this.Va(new Date(a.applicationDate)),"gs-publishedDate");T(f,l)}if(a.assignee){l=U(" - "+a.assignee,"gs-author");T(f,l)}l=U(a[va],"gs-snippet");T(e,l);T(e,l);a.html=d;this.ta(a.html)};O(m[H].h[E],"createResultHtml",m[H].h[E].C);m[H].h[E].hc=function(a){var d=V("gs-patent-image"),e=qb(a.tbUrl,75,100,"gs-image");a=rb(a.unescapedUrl,c,this.s(),"gs-image");t(a,"gs-image");T(a,e);T(d,a);return d};
m[H].h[E].K=function(a){this.tb=a==m[H].a.ma?"&scoring=d":a==m[H].a.rd?"&scoring=ad":c};O(m[H].h[E],"setResultOrder",m[H].h[E].K);m[H].h[E].R=function(a,d){if(a==m[H].a.Db)this.Je=d?d==m[H].h.Id?"":d==m[H].h.Md?"&as_psrg=1":d==m[H].h.Jd?"&as_psra=1":"":""};O(m[H].h[E],"setRestriction",m[H].h[E].R);
m[H].h[E].oa=function(a,d){if(d){var e=g;if(this.tb&&this.tb=="&scoring=d")e=b;if(this.o==c){d=V("gsc-configSetting");this.o=xb(c,"0",e,"gsc-configSettingCheckbox");T(d,this.o);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));e=V("gsc-configSettingSubmit");T(e,ub(P[Ra],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else na(this.o,e);this.o[Ba]()}else if(this.o)this.o[Ka]?this.K(m[H].a.ma):this.K(m[H].a.eb)};m[H].A=function(){this.xe=this.$=m[H].b.Da;this.i=c;this.M={width:112,height:84};this.Tb={width:100,height:75};this.rb=c};N("google.search.SearcherOptions",m[H].A);m[H].A[E].Ee=function(a){switch(a){case m[H].b.Zc:case m[H].b.La:case m[H].b.Da:this.$=a;break;default:this.$=m[H].b.Da;break}this.xe=this.$};O(m[H].A[E],"setExpandMode",m[H].A[E].Ee);m[H].A[E].tg=function(a){ib(a);this.i=a};O(m[H].A[E],"setRoot",m[H].A[E].tg);m[H].A[E].yb=function(a){this.rb=a};O(m[H].A[E],"setNoResultsString",m[H].A[E].yb);
m[H].A[E].ng=function(a){if(a>100)a=100;u(this.M,a);ja(this.M,q[ta](a*1.33))};O(m[H].A[E],"setImageResultsTbHeight",m[H].A[E].ng);m[H].A[E].zg=function(a){if(a>100)a=100;u(this.Tb,a);ja(this.Tb,q[ta](a*1.33))};O(m[H].A[E],"setVideoResultsTbHeight",m[H].A[E].zg);m[H].T=function(){ia(this,c);this.Ie=c;this.Z=m[H].b.ra};N("google.search.DrawOptions",m[H].T);m[H].T[E].og=function(a){ia(this,a)};O(m[H].T[E],"setInput",m[H].T[E].og);
m[H].T[E].ug=function(a){if(a&&typeof a=="string")a=p.getElementById(a);this.Ie=a};O(m[H].T[E],"setSearchFormRoot",m[H].T[E].ug);m[H].T[E].De=function(a){this.Z=a==m[H].b.ra||a==m[H].b.Ka?a:m[H].b.ra};O(m[H].T[E],"setDrawMode",m[H].T[E].De);
m[H].z=function(a,d,e){this.t=e;this.fc=this.kc=g;this.f=a;this.v=c;this.hg=R(d,m[H].b[E].bg,[this]);this.kg=R(d,m[H].b[E].wc,[this,m[H].z.Zb]);this.jg=R(d,m[H].b[E].wc,[this,m[H].z.Yb]);this.ig=R(d,m[H].b[E].wc,[this,m[H].z.Cd]);this.gg=R(d,m[H].b[E].ag,[this]);this.fg=R(d,m[H].b[E].Xf,[this]);this.f.zb(d,m[H].b[E].W,[this]);this.f.S(d.Mb);this.f.xb(d.Fa);this.Q=this.Ua=this.va=this.zc=this.nb=this.Rb=this.i=c;this.pb=b};m[H].z.Xb=0;m[H].z.Zb=1;m[H].z.Yb=2;m[H].z.Cd=3;
m[H].z[E].Dc=function(a){var d="gsc-results-selector ";d+=a==m[H].z.Xb?this.t.$==m[H].b.Da?"gsc-one-result-active":this.f.za==m[H].a.X?"gsc-more-results-active":"gsc-all-results-active":a==m[H].z.Zb?"gsc-one-result-active":a==m[H].z.Yb?"gsc-more-results-active":"gsc-all-results-active";t(this.zc,d)};
m[H].b=function(a){if(!m[J].KeyVerified)if(m[H].b.ue())m[J].KeyVerified=b;else return;this.Vd=this.Mb=m[H].a.X;this.Z=m[H].b.ra;this.Nb=this.i=c;ia(this,c);this.Qb=m[H].b.Eb;this.Of=R(this,m[H].b[E].Yf,[c]);this.Pf=R(this,m[H].b[E].Zf,[c]);this.Xa=this.ub=this.Bc=this.Lb=c;this.gb=this.Uf=g;this.Fa=m[H].a.db;this.sc=P.copy;this.d=[];this.Qg=[];var d;if(a)for(var e=0;e<a[D];e++){d=new m[H].z(a[e],this,g);this.d[ra](d)}};N("google.search.SearchControl",m[H].b);m[H].b.qd=P["no-results"];
O(m[H].b,"NO_RESULTS_DEFAULT_STRING",m[H].b.qd);m[H].b.Gd=350;O(m[H].b,"TIMEOUT_SHORT",m[H].b.Gd);m[H].b.Eb=500;O(m[H].b,"TIMEOUT_MEDIUM",m[H].b.Eb);m[H].b.Fd=700;O(m[H].b,"TIMEOUT_LONG",m[H].b.Fd);m[H].b.Zc=1;O(m[H].b,"EXPAND_MODE_CLOSED",m[H].b.Zc);m[H].b.La=2;O(m[H].b,"EXPAND_MODE_OPEN",m[H].b.La);m[H].b.Da=3;O(m[H].b,"EXPAND_MODE_PARTIAL",m[H].b.Da);m[H].b.ra=1;O(m[H].b,"DRAW_MODE_LINEAR",m[H].b.ra);m[H].b.Ka=2;O(m[H].b,"DRAW_MODE_TABBED",m[H].b.Ka);m[H].b.nd="save";
O(m[H].b,"KEEP_LABEL_SAVE",m[H].b.nd);m[H].b.md="keep";O(m[H].b,"KEEP_LABEL_KEEP",m[H].b.md);m[H].b.ld="include";O(m[H].b,"KEEP_LABEL_INCLUDE",m[H].b.ld);m[H].b.kd="copy";O(m[H].b,"KEEP_LABEL_COPY",m[H].b.kd);m[H].b.jd="blank";O(m[H].b,"KEEP_LABEL_BLANK",m[H].b.jd);try{m[H].b.appPath=k[Pa].href}catch(Lb){m[H].b.appPath=c}
m[H].b.ue=function(){var a=b,d;d=k[Pa].host[Ya]()[Na](".");if(d[D]<2)d=g;else{var e=d.pop(),f=d.pop();if((f=="igoogle"||f=="gmodules"||f=="googlesyndication")&&e=="com")d=b;else{if(e[D]==2&&d[D]>0)if(Cb[f]&&Cb[f][e]==1)f=d.pop();d=f=="google"}}if(d)return b;if(m[J].LoadFailure)if(m[J].OriginalAppPath&&m[H].b.appPath){m[J].LoadFailure=g;a=b}m[J].KeyVerified=b;m[J].LoadFailure=g;return a};O(m[H].b,"keyCheck",m[H].b.ue);
m[H].b[E].jb=function(a,d){this.ua=b;this.Qa=a;if(d){if(d.includeVerticalAds!=o)this.Ca=d.includeVerticalAds;if(d.includeSideAds!=o)this.Ca=d.includeSideAds;if(d.iframes!=o)this.mb=d.iframes;if(d.useNarrowTopAd!=o)if(this.mb)this.Ig=d.useNarrowTopAd;if(d.channel)this.Sd=d.channel;if(d.clientIP)this.Td=d.clientIP;if(d.safe)this.Ud=d.safe;if(d[Oa])this.Wd=d[Oa];if(a=d.adtest||d.debug)this.ac=a;if(d.numTopAds!=o){this.Ga=d.numTopAds;this.Ga=q.max(0,q.min(4,this.Ga))}if(d.numSideAds!=o){this.xa=d.numSideAds;
this.Ca=(this.xa=q.max(0,q.min(8,this.xa)))?b:g}this.Be=d.enableSearchCompleteCallback?b:g}m[J][Ea]("hl","afs_ads")};O(m[H].b[E],"enableAds",m[H].b[E].jb);m[H].b[E].Oa=function(a,d){d||(d=new m[H].A);a.pa=c;this.d[ra](new m[H].z(a,this,d));if(this.vb(a))this.Jf=b;a.wb="gsc"};O(m[H].b[E],"addSearcher",m[H].b[E].Oa);
m[H].b[E].ce=function(a){if(this.d[a].t.i){this.d[a].pb=g;this.d[a].i=this.d[a].t.i;Z(this.d[a].i,"gsc-resultsRoot");$(this.d[a].i,"gsc-resultsbox-visible");Z(this.d[a].i,"gsc-resultsbox-invisible")}else this.d[a].i=V("gsc-resultsRoot");this.d[a].f.Cb&&wb(this.d[a].i,"gsc-resultsRoot-"+this.d[a].f.Cb);if(this.Z==m[H].b.Ka)this.p[a].ga=this.d[a].i;var d=nb(c,c,"gsc-resultsHeader"),e=ob(d,0);this.d[a].Ja=X(e,"gsc-twiddleRegionCell");e=X(e,"gsc-configLabelCell");this.d[a].Rb=U("","gsc-twiddle");T(this.d[a].Ja,
this.d[a].Rb);var f=lb(this.d[a].f.Ff(),"gsc-title");T(this.d[a].Rb,f);this.d[a].nb=U("","gsc-stats");T(this.d[a].Ja,this.d[a].nb);f=U();var h=U(P.blank,"gsc-result-selector gsc-one-result"),l=U(P.blank,"gsc-result-selector gsc-more-results"),n=U(P.blank,"gsc-result-selector gsc-all-results");s(h,P["show-one-result"]);s(l,P["show-more-results"]);s(n,P["show-all-results"]);T(f,h);T(f,l);T(f,n);oa(h,this.d[a].kg);oa(l,this.d[a].jg);oa(n,this.d[a].ig);this.d[a].zc=f;this.d[a].Dc(m[H].z.Xb);T(this.d[a].Ja,
this.d[a].zc);oa(this.d[a].Rb,this.d[a].hg);if(this.d[a].f.fa){this.d[a].P=mb("","gsc-configLabel");r(this.d[a].P,P.blank);Z(this.d[a].P,"gsc-twiddle-closed");T(e,this.d[a].P);oa(this.d[a].P,this.d[a].gg);s(this.d[a].P,P.settings);this.d[a].va=V("gsc-config");Z(this.d[a].va,this.d[a].f.Sa);this.d[a].Ua=tb("gsc-config");Z(this.d[a].Ua,this.d[a].f.Sa);this.d[a].Ua.onsubmit=this.d[a].fg;T(this.d[a].va,this.d[a].Ua);pa(this.d[a].va[G],"none")}this.d[a].Q=V("gsc-results");e=this.d[a].f.nc();Z(this.d[a].Q,
e);this.d[a].t.i==c&&T(this.Aa,this.d[a].i);T(this.d[a].i,d);this.d[a].va&&T(this.d[a].i,this.d[a].va);T(this.d[a].i,this.d[a].Q)};m[H].b[E].de=function(a){var d=this.d[a],e={},f=d.f.Hf();e.V=lb(f);e.ga=c;e.Cc=d.f;e.w=d.f.w;oa(e.V,R(this,this.Dg,[a]));this.p[a]=e;T(this.ca,e.V);a="gs-spacer";if(bb("opera"))a+=" gs-spacer-opera";a=mb(" ",a);T(this.ca,a);d.t.Ee(m[H].b.La)};
m[H].b[E].Ib=function(a,d){var e=c,f=c;if(d)if(d.Z){this.Z=d.Z;e=d[w];f=d.Ie}else this.Z=m[H].b.ra;else this.Z=m[H].b.ra;this.i=V("gsc-control");if(e!=c){ia(this,e);this[w].onkeyup=this.Of;this[w].onpaste=this.Pf}else{if(f==c)f=this.i;d=new m[H].L(b,f);d.Ge(this,this.submit);d.Fe(this,this.dc);ia(this,d[w]);this.kb&&d.Kf()}this.Aa=V("gsc-resultsbox-invisible");if(this.Z==m[H].b.Ka){this.ca=V("gsc-tabsAreaInvisible");T(this.i,this.ca);this.p=[];for(d=this.J=0;d<this.d[D];d++)this.de(d)}this.da=this.i;
if(this.ua){this.da=V("gsc-wrapper");this.O=V("gsc-adBlockInvisible");this.U=V("gsc-adBlockInvisible");T(this.da,this.O);T(this.i,this.U);T(this.i,this.da);this.ac&&wb(this.i,"gsc-ad-preview")}T(this.da,this.Aa);for(d=0;d<this.d[D];d++){this.ce(d);if(this.Z==m[H].b.Ka){Z(this.p[d].V,"gsc-tabHeader");Z(this.p[d].ga,"gsc-tabData");if(d==this.J){Z(this.p[d].V,"gsc-tabhActive");Z(this.p[d].ga,"gsc-tabdActive")}else{Z(this.p[d].V,"gsc-tabhInactive");Z(this.p[d].ga,"gsc-tabdInactive")}}}if(a&&typeof a==
"string")a=p.getElementById(a);if(a){jb(a,this.i);if((a=this.Df())&&a<300){this.Uf=b;Z(this.i,"gsc-narrow")}}};O(m[H].b[E],"draw",m[H].b[E].Ib);m[H].b[E].xg=function(a){switch(a){case m[H].b.Gd:case m[H].b.Eb:case m[H].b.Fd:this.Qb=a;break;default:this.Qb=m[H].b.Eb;break}};O(m[H].b[E],"setTimeoutInterval",m[H].b[E].xg);m[H].b[E].rg=function(a,d,e){if(e)switch(e){case m[H].b.nd:case m[H].b.md:case m[H].b.ld:case m[H].b.kd:case m[H].b.jd:this.sc=P[e];break;default:this.sc=e;break}this.Lb=hb(a,d)};
O(m[H].b[E],"setOnKeepCallback",m[H].b[E].rg);M=m[H].b[E];M.vb=function(a){var d=a.w;if(this.kb){if(d=="web"&&a.D!=m[H].g.Y)return g;return b}else return d=="blog"||d=="image"?b:g};
M.Dg=function(a){if(this.J!=a){$(this.p[this.J].V,"gsc-tabhActive");$(this.p[this.J].ga,"gsc-tabdActive");Z(this.p[this.J].V,"gsc-tabhInactive");Z(this.p[this.J].ga,"gsc-tabdInactive");this.J=a;Z(this.p[this.J].V,"gsc-tabhActive");Z(this.p[this.J].ga,"gsc-tabdActive");$(this.p[this.J].V,"gsc-tabhInactive");$(this.p[this.J].ga,"gsc-tabdInactive");if(this.ua)this.vb(this.p[this.J].Cc)?this.ob():this.fe()}};
M.ob=function(){if(this.ua){t(this.O,"gsc-adBlockInvisible");t(this.U,"gsc-adBlockInvisible");this.Ca&&zb(this.da,"gsc-thinWrapper")}};M.fe=function(){if(this.ua){this.vc>0?yb(this.O,"gsc-adBlock"):yb(this.O,"gsc-adBlockInvisible");if(this.Ca)if(this.uc>0){t(this.U,"gsc-adBlockVertical");Z(this.da,"gsc-thinWrapper")}else{t(this.U,"gsc-adBlockInvisible");$(this.da,"gsc-thinWrapper")}}};M.submit=function(){this[w][xa][D]?this[L]():this.dc();return g};O(m[H].b[E],"submit",m[H].b[E].submit);M=m[H].b[E];
M.Hb=function(){if(this.ca&&!this.Cg&&(!this.kb||this.Rd))t(this.ca,"gsc-tabsArea")};M.Mf=function(a,d,e){d[v](a);(new Mb(e,"parent",a)).sf()};M.Nf=function(a,d,e){var f=k;(f.postMessage?f:f[Ma].postMessage?f[Ma]:c)?this.lf(a,e):this.kf(a,e);d[v](a)};M.re=function(a,d,e){t(e,"gsc-adBlockNoHeight");d=this.Fb.Jg(this.tf(a,d,e));var f;if(f=k[Wa]?k[Wa][Oa]:c){f=Nb(f);var h=k[Wa]?k[Wa][Oa]:c;f=(h?h[ya]("Opera")!=0&&h[ya]("MSIE")!=-1:g)&&(f==6||f==7)}else f=g;f&&!Ob()?this.Mf(a,e,d):this.Nf(a,e,d)};
qa(M,function(a){if(a){a=a;this[w].onfocus&&this[w].onfocus();ka(this[w],a)}else a=this[w][xa];this.Fb=c;if(a[D]){this.gb=g;t(this.Aa,"gsc-resultsbox-visible");this.Hb();this.Wa=m[J].createGuidArg_();var d=this.ua;if(d&&this.Jf&&this.Z==m[H].b.ra)d=g;var e=this.Qf();if(e==o&&!this.Qa&&!this.mb)d=g;if(d){this.mg();d="w"+this.Ga;if(this.Ca)d=d+"n"+this.xa;if(this.mb){d="w"+this.Ga;d=m[J][Fa]+"/GafsAds?q="+i(a)+"&hl="+i(m[H][K])+"&ad="+i(d)+"&source="+this.d[0].f.wb+"&"+this.Wa}else d="http://www.google.com/"+
(e?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+i(a)+"&hl="+i(m[H][K])+"&ad="+i(d)+"&js=uds&"+this.Wa;if(e)d+="&cx="+e;if(this.Qa)d+="&client="+i(this.Qa);if(this.Sd)d+="&channel="+i(this.Sd);if(this.ac)d+="&adtest=on";if(this.Td)d+="&ip="+i(this.Td);if(this.Ud)d+="&adsafe="+i(this.Ud);if(this.Wd)d+="&useragent="+i(this.Wd);if(this.mb){ma(this.Aa[G],"hidden");this.Fb=new m[H].cb;this.ob();r(this.O,"");r(this.U,"");if(fb()||gb())d+="&nocache="+_json_cache_defeater_++;d+="&referer="+k[Pa].host;
if(this.Ga>0){if(this.Ig)d=d[z](/&ad=[^&]*/,"&ad=n1w0");var f=this.je();e=d.substring(0,2E3);e=e[z](/%\w?$/,"");f.src=e;this.re(f,g,this.O)}if(this.Ca&&this.xa>0){e=d[z](/&ad=[^&]*/,"&ad="+("n"+this.xa));d=this.je();e=e.substring(0,2E3);e=e[z](/%\w?$/,"");d.src=e;this.re(d,b,this.U)}}else{var h=this;k.google_afs_request_done=function(l){h.Wf(l)};eb(d)}}for(e=0;e<this.d[D];e++){if(!this.d[e].pb){$(this.d[e].i,"gsc-resultsbox-invisible");Z(this.d[e].i,"gsc-resultsbox-visible")}this.Bc&&this.Bc(this,
this.d[e].f,a);if(this.d[e].f.pa)this.d[e].f.pa=c;this.d[e].f.Wa=this.Wa;this.d[e].f[L](a)}this.Fb&&this.Fb.start(2E3)}});O(m[H].b[E],"execute",m[H].b[E][L]);M=m[H].b[E];M.tf=function(a,d,e){var f=this;return function(h){m[J][Ea]("afsq","1");var l=h&&h>40;if(d)f.uc=l?1:0;else f.vc=l?1:0;f.Sf(a,h,l);if(f.ca)if(f.vb(f.p[f.J].Cc))l=g;l?f.fe():yb(e,"gsc-adBlockInvisible")}};
M.kf=function(a,d){var e=function(){var f=0;try{var h=a.contentWindow;if(h.frames&&h.frames[D])f=h.frames[0].name}catch(l){}d(f)};if(fb())ha(a,function(){if(a[Aa]=="loaded"||a[Aa]=="complete"){ha(a,c);e()}});else ga(a,function(){ga(a,c);e()})};
M.lf=function(a,d){var e=function(f){f=f?f:k[Za];if(f.source==a.contentWindow){if(k.detachEvent)k.detachEvent("onmessage",e);else k.removeEventListener&&k.removeEventListener("message",e,g);d(f.data)}};if(k.attachEvent)k.attachEvent("onmessage",e);else k.addEventListener&&k.addEventListener("message",e,g)};
M.je=function(){var a=p[A]("iframe");a.name="google_afs_ads_frame";u(a,0);a.frameBorder=0;a.marginWidth=0;a.marginHeight=0;a.vspace=0;a.hspace=0;a[C]("allowTransparency",b);a.scrolling="no";ma(a[G],"hidden");return a};M.Sf=function(a,d,e){ja(a,"100%");if(e){u(a[G],d+"px");ma(a[G],"visible")}else{u(a[G],"0px");ma(a[G],"hidden")}};M.Qf=function(){for(var a=0;a<this.d[D];a++){var d=this.d[a].f;if(d.w=="web")if(d.D!=m[H].g.Y)if(d.D==m[H].g.ib)return d.l}return c};
M.Wf=function(a){k.google_afs_request_done=c;if(this.O){m[J][Ea]("afsq","1");r(this.O,"");r(this.U,"");this.vc=this.uc=0;if(!a||a[D]<1)this.ob();else{if(!this.ca)for(var d=0;d<this.d[D];d++){var e=this.d[d].f;if(this.vb(e)){this.ob();return}}t(this.O,"gsc-adBlock");e=g;var f=p[A]("h2");d="";if(this.ac)d="*DEBUG* ";d+=P["ads-by-google"];r(f,d);T(this.O,f);var h=a[D];for(d=0;d<h;d++){var l=a[d];if(l[Da]=="text/wide"){this.vc++;var n=V("gsc-ad"),y=Y(l.url,l.line1,m[H].a.db);T(n,y);y=p[A]("cite");r(y,
l.visible_url);T(n,y);y=mb();r(y,l.line2);T(n,y);T(this.O,n)}else if(this.Ca){this.uc++;if(!e){e=b;Z(this.da,"gsc-thinWrapper");T(this.U,f[Ca](b));t(this.U,"gsc-adBlockVertical")}n=V("gsc-ad");y=Y(l.url,l.line1,m[H].a.db);T(n,y);y=mb();r(y,l.line2+"<br/>"+l.line3);T(n,y);y=p[A]("cite");r(y,l.visible_url);T(n,y);T(this.U,n)}}this.Ca&&!e&&zb(this.da,"gsc-thinWrapper");if(this.ca){e=this.p[this.J].Cc;this.vb(e)&&this.ob()}this.ub&&this.Be&&this.ub(this,"ads")}}};
M.Yf=function(){var a=this[w][xa];if(a&&a!=""){this.Xa&&k[sa](this.Xa);this.Xa=k[La](R(this,m[H].b[E][L],[c]),this.Qb)}};M.Zf=function(){this.Xa&&k[sa](this.Xa);this.Xa=k[La](R(this,m[H].b[E][L],[c]),this.Qb)};M.mg=function(){var a,d;switch(this.Vd){case m[H].a.Ma:a=3;d=5;break;case m[H].a.la:a=2;d=4;break;case m[H].a.X:default:a=1;d=2;break}if(this.Ga==o)this.Ga=a;if(this.xa==o)this.xa=d};
M.S=function(a){switch(a){case m[H].a.la:case m[H].a.Ma:this.Mb=m[H].a.la;break;default:case m[H].a.X:this.Mb=m[H].a.X;break}for(var d=0;d<this.d[D];d++)this.d[d].f.S(a);this.Vd=a};O(m[H].b[E],"setResultSetSize",m[H].b[E].S);m[H].b[E].xb=function(a){this.Fa=a;for(var d=0;d<this.d[D];d++)this.d[d].f.xb(a)};O(m[H].b[E],"setLinkTarget",m[H].b[E].xb);m[H].b[E].yb=function(a){for(var d=0;d<this.d[D];d++)this.d[d].t.yb(a)};O(m[H].b[E],"setNoResultsString",m[H].b[E].yb);M=m[H].b[E];
M.bg=function(a){a.kc?this.Ia(a,g):this.Ia(a,b)};M.Ia=function(a,d,e){if(d){$(a.Ja,"gsc-twiddle-closed");Z(a.Ja,"gsc-twiddle-opened");a.kc=b;pa(a.Q[G],"block")}else{$(a.Ja,"gsc-twiddle-opened");Z(a.Ja,"gsc-twiddle-closed");a.kc=g;pa(a.Q[G],"none");r(a.nb,e?"(0)":"("+a.f.results[D]+")")}};M.Xf=function(a){this.Ab(a,g,b);return g};M.ag=function(a){if(a.f.Ta)a.fc?this.Ab(a,g,b):this.Ab(a,b,b)};
M.Ab=function(a,d,e){if(d){if(a.P&&a.f.fa){Z(a.P,"gsc-twiddle-opened");$(a.P,"gsc-twiddle-closed");r(a.P,P[Ra]);a.fc=b;pa(a.va[G],"block");a.f.fa(a.Ua,b)}}else if(a.P&&a.f.fa){$(a.P,"gsc-twiddle-opened");Z(a.P,"gsc-twiddle-closed");r(a.P,P.blank);a.fc=g;a.f.fa(a.Ua,g);pa(a.va[G],"none");e&&this[L]()}};M.$f=function(a,d){if(this.Lb){d.f.Lf();this.Lb(a)}};M.mf=function(){this.gb=b};O(m[H].b[E],"cancelSearch",m[H].b[E].mf);
m[H].b[E].dc=function(){ka(this[w],"");this[w].onblur&&this[w].onblur();t(this.Aa,"gsc-resultsbox-invisible");this.ca&&yb(this.ca,"gsc-tabsAreaInvisible");this.O&&yb(this.O,"gsc-adBlockInvisible");if(this.U){t(this.U,"gsc-adBlockInvisible");$(this.da,"gsc-thinWrapper")}for(var a=0;a<this.d[D];a++){if(!this.d[a].pb){$(this.d[a].i,"gsc-resultsbox-visible");Z(this.d[a].i,"gsc-resultsbox-invisible")}var d=this.d[a];ib(d.Q);d.v=c;this.Ia(d,g,b);this.Ab(d,g,g)}};O(m[H].b[E],"clearAllResults",m[H].b[E].dc);
m[H].b[E].W=function(a){if(this.mb&&a==this.d[this.J])ma(this.Aa[G],"visible");var d,e,f=g,h;if(!this.gb){ib(a.Q);a.v=c;this.Ia(a,g,b);this.Ab(a,g,g);a.Dc(m[H].z.Xb);var l=a.f.context,n=this.ca&&l;if(this.kb&&!this.Rd){if(n){h=l[Ha];for(e=0;e<this.p[D];e++){d=this.p[e];if(d.w==a.f.w){var y=a.f;h&&!a.f.bb&&jb(d.V,kb(h));break}}}this.Rd=b;this.Hb()}if((d=a.f.promotions)&&d[D]>0)for(e=0;e<d[D];e++){var B=d[e];B.html||a.f.be(B);if(B.html){h=V(a.f.nc());Z(h,"gsc-result");var W=B.html[Ca](b);T(h,W);T(a.Q,
h)}}B=a.f.results;if(a.f.lb&&a.f.completionStatus>=400){B=[];B[ra](a.f.Af())}else if(B[D]==0&&a.t.rb&&a.f.completionStatus==200){B=[];B[ra](a.f.Bf(a.t.rb))}for(e=0;e<B[D];e++){d=B[e];d.html||a.f.C(d);if(d.html){f=b;h=V(a.f.nc());Z(h,"gsc-result");a.f.Cb&&wb(h,"gsc-result-"+a.f.Cb);W=d.html[Ca](b);if(d.GsearchResultClass==m[H].c.B){if(a.t.M)if(a.t.M[x]!=a.f.M[x]||a.t.M[Xa]!=a.f.M[Xa])for(var S=W.getElementsByTagName("img"),wa=0;wa<S[D];wa++)m[H].a.$a(d.tbWidth,d.tbHeight,a.t.M,S[wa],b)}else if(d.GsearchResultClass==
m[H].r.B)if(a.t.Tb){S=W.getElementsByTagName("img");for(wa=0;wa<S[D];wa++)m[H].a.$a(d.tbWidth,d.tbHeight,a.t.Tb,S[wa])}T(h,W);if(this.Lb){W=this.sc;S=U("","gsc-keeper");r(S,W);T(h,S);oa(S,R(this,m[H].b[E].$f,[d,a]))}if(e>=a.f.we){if(!a.v){a.v=V("gsc-expansionArea");T(a.Q,a.v);if(a.t.$==m[H].b.Da)pa(a.v[G],"none")}T(a.v,h)}else T(a.Q,h)}}if(!a.v&&a.f[F]){a.v=V("gsc-expansionArea");T(a.Q,a.v)}if(a.v&&a.f.u&&a.f.gwsUrl){h=Y(a.f.gwsUrl,P["more-results"]+"&nbsp;&raquo;",a.f.s(),"gsc-trailing-more-results");
if(a.f[F]){e=V("gsc-cursor-box");d=this.vf(a);e[v](d);a.f[F].currentPageIndex==a.f[F].pages[D]-1&&e[v](h);T(a.v,e)}else T(a.v,h)}if(f){r(a.nb,"("+a.f.results[D]+")");a.t.$==m[H].b.Da||a.t.$==m[H].b.La?this.Ia(a,b):this.Ia(a,g);(e=a.f.le())&&T(a.Q,e)}else{r(a.nb,"(0)");r(a.Q,"");this.Ia(a,g)}a.t.$=a.t.xe;this.ub&&this.ub(this,a.f);if(this.kb&&n&&!this.ff&&l.facets){a=this[w][xa];l=l.facets;for(e=0;e<l[D];e++){n=l[e];f=new m[H].g;y&&y.l&&f.qa(y.l,n.label);f.Bb(n.anchor);this.Oa(f);f.S(y.za);f[L](a)}for(e=
0;e<this.d[D];e++)if(!this.p[e]){this.de(e);this.ce(e);Z(this.p[e].V,"gsc-tabHeader");Z(this.p[e].ga,"gsc-tabData");Z(this.p[e].V,"gsc-tabhInactive");Z(this.p[e].ga,"gsc-tabdInactive")}this.ff=b}}};O(m[H].b[E],"onSearchComplete",m[H].b[E].W);m[H].b[E].vf=function(a){for(var d=V("gsc-cursor"),e=a.f[F],f=0;f<e.pages[D];f++){var h="gsc-cursor-page";if(f==e.currentPageIndex)h+=" gsc-cursor-current-page";h=U(e.pages[f].label,h);oa(h,R(this,m[H].b[E].eg,[a,f]));d[v](h)}return d};
m[H].b.Bd={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
m[H].b.se=function(a,d){if(gb())alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var e=b;if(d)e=d;if(e)for(d=0;d<a.childNodes[D];d++)m[H].b.se(a.childNodes[d],b);if(a.nodeType==1){var f,h;d=e=g;if(k[Qa]){f=k[Qa](a,c);e=h=b}else if(a[Sa]){f=a[Sa];h=g;e=b}if(e){for(var l in f)if(m[H].b.Bd[l]){e=m[H].b.Bd[l];var n=f[l];if(l=="display"&&n=="none"){r(a,"");d=b}if(f[l]!="")h?a[G].setProperty(e,n):a[G][C](e,n)}if(d)if(!h)a.outerHTML='<div style="display:none"/>'}}}};
O(m[H].b,"inlineCurrentStyle",m[H].b.se);m[H].b[E].Df=function(a){a=a?a:this.i;var d=c;if(k[Qa])d=k[Qa](a,c);else if(a[Sa])d=a[Sa];else if(p.defaultView[Qa])d=p.defaultView[Qa](a,c);return d?ca(d[x],10):300};m[H].b[E].zb=function(a,d){this.ub=hb(a,d)};O(m[H].b[E],"setSearchCompleteCallback",m[H].b[E].zb);m[H].b[E].vg=function(a,d){this.Bc=hb(a,d)};O(m[H].b[E],"setSearchStartingCallback",m[H].b[E].vg);
m[H].b[E].wc=function(a,d){a.Dc(d);var e=g;switch(d){default:case m[H].z.Zb:if(a.v)pa(a.v[G],"none");break;case m[H].z.Yb:if(a.v)pa(a.v[G],"block");if(a.f.za!=m[H].a.X)e=b;a.f.S(m[H].a.X);break;case m[H].z.Cd:if(a.v)pa(a.v[G],"block");if(a.f.za!=m[H].a.la)e=b;a.f.S(m[H].a.la);break}if(e){d=this[w][xa];if(d[D]){this.gb=g;t(this.Aa,"gsc-resultsbox-visible");this.Hb();if(!a.pb){$(a.i,"gsc-resultsbox-invisible");Z(a.i,"gsc-resultsbox-visible")}a.t.$=m[H].b.La;a.f[L](d)}}};
m[H].b[E].eg=function(a,d){this.gb=g;t(this.Aa,"gsc-resultsbox-visible");this.Hb();if(!a.pb){$(a.i,"gsc-resultsbox-invisible");Z(a.i,"gsc-resultsbox-visible")}a.t.$=m[H].b.La;a.f.ne(d)};
m[H].L=function(a,d,e){var f=tb("gsc-search-box");f.acceptCharset="utf-8";var h=c,l=P["search-uc"],n=P[H];if(e){if(e.buttonText)n=l=e.buttonText;if(e.clickableBrandingUrl){h="http://www.google.com";if(typeof e.clickableBrandingUrl=="string"&&e.clickableBrandingUrl[za](/^http:\/\/[a-z]*\.google\.com/))h=e.clickableBrandingUrl;h=rb(h,c,"_BLANK");t(h,"gsc-branding-clickable")}}this.Nb=ub(l,"gsc-search-button");s(this.Nb,n);if(a){e="gsc-branding-img";this.ec=U(P.blank,"gsc-clear-button");s(this.ec,P["clear-results"])}else e=
"gsc-branding-img-noclear";ia(this,vb(c,"gsc-input",c));this[w].name="search";s(this[w],n);n=nb(c,c,"gsc-search-box");T(f,n);n=ob(n,0);this.te=X(n,"gsc-input");l=X(n,"gsc-search-button");if(a){a=X(n,"gsc-clear-button");T(a,this.ec)}T(this.te,this[w]);T(l,this.Nb);a=nb(c,c,"gsc-branding");T(f,a);n=ob(a,0);this.userDefinedCell=X(n,"gsc-branding-user-defined");a=X(n,"gsc-branding-text");n=X(n,e);l=U(P["powered-by"],"gsc-branding-text");var y=m[J][Fa]+"/css/small-logo.png";e=e;if(fb()){e=V(e);e[G].filter=
'progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+y+'")';ja(e[G],"51px");u(e[G],"15px")}else e=qb(y,c,c,e);e=e;T(a,l);if(h){T(h,e);T(n,h)}else T(n,e);this.Ae=f;ib(d);T(d,this.Ae)};N("google.search.SearchForm",m[H].L);m[H].L[E].Ge=function(a,d){this.Ke=R(this,this.Bg,[this]);this.Ob=R(a,d,[this]);this.Ae.onsubmit=this.Ke;oa(this.Nb,this.Ke)};O(m[H].L[E],"setOnSubmitCallback",m[H].L[E].Ge);m[H].L[E].Fe=function(a,d){oa(this.ec,R(a,d,[this]))};O(m[H].L[E],"setOnClearCallback",m[H].L[E].Fe);
m[H].L[E].Bg=function(){var a=this.te.offsetWidth,d=this[w][xa];this.Ob&&this.Ob();if(fb()){var e=this,f;f=d[D]*8>=a?a-6:"99%";k[La](function(){ja(e[w][G],f)},1)}return g};qa(m[H].L[E],function(a){if(a)ka(this[w],a);this.Ob&&this.Ob()});O(m[H].L[E],"execute",m[H].L[E][L]);
m[H].L[E].Kf=function(){var a=this[w],d=function(){if(a[xa]=="")a[G].background="#FFFFFF url(http://www.google.com/coop/intl/"+m[H][K]+"/images/google_custom_search_watermark.gif) left no-repeat"};a.onblur=d;a.onfocus=function(){a[G].background="#FFFFFF"};d()};m[H].cb=function(){this.xc=0;this.ie=g;this.sb=[]};m[H].cb[E].Jg=function(a){this.xc++;var d=this;return function(){for(var e=[],f=0;f<arguments[D];++f)e[ra](arguments[f]);if(d.ie)this.ge(a,e);else{d.sb[ra]([a,e]);d.xc--;d.xc==0&&d.he()}}};
m[H].cb[E].he=function(){for(var a=0;a<this.sb[D];a++)this.ge(this.sb[a][0],this.sb[a][1]);this.sb=[];this.ie=b};m[H].cb[E].ge=function(a,d){k[La](function(){a[Va](c,d)},0)};m[H].cb[E].start=function(a){k[La](R(this,this.he,[]),a)};m[H].j=function(a,d){m[H].b[I](this);this.kb=b;this.S(m[H].a.la);this.jb("",{iframes:b});this.hb=new m[H].g;if(a==o){a={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+k[Pa]};this.Kg=b}this.hb.qa(a);this.hb.Pb=P.cse;d&&d[m[H].a.Na]&&this.hb.R(m[H].a.Na,d[m[H].a.Na]);this.Oa(this.hb);this.yb(m[H].b.qd);this.Fg=(new Date)[Ga]()};N("google.search.CustomSearchControl",m[H].j);$a(m[H].j,m[H].b);
m[H].j[E].Ib=function(a,d){(d=d)||(d=new m[H].T);d.De(m[H].b.Ka);if(this.Kg&&this.d[D]==1)this.Cg=b;m[H].b[E].Ib[I](this,a,d);t(this.i,"gsc-control-cse")};O(m[H].j[E],"draw",m[H].j[E].Ib);
qa(m[H].j[E],function(a){var d=this.i.offsetWidth;$(this.da,"gsc-thinWrapper");if(d<m[H].j.Xe)this.ua=g;else if(d<m[H].j.Ze)this.jb(this.Qa,{useNarrowTopAd:b,includeVerticalAds:g});else{d={useNarrowTopAd:g,includeVerticalAds:d>m[H].j.Ye};if(this.ve)d.numTopAds=m[H].j.$e;this.jb(this.Qa,d)}if((new Date)[Ga]()-this.Fg<m[H].j.Le&&this.ua){d=fa(k[Pa].href)[z](/\+/g," ");var e=fa(a)[z](/\+/g," ");this.ua=d[ya](e)!=-1}m[H].b[E][L][I](this,a)});O(m[H].j[E],"execute",m[H].j[E][L]);m[H].j[E].Bb=function(a){this.hb.Bb(a)};
O(m[H].j[E],"setUserDefinedLabel",m[H].j[E].Bb);m[H].j[E].Oa=function(a,d){m[H].b[E].Oa[I](this,a,d);a.wb="gcsc"};O(m[H].j[E],"addSearcher",m[H].j[E].Oa);m[H].j[E].xf=function(){m[H].b[E].jb("",{numTopAds:0,numSideAds:0});this.Qa=c;this.Be=g};O(m[H].j[E],"disableAds",m[H].j[E].xf);m[H].j[E].pg=function(){this.ve=b};O(m[H].j[E],"setMoreAds",m[H].j[E].pg);m[H].j.Me="";O(m[H].j,"AUTO_PUBID",m[H].j.Me);m[H].j.Xe=250;m[H].j.Ze=500;m[H].j.Ye=800;m[H].j.Le=500;m[H].j[E].ve=g;m[H].j.$e=4;m[H].r=function(){m[H].a[I](this);this.w="video";this.Ba="/GvideoSearch";this.na="http://video.google.com/videosearch";this.N=g;this.Ta=b;this.fa=hb(this,this.oa);this.Sa="gsc-videoConfig";this.o=c};N("google.search.VideoSearch",m[H].r);$a(m[H].r,m[H].a);m[H].r.B="GvideoSearch";O(m[H].r,"RESULT_CLASS",m[H].r.B);m[H].r.n=[];m[H].r.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].r.n[l];m[H].r.n[l]=c;a.W(d,e,f,h)};O(m[H].r,"RawCompletion",m[H].r.I);
m[H].r[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].r.n,this):e;d=this.ya(d==c?"google.search.VideoSearch.RawCompletion":d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;a="&q="+i(a);if(this.N)a+="&scoring=d";d+=a;this.u=a;if(f&&f!=0)this.u=this.u+"&start="+f}return d};
m[H].r[E].C=function(a){a.html&&delete a.html;var d=V(this.ia());Z(d,"gs-result");var e=V("gs-image-box"),f=V("gs-text-box"),h=nb(),l=ob(h,0),n=X(l,"gs-image-box");l=X(l,"gs-text-box");T(n,e);T(l,f);T(d,h);h=m[H].a.$a(a.tbWidth,a.tbHeight,this.M);h=qb(a.tbUrl,h[x],h[Xa],"gs-image");n=rb(a.url,c,this.s(),"gs-image");t(n,"gs-image");T(n,h);T(e,n);e=Y(a.url,a[Ha],this.s(),"gs-title");T(f,e);e=U(a[va],"gs-snippet");if(fb())u(e[G],"2.6em");T(f,e);e=U(this.Va(new Date(a.published)),"gs-publishedDate");
T(f,e);e=Y("http://"+a.publisher,a.publisher,this.s(),"gs-publisher");T(f,e);a.html=d;this.ta(a.html)};O(m[H].r[E],"createResultHtml",m[H].r[E].C);
m[H].r.wf=function(a,d){var e=c;if(a.playUrl&&a.playUrl!=""){e=a.playUrl;var f="gsc-video-player";if(d)f=d;if(bb("opera")){var h=p[A]("object");t(h,f);h[C]("type","application/x-shockwave-flash");h[C]("data",e)}else{h=p[A]("embed");t(h,f);h[C]("type","application/x-shockwave-flash");h[C]("src",e);if(a.videoType)a.videoType=="Google"?h[C]("bgcolor","#000000"):h[C]("wmode","transparent");else h[C]("bgcolor","#000000")}e=V(d);e[v](h)}return e};O(m[H].r,"createPlayer",m[H].r.wf);
m[H].r[E].K=function(a){this.N=a==m[H].a.ma?b:g};O(m[H].r[E],"setResultOrder",m[H].r[E].K);m[H].r[E].oa=function(a,d){if(d){if(this.o==c){d=V("gsc-configSetting");this.o=xb(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.o);T(d,U(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=V("gsc-configSettingSubmit");T(e,ub(P[Ra],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else na(this.o,this.N);this.o[Ba]()}else if(this.o)this.o[Ka]?this.K(m[H].a.ma):this.K(m[H].a.eb)};m[H].g=function(){m[H].a[I](this);this.w="web";this.Ba="/GwebSearch";this.na="http://www.google.com/search";this.l=c;this.D=m[H].g.Y;this.F=this.Ha=this.wa=this.jc=this.Ea=c};N("google.search.WebSearch",m[H].g);$a(m[H].g,m[H].a);m[H].g.B="GwebSearch";O(m[H].g,"RESULT_CLASS",m[H].g.B);m[H].g.ib="cx";O(m[H].g,"cxRestriction_CX",m[H].g.ib);m[H].g.Gb="cref";O(m[H].g,"cxRestriction_CREF",m[H].g.Gb);m[H].g.Y="none";O(m[H].g,"cxRestriction_NONE",m[H].g.Y);m[H].g.n=[];
m[H].g.I=function(a,d,e,f,h){var l=0;if(a)l=ca(a,10);a=m[H].g.n[l];m[H].g.n[l]=c;a.W(d,e,f,h)};O(m[H].g,"RawCompletion",m[H].g.I);m[H].g[E].Hg=function(a){return a[z](/\s+$/,"")[z](/^\s+/,"")};m[H].g[E].Vf=function(a){a=this.Hg(a);return a[z](/\s+/g,"_")[Ya]()};
m[H].g[E].ha=function(a,d,e,f){e=e==c?m[H].a.ka(m[H].g.n,this):e;if(this.D==m[H].g.Y&&this.Jh==m[H].a.Ma)throw createException("The resultset size google.search.Search.FILTERED_CSE_RESULTSET can  only be used for querying filtered Custom Search Engines.");d=this.ya(d==c?"google.search.WebSearch.RawCompletion":d,e,f);if(a){a=a;if(this.H)a=a+" "+this.H;if(this.l&&this.D!=m[H].g.Y&&this.jc){e=this.jc;var h=a;if(this.Ea!=c)h=a+" more:"+this.Ea;e=e[z](/__HL__/,m[H][K]);this.wa=e=e[z](/__QUERY__/,i(h))}if(this.l&&
this.D==m[H].g.Y)a=a+" site:"+this.l;e="";if(this.l&&this.D!=m[H].g.Y){if(this.D==m[H].g.ib)e=e+"&cx="+this.l;else if(this.D==m[H].g.Gb)e=e+"&cref="+i(this.l);if(this.Ea!=c)a=a+" more:"+this.Ea}e=e+"&q="+i(a);if(this.Ha)e=e+"&safe="+this.Ha;if(this.F)e+=this.F;d+=e;this.u=e;if(f&&f!=0)this.u=this.u+"&start="+f}if(k.google[J].GoogleLocale)d+="&gl="+i(k.google[J].GoogleLocale);return d};
m[H].g[E].be=function(a){a.html&&delete a.html;var d=V("gs-promotion");Z(d,"gs-result");var e=sb(a.url,a[Ha],this.s(),"gs-title");T(d,e);e=nb(0,0);var f=ob(e,0),h;T(d,e);if(a.image){e=a.image;e=qb(e.url,e[x],e[Xa],"gs-promotion-image");h=pb("gs-promotion-image-td");T(h,e);T(f,h)}if(a.bodyLines){h=pb();var l=V();T(f,h);T(h,l);f=a.bodyLines;for(h=0;h<f[D];h++){e=f[h];var n=e[Ha],y=e.url,B=e.visibleUrl;e=V("gs-snippet");if(y&&B){y=rb(y,B,this.s(),"gs-title");T(e,y)}n&&T(e,kb(n));T(l,e)}}e=lb(a.visibleUrl,
"gs-visibleUrl");T(l,e);Z(e,"gs-visibleUrl-short");a.html=d};O(m[H].g[E],"createPromotionHtml",m[H].g[E].be);m[H].g[E].ee=function(a,d,e,f){var h=V("gs-image-box gs-web-image-box");if(e==o)e=100;a=qb(a,e,f,"gs-image");d=rb(d,c,this.s());t(d,"gs-image");T(d,a);T(h,d);return h};m[H].g[E].Xd=function(a,d){if(d.url){var e=sb(d.url,d.label,this.s(),"gs-action");d["class"]&&wb(e,d["class"]);a.actionHtml||(a.actionHtml=V("gs-actions"));T(a.actionHtml,e)}};
m[H].g[E].C=function(a){a.html&&delete a.html;a.thumbnailHtml&&delete a.thumbnailHtml;a.actionHtml&&delete a.actionHtml;var d=V(this.ia());Z(d,"gs-result");if(a.richSnippet){var e=a.richSnippet;if(e.thumbnail&&e.thumbnail.src)a.thumbnailHtml=this.ee(e.thumbnail.src,a.unescapedUrl,e.thumbnail[x],e.thumbnail[Xa]);else if(e[Ma]&&e[Ma].thumbnailUrl)a.thumbnailHtml=this.ee(e[Ma].thumbnailUrl,a.unescapedUrl);if(e[Ua])if(e[Ua][D]&&e[Ua][0])for(var f=0;f<e[Ua][D];f++)this.Xd(a,e[Ua][f]);else this.Xd(a,e[Ua]);
a.thumbnailHtml&&T(d,a.thumbnailHtml[Ca](b))}e=Y(a.unescapedUrl,a[Ha],this.s(),"gs-title");T(d,e);e=U(a[va],"gs-snippet");T(d,e);e=U(a.visibleUrl,"gs-visibleUrl");T(d,e);Z(e,"gs-visibleUrl-short");e=a.unescapedUrl[ya](a.visibleUrl);f=a.visibleUrl;if(e!=-1&&e!=0)f=a.unescapedUrl.substring(e);e=U(f,"gs-visibleUrl");Z(e,"gs-visibleUrl-long");T(d,e);a.actionHtml&&T(d,a.actionHtml[Ca](b));a.html=d;this.ta(a.html)};O(m[H].g[E],"createResultHtml",m[H].g[E].C);
m[H].g[E].qa=function(a,d,e){this.lb=this.wa=c;var f=g;if(a==c||typeof a=="string"&&a==""){f=g;this.l=c;this.D=m[H].g.Y;this.lb=this.Ea=c}else if(typeof a=="string")if(f=a[za](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/)){this.l=a;this.D=m[H].g.ib}else{this.l=a;this.D=m[H].g.Y}else if(a.siteUrl){f=g;this.l=a.siteUrl}else if(a.cseId){f=b;this.l=a.cseId;this.D=m[H].g.ib}else if(a.crefUrl){f=b;this.l=a.crefUrl;this.D=m[H].g.Gb;this.lb=P["linked-cse-error-results"]}else{f=g;this.l=c;this.D=m[H].g.Y;this.Ea=
c}if(f){if(d)this.Ea=this.Vf(d);if(e)if(e[za](/__HL__/)&&e[za](/__QUERY__/))this.jc=e;if(this.D==m[H].g.Gb)if(!this.l[za](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/))(new Image).src="http://www.google.com/cse/tools/ping?cref="+i(this.l)+"&nocache="+Number(new Date)}};O(m[H].g[E],"setSiteRestriction",m[H].g[E].qa);
m[H].g[E].R=function(a,d){if(a==m[H].a.Ub)this.Ha=d?d==m[H].a.Wb||d==m[H].a.Vb||d==m[H].a.Ad?d:c:c;if(a==m[H].a.Na)if(d)for(var e in d){a=d[e];if(e=="lr"||e=="usg"||e=="filter"||e=="gl"||e=="richsnippet"){if(this.F==c)this.F="&";else this.F+="&";this.F+=e+"="+i(a)}}else this.F=c};O(m[H].g[E],"setRestriction",m[H].g[E].R);m[H].g[E].S=function(a){if(m[H].a.Ma==a)this.za=m[H].a.Ma;else m[H].a[E].S[I](this,a)};O(m[H].g[E],"setResultSetSize",m[H].g[E].S);if(!m[H].NoOldNames){j("GwebSearch",m[H].g);j("GbookSearch",m[H].k);j("GblogSearch",m[H].q);j("GvideoSearch",m[H].r);j("GnewsSearch",m[H].m);j("GlocalSearch",m[H].e);j("GimageSearch",m[H].c);j("GpatentSearch",m[H].h);j("GSearch",m[H].a);j("GSearchControl",m[H].b);j("GSearchForm",m[H].L);j("GsearcherOptions",m[H].A);j("GdrawOptions",m[H].T)};var Mb=function(a,d,e){this.Tf=a;this.Ac=d;this.Ya=g;this.pe=e||c;this.console=k[Ta]||{log:function(){}};if(!this.pe&&this.Ac=="parent")this[Ta].log("You forgot to pass an iframe.");else{if(!k.UDS_IEXDC_SETUP_COMPLETE)try{k.execScript("Class UDS_GCXPC____NIXVBS_wrapper\n Private UDS_M_TRANSPORT\nPublic Sub UDS_SET_TRANSPORT(transport)\nIf isEmpty(UDS_M_TRANSPORT) Then\nSet UDS_M_TRANSPORT = transport\nEnd If\nEnd Sub\nPublic Sub UDS_SEND_MESSAGE_(payload)\n Call UDS_M_TRANSPORT.UDS_GCXPC____NIXJS_handle_message(payload)\nEnd Sub\nPublic Sub UDS_CREATE_CHANNEL(channel)\n Call UDS_M_TRANSPORT.UDS_GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub UDS_GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function UDS_GCXPC____NIXVBS_get_wrapper(transport)\nDim wrap\nSet wrap = New UDS_GCXPC____NIXVBS_wrapper\nwrap.UDS_SET_TRANSPORT transport\nSet UDS_GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript");k.UDS_IEXDC_SETUP_COMPLETE=b}catch(f){}this.UDS_GCXPC____NIXJS_handle_message=this.If;this.UDS_GCXPC____NIXJS_create_channel=this.uf}},Ob=function(){var a=k[Wa]?k[Wa][Oa]:c;if(a)return/trident\/\d/i.test(a)&&Nb(a)==7;return g},Pb=/MSIE\s+([^\);]+)(\)|;)/,Nb=function(a){return(a=Pb.exec(a))?a[1]:""};M=Mb[E];M.If=function(a){this.Ac=="parent"&&a=="connected"?this.He():this.Tf(a)};M.uf=function(a){this.oe=a};
M.Zd=function(a){return function(){if(!a.Ya){var d=a.pe;try{d.contentWindow.opener=k.UDS_GCXPC____NIXVBS_get_wrapper(a);a.Ya=b}catch(e){this[Ta].log("Exception caught while attempting Google IE XDC: "+e.message)}a.Ya||k[La](a.Zd(a),100)}}};M.Yd=function(a){return function(){if(!a.Ya){try{var d=k.opener;if(d&&"UDS_GCXPC____NIXVBS_container"in d){a.oe=d;a.oe.UDS_CREATE_CHANNEL(k.UDS_GCXPC____NIXVBS_get_wrapper(a));a.Ya=b;a.send("connected");a.He()}}catch(e){return}a.Ya||k[La](a.Yd(a),100)}}};
M.send=function(){this[Ta].log("Cross-domain channel has been modified.")};M.sf=function(a){this.He=a||function(){};this.Ac=="parent"?this.Zd(this)():this.Yd(this)()};
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['search']) {(function() {var scripts = google.loader.eval.scripts['search'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.search(scripts[i]);}})();google.loader.eval.scripts['search'] = null;}})();