
all:
	gcc  -I/home/leandro/programa/libdebug  -o main   programa.c -L/home/leandro/programa/libdebug -lDebug

outro:
	gcc  -I/home/leandro/programa/libdebug  -L/home/leandro/programa/libdebug -lDebug   programa.c -o main
