#
# Makefile
#
# $Id: //poco/1.3/Net/samples/TimeServer/Makefile#1 $
#
# Makefile for Poco TimeServer
#

PROJECT_BASE=.
POCO_BASE=/usr/local/poco

include $(POCO_BASE)/build/rules/global

objects = TimeServer

target         = TimeServer
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
