var gfc_bm=osapi,gfc_cm="ceil";gfc_2[gfc_].share=gfc_Sc(24,function(){gfc_Xl();return gfc_d});gfc_7e[gfc_].ceil=gfc_Sc(20,function(){gfc_na(this,gfc_k[gfc_cm](this[gfc_p]));gfc_Ia(this,gfc_k[gfc_cm](this[gfc_L]));return this});gfc_2[gfc_].Ni=gfc_Sc(19,function(){var a=this.Id;if(a.valid){this.d=this.Mg(this.Id);this.Uh(a[gfc_Hb])}else{this.Id=gfc_c;this.render(a.actions,a[gfc_Hb],a.params)}this.Lg()});gfc_2[gfc_].Pf=gfc_Sc(14,function(){return this.Gb.pop()});
gfc_2[gfc_].qi=gfc_Sc(5,function(a,b,c){return a?c<b?[]:a[gfc_9a](gfc_k.min(b,a[gfc_n]),gfc_k.min(c,a[gfc_n])):[]});
var gfc_dm=function(a){return a=gfc_h.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ja();this.dr();var d=new gfc_Q;d.set("members",{action:this.wu,callback:this.qt});d.set("member-page",{action:this.vu,callback:this.pt});d.set("blocked-member-page",{action:this.pu,callback:this.lt});d.set("profile-friends-page",{action:this.Bu,callback:this.ut});d.set("sitesData",{action:this.Ju,callback:this.yt});d.set("viewerFriends",{action:this.Ou,callback:this.At});
d.set("profileData",{action:this.Au,callback:this.tt});d.set("blockUser",{action:this.ou,callback:this.kt});d.set("unblockUser",{action:this.Mu,callback:this.zt});d.set("profileFriends",{action:this.Cu,callback:this.vt});d.set("activityData",{action:this.Wf,callback:this.rd});d.set("sendFriendRequest",{action:this.Iu,callback:this.xt});d.set("sendFriendRequestResponse",{action:this.su,callback:this.im});d.set("deleteActivity",{action:this.Xf,callback:this.rd});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.Pu,callback:this.Ct});d.set("requestPromo",{action:this.Du,callback:this.wt});this.lb=gfc_c;this.$w=new gfc_4l("fc-members-options-menu",gfc_N(this.Ps,this),gfc_N(this.Os,this),gfc_N(this.Qs,this),0,gfc_h.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.Uv=gfc_d;this.Fa=10;this.Kf=15;this.jn=10;var e=gfc_Hg(gfc_vg()),f=gfc_em;this.Xb=3;this.oc=8;this.Im=gfc_c;this.ta=this.oc*this.Xb;this.slimTopCapHeight=19;this.tinyTopCapHeight=
8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=gfc_c;this.Pb=new gfc_0l;if(this.Ph()){a=(a=this.f(f.FACE_SIZE))?gfc_ea(a):32;a=a+6;this.Xb=gfc_k[gfc_eb]((e[gfc_p]-10)/a);e=340;e=this.f(f.HEIGHT);b=this.f(f.NUMBER_ROWS);f=27;if(b){this.oc=gfc_ea(b);e=this.oc*a;this.Im=e+f}else if(e){e=gfc_ea(e)-96;this.oc=gfc_k.max(2,gfc_k[gfc_eb](e/a));this.Im=this.oc*a+f}this.ta=this.oc*this.Xb}gfc_2[gfc_D](this,d)};gfc_7.inherits(gfc_2);
gfc_ya(gfc_7[gfc_],function(){gfc_yl("start");var a=gfc_e[gfc_o][gfc_Kb](),b=gfc_ia();if(a=b.profileId||a.profileId){b={};b[gfc_i[gfc_u][gfc_J].ID]=a;a=new gfc_i[gfc_u](b);this.render(["profileData","profileFriends","activityData"],"profile",{person:a})}else{a=["members","viewerFriends"];this.isMessagingEnabled&&a[gfc_m]("requestAndProcessViewerNumWaitingMessages");this.isPromosEnabled&&!this.Mb()&&a[gfc_m]("requestPromo");this.render(a,"faces")}});gfc_7[gfc_].e={};
gfc_7[gfc_].Ja=function(){this.e.MSG_SITE_MEMBERS="Membros";this.e.MSG_BE_THE_FIRST="Seja o primeiro!";this.e.MSG_NO_SITE_MEMBERS="Ainda n\u00e3o h\u00e1 membros.";this.e.MSG_ALL_SITE_MEMBERS="Todos os membros";this.e.MSG_ALL_BLOCKED_MEMBERS="Todos os membros bloqueados";this.e.MSG_NO_BLOCKED_MEMBERS="Voc\u00ea n\u00e3o bloqueou nenhum membro";this.e.MSG_YOUR_FRIENDS="Seus amigos";this.e.MSG_ALL_YOUR_FRIENDS="Todos os seus amigos";this.e.MSG_JFJ="Participe e conecte-se com as pessoas!";this.e.MSG_MANAGE=
"Gerenciar membros";this.e.MSG_SETTINGS="Configura\u00e7\u00f5es";this.e.MSG_OPTIONS="Op\u00e7\u00f5es";this.e.MSG_INVITE="Convidar";this.e.MSG_MEMBERS_SHARE="Share this page";this.e.MSG_BACK="Voltar";this.e.MSG_BACK_TO_TOP="P\u00e1gina inicial";this.e.MSG_VIEW_MY_PROFILE="Visualizar meu perfil";this.e.MSG_ABOUT_ME="Sobre mim";this.e.MSG_MORE="Mais \u00bb";this.e.MSG_SHOW_BLOCKED="Mostrar membros bloqueados \u00bb";this.e.MSG_SHOW_ALL="\u00ab Mostrar todos os membros";this.e.MSG_INVITE_YOUR_FRIENDS=
"Convide seus amigos";this.e.MSG_LINK_IN_NETWORKS="Vincular suas redes sociais";this.e.MSG_ACTIVITIES="Atividades";this.e.MSG_ALL_ACTIVITIES="Mais atividades";this.e.MSG_DELETE_THIS="Excluir";this.e.MSG_SITES="Sites dos quais eu participo";this.e.MSG_ALL_SITES="Mais sites dos quais eu participo";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="Mais links";this.e.MSG_NO_ACTIVITIES="Nenhuma atividade a ser exibida";this.e.MSG_ADD_AS_FRIEND="Adicionar como amigo(a)";this.e.MSG_SEND_MESSAGE="Enviar mensagem";
this.e.MSG_BLOCK_USER="Bloquear este usu\u00e1rio";this.e.MSG_UNBLOCK_USER="Desbloquear este usu\u00e1rio";this.e.MSG_USER_IS_ADMIN="Administrador";this.e.MSG_JOIN="Participar deste site";this.e.MSG_OR="ou";this.e.MSG_SIGN_IN="Fazer login";this.e.MSG_SIGN_OUT="Sair";this.e.MSG_PREVIOUS="\u00ab Anterior";this.e.MSG_NEXT="Pr\u00f3xima \u00bb";this.e.MSG_NEWER="\u00ab Mais recentes";this.e.MSG_OLDER="Mais antigos \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Aceitar tudo";this.e.MSG_HELP_FRIENDREQUEST=
"Voc\u00ea e seus amigos ver\u00e3o uns aos outros em todos os sites do Google Friend Connect.";this.e.MSG_HELP_FRIENDINVITE="Depois de se tornarem amigos, voc\u00eas ver\u00e3o um ao outro em todos os sites do Google Friend Connect.";this.e.MSG_HELP_BLOCKMEMBER="Bloquear um visitante o remove da lista de membros e impede que ele interaja com outros visitantes no seu site";this.e.MSG_INVITATION="Convite:";this.e.MSG_SEND="Enviar";this.e.MSG_BLOCK="Bloquear";this.e.MSG_IGNORE="Ignorar";this.e.MSG_CANCEL=
"Cancelar";this.e.MSG_SITE_SETTINGS="Configura\u00e7\u00f5es do site";this.e.MSG_INVITE_FRIENDS="Convidar amigos";this.e.MSG_ABOUT_FC="Sobre o Google Friend Connect";this.e.MSG_ALREADY_MEMBER="J\u00e1 \u00e9 um membro?";this.e.MSG_EDIT_PROFILE="Editar perfil"};gfc_7[gfc_].wa={};
gfc_7[gfc_].dr=function(){this.wa.MSG_SITE_MEMBERS="Seguidores";this.wa.MSG_NO_SITE_MEMBERS="Ainda n\u00e3o h\u00e1 seguidores.";this.wa.MSG_SHOW_BLOCKED="Mostrar seguidores bloqueados \u00bb";this.wa.MSG_SHOW_ALL="\u00ab Mostrar todos os seguidores";this.wa.MSG_ALL_SITE_MEMBERS="Todos os seguidores";this.wa.MSG_ALL_BLOCKED_MEMBERS="Todos os seguidores bloqueados";this.wa.MSG_NO_BLOCKED_MEMBERS="Voc\u00ea n\u00e3o bloqueou nenhum seguidor";this.wa.MSG_LIKE_THIS_SITE="Gostou deste blog?";this.wa.MSG_JOIN=
"Seguir";this.wa.MSG_BACK_TO_TOP="Membros";this.wa.MSG_JFJ="Participe e conecte-se aos seus amigos!";this.wa.MSG_HELP_FRIENDREQUEST="Voc\u00ea e seus amigos ver\u00e3o uns aos outros em todos os blogs que estiverem seguindo e sites do Google Friend Connect.";this.wa.MSG_HELP_FRIENDINVITE="Depois de se tornarem amigos, voc\u00eas ver\u00e3o um ao outro em todos os blogs que estiverem seguindo e sites do Google Friend Connect."};
gfc_7[gfc_].N=function(a,b){var c=gfc_b;if(b[gfc_F]&&b[gfc_F].person){var d={},e=b[gfc_F].person[gfc_Eb]()+" \u00e9 seu(sua) amigo(a)";d.MSG_IS_FRIEND=e;e="Voc\u00ea convidou "+(b[gfc_F].person[gfc_Eb]()+" para ser seu(sua) amigo(a)");d.MSG_IS_INVITED=e;e="Amigos de "+b[gfc_F].person[gfc_Eb]();d.MSG_PROFILE_FRIENDS=e;e="Todos os amigos de "+b[gfc_F].person[gfc_Eb]();d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.g(a,f,d[f])}if(b.invitedBy&&b.invitedBy[gfc_Eb]()){d=gfc_j[gfc_p]?gfc_j[gfc_p]:gfc_j[gfc_y][gfc_5a]+
2;c=(d-135)/8;d=(d-175)/8;c="Visualizar perfil de "+gfc_ml(b.invitedBy[gfc_Eb](),c);d=gfc_ml(b.invitedBy[gfc_Eb](),d)+" convidou voc\u00ea para este site";this.g(a,"MSG_VIEW_INVITER_PROFILE",c);this.g(a,"MSG_INVITED_YOU",d);this.Uv=gfc_b;c=gfc_d}d=this.numWaitingMessages+" mensagens aguardando voc\u00ea.";if(this.isMessagingEnabled&&this.numWaitingMessages>0){c=gfc_d;this.g(a,"showWaitingMessages",gfc_b);if(this.isMessagingEnabled){this.g(a,"MSG_NUM_WAITING_MESSAGES",d);this.g(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING",
"Visualizar mensagens")}}if(b.friendRequests){if(b.friendRequests[gfc_1a]()>0)c=gfc_d;if(b.friendRequests[gfc_1a]()==1)d="Solicita\u00e7\u00e3o de novo amigo \u00bb";else d=d="Solicita\u00e7\u00f5es de novos amigos ("+(b.friendRequests[gfc_1a]()+") \u00bb");this.g(a,"MSG_NEW_FRIEND_REQUESTS",d)}if(this.lb){if(this.jl(this.lb.themeId))for(f in this.wa)this.g(a,f,this.wa[f]);this.lb.signInPrompt&&this.g(a,"MSG_JOIN",this.lb.signInPrompt);this.lb.signOutPrompt&&this.g(a,"MSG_SIGN_OUT",this.lb.signOutPrompt)}this.g(a,
"isViewerAdmin",b.isViewerAdmin);this.g(a,"isMessagingEnabled",this.isMessagingEnabled);this.g(a,"acceptMessages",this.Kn);this.g(a,"isViewingSelf",b.viewer&&b[gfc_F]&&b[gfc_F].person&&b.viewer[gfc_B]()==b[gfc_F].person[gfc_B]());d=gfc_d;if(b.owner)if(b=b.owner[gfc_K]("profileExtensions"))for(f in b)d=gfc_b;this.g(a,"communityHasProfile",d);this.g(a,"promoHtml",c?this.promoHtml:gfc_c);this.g(a,"insertHtml",function(g,h){gfc_pa(g,h)})};gfc_7[gfc_].jl=function(a){return a=="blogger"};
gfc_7[gfc_].bh=function(a,b,c,d){gfc_Vl({id:a,text:b,version:this.jl(this.lb.themeId)?1:gfc_c,style:c},d)};
gfc_7[gfc_].Q=function(a){function b(e,f){d.g(a,e,gfc_N(f,d))}this.g(a,"facesPerRow",this.Xb);for(var c in this.e)this.g(a,c,this.e[c]);var d=this;b("getThumbnail",this.tc);b("map",this.map);b("elide",gfc_ml);b("safeSlice",this.qi);b("showAllActivities",this.Fv);b("transformActivity",this.gc);b("nextActivities",this.ms);b("previousActivities",this.Xs);b("showAllLinks",this.Hv);b("transformLink",this.sw);b("nextLinks",this.rs);b("previousLinks",this.Zs);b("showAllSites",this.Kv);b("transformSite",
this.tw);b("nextSites",this.ys);b("previousSites",this.ft);b("showAllMembers",this.Iv);b("showBlockedMembers",this.Mv);b("showUnblockedMembers",this.cw);b("nextMembers",this.ss);b("nextBlockedMembers",this.ns);b("previousMembers",this.$s);b("previousBlockedMembers",this.Ys);b("showAllProfileFriends",this.Jv);b("nextProfileFriends",this.xs);b("previousProfileFriends",this.et);b("showAllViewerFriends",this.Lv);b("nextViewerFriends",this.zs);b("previousViewerFriends",this.gt);b("isHome",this.Mh);b("goBack",
this.qh);b("goBackToHome",this.Vv);b("invite",this.invite);b("editSettings",this.Bb);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.An);b("blockUser",this.lj);b("unblockUser",this.vw);b("goToInviteFriend",this.nq);b("sendMessageDialog",this.cv);b("goToBlockMember",this.mq);b("goToEditProfile",this.Bb);b("goToViewerProfile",this.oq);b("sendInvite",this.bv);b("blockMember",this.co);b("acceptFriendRequest",this.Jn);b("ignoreFriendRequest",this.cr);b("viewFriendRequests",this.Fw);
b("acceptAllFriendRequests",this.In);b("numPreviewFriends",this.Wp);b("numPreviewMembers",this.Xp);b("showInvitedBy",this.cq)};
gfc_7[gfc_].Dk=function(a){a=gfc_k.max(1,a?this.oc-1:this.oc);var b=this.d[gfc_r].members?this.d[gfc_r].members[gfc_1a]():0,c=this.d[gfc_r].friends?this.d[gfc_r].friends[gfc_1a]():0;b=gfc_k[gfc_cm](b/this.Xb);c=gfc_k[gfc_cm](c/this.Xb);if(b>gfc_k[gfc_cm](a/2))if(c>gfc_k[gfc_eb](a/2)){b=gfc_k[gfc_cm](a/2);c=gfc_k[gfc_eb](a/2)}else b=gfc_k.max(0,a-c);else if(c>gfc_k[gfc_eb](a/2))c=gfc_k.max(0,a-b);b=b*this.Xb;c=c*this.Xb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].Xp=function(a){return this.Dk(a).numMembers};
gfc_7[gfc_].Wp=function(a){return this.Dk(a).numFriends};gfc_7[gfc_].vu=function(a,b){var c=gfc_i[gfc_I](),d={},e=gfc_i[gfc_z][gfc_gc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_Wb];d[e.MAX]=b.pageSize?b.pageSize:this.ta;b=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Ua],gfc_i[gfc_u][gfc_J][gfc_Cc]];d[e[gfc_jc]]=b;d[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c.add(c[gfc_Ub](gfc_Pd(),d),"ownerFriends");c[gfc_E](a)};gfc_7[gfc_].pt=function(a){this.d[gfc_r].members=a.get("ownerFriends")[gfc_s]()};
gfc_7[gfc_].pu=function(a,b){var c=gfc_i[gfc_I](),d={},e=gfc_i[gfc_z][gfc_gc];d[e.FIRST]=b[gfc_Wb];d[e.MAX]=b.pageSize?b.pageSize:this.ta;d[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;b={};b[gfc_i[gfc_Pa][gfc_J][gfc_Db]]=gfc_i[gfc_Pa].PersonId.OWNER;b[gfc_i[gfc_Pa][gfc_J][gfc_gb]]="BLOCKED";b[gfc_i[gfc_Pa][gfc_J][gfc_Ta]]=1;b=gfc_i[gfc_Kc](b);c.add(c[gfc_Ub](b,d),"blockedMembers");c[gfc_E](a)};gfc_7[gfc_].lt=function(a){this.d[gfc_r].blockedMembers=a.get("blockedMembers")[gfc_s]()};
gfc_7[gfc_].Bu=function(a,b){var c=gfc_i[gfc_I](),d=b&&b.person&&b.person[gfc_B]()||this.G[gfc_F].person[gfc_B](),e={},f=gfc_i[gfc_z][gfc_gc];e[f.FIRST]=b[gfc_Wb];e[f.MAX]=b.pageSize?b.pageSize:this.ta;b=this.Ol(d);e[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c.add(c[gfc_Ub](b,e),"profileFriends");c[gfc_E](a)};gfc_7[gfc_].Ol=function(a){var b={};b[gfc_i[gfc_Pa][gfc_J][gfc_Db]]=a;b[gfc_i[gfc_Pa][gfc_J][gfc_gb]]="FRIENDS";b[gfc_i[gfc_Pa][gfc_J][gfc_Ta]]=1;return gfc_i[gfc_Kc](b)};
gfc_7[gfc_].ut=function(a){this.d[gfc_r][gfc_F].friends=a.get("profileFriends")[gfc_s]()};gfc_7[gfc_].dj=function(a){for(var b=gfc_i[gfc_r].getDataContext(),c=0;c<a[gfc_n];c++){var d=a[c];d=b.getDataSet(d);if(!d||d.code)return gfc_d}return gfc_b};
gfc_7[gfc_].wu=function(a){var b=this.ta,c=!b||b==24;if(c&&gfc_i[gfc_r])if(this.dj(["ownerFriends","viewer","siteSettings","friendRequests"])){a(gfc_i[gfc_r].getDataContext()[gfc_s]());return}c=gfc_bm.newBatch();b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"};c.add("ownerFriends",gfc_bm.people.get(b));c.add("viewer",gfc_bm.people.getViewer());c.add("siteSettings",gfc_bm.extensions.get({command:"GetSiteSettings"}));c.add("friendRequests",gfc_bm.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'}));(b=gfc_ia().psinvite)&&c.add("invitedBy",gfc_bm.extensions.get({command:"DecodeInvitation",params:{token:b}}));c.execute(a)};gfc_7[gfc_].qt=function(a,b){this.d[gfc_r].members=gfc_Hd(a.ownerFriends,gfc_Cd);this.d[gfc_r].viewer=gfc_Cd(a.viewer);this.im(a,b,gfc_b);this.lb=a[gfc_kc];b=gfc_ia();if(b.psinvite)if(this.d[gfc_r].viewer==gfc_c||this.d[gfc_r].viewer==""){if(a.invitedBy)a.invitedBy.nickname=a.invitedBy.displayName;this.d[gfc_r].invitedBy=new gfc_i[gfc_u](a.invitedBy)}};
gfc_7[gfc_].Ou=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_Wb]||b[gfc_Wb]==0,e=!c||c==20;if(d&&e&&gfc_i[gfc_r])if(this.dj(["friends","isViewerAdmin"])){a(gfc_i[gfc_r].getDataContext()[gfc_s]());return}d=gfc_bm.newBatch();c={userId:"@viewer",groupId:"@friends",count:c};if(b[gfc_Wb])c.startIndex=b[gfc_Wb];d.add("friends",gfc_bm.people.get(c));d.add("isViewerAdmin",gfc_bm.people.get({userId:"@viewer",groupId:"ADMINS"}));d.execute(a)};
gfc_7[gfc_].At=function(a){var b=a.friends;if(b&&!b.error)this.d[gfc_r].friends=gfc_Hd(b,gfc_Cd);this.Lm(a)};gfc_7[gfc_].Pu=function(a){var b=gfc_i[gfc_I]();b.add(gfc_Fd("VIEWER"),"numWaitingMessages");b[gfc_E](a)};gfc_7[gfc_].Ct=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_s]().numberOfWaitingMessages};
gfc_7[gfc_].Du=function(a){this.log("requesting promo");var b=new gfc_e[gfc_xb];b=b.getLang()+(b[gfc_cc]()?"_"+b[gfc_cc]():"");var c=gfc_i[gfc_I]();c.add(gfc_ud("GetPromo",{hl:b}),"promo");c[gfc_E](a)};gfc_7[gfc_].wt=function(a){this.log("processing promo");if((a=a.get("promo")[gfc_s]())&&a.promoCode!=-1){this.promoCode=a.promoCode;this.promoHtml=a.promoHtml}};
gfc_7[gfc_].Rn=function(){for(var a=function(){this.promoHtml=gfc_c;for(var f=gfc__f("div","fc-promo-main",gfc_T("peg")),g=0;g<f[gfc_n];g++)gfc_Lg(f[g],gfc_d);this.W();this.log("Dismissing promo "+this.promoCode);f=gfc_i[gfc_I]();f.add(gfc_ud("DismissPromo",{promoCode:this.promoCode}));f[gfc_E](gfc_N(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc__f("a","fc-promo-dismiss-link",gfc_T("peg")),c=0;c<b[gfc_n];c++){var d=b[c],e="click";gfc_yh(d,e);gfc_sh(d,e,gfc_N(a,
this))}};gfc_7[gfc_].Lm=function(a){var b=a.isViewerAdmin;if(b&&!b.error)this.d[gfc_r].isViewerAdmin=b.list[gfc_n];else if(a.get&&a.get("isViewerAdmin"))if((a=a.get("isViewerAdmin"))&&!a[gfc_tb]())this.d[gfc_r].isViewerAdmin=a[gfc_s]()[gfc_1a]()};gfc_7[gfc_].In=function(a){var b=[];a.each(function(c){c={user:c[gfc_K](goog.opensocial.peoplesense.Invite[gfc_J].INVITER)[gfc_B](),action:"ACCEPT"};b[gfc_m](c)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_N(this.Jg,this),{friendRequestResponses:b})};
gfc_7[gfc_].Vv=function(){this.ia();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].Jn=function(a){a={user:a[gfc_B](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_N(this.Jg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Fw=function(){this.ia();this.z("friend-requests")};gfc_7[gfc_].An=function(a){if(this.Mb()){this.ia();this.Hw(a)}else gfc_qd(a[gfc_B]())};
gfc_7[gfc_].Hw=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].Ju=function(a,b){var c=gfc_i[gfc_I](),d=gfc_i[gfc_z][gfc_gc],e={};e[d.FIRST]=b&&b[gfc_Wb]?b[gfc_Wb]:0;b=this.d[gfc_r][gfc_F].person[gfc_B]();e[d.MAX]=this.jn;c.add(gfc_Md(gfc_i[gfc_Kc]({userId:b}),e),"profileSites");c[gfc_E](a)};gfc_7[gfc_].yt=function(a){this.d[gfc_r][gfc_F].sites=a.get("profileSites")[gfc_s]()};
gfc_7[gfc_].Au=function(a,b){this.d[gfc_r].profile={};b=b||{};var c=b.person;b={};c=c[gfc_B]();var d=gfc_i[gfc_I](),e=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Ua],gfc_i[gfc_u][gfc_J][gfc_Cc],gfc_i[gfc_u][gfc_J].ABOUT_ME,gfc_i[gfc_u][gfc_J].URLS,"profileExtensions"],f=gfc_i[gfc_z][gfc_gc];b[f[gfc_jc]]=e;b[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;d.add(d.newFetchPersonRequest(c,b),"profile");d.add(d.newFetchPersonRequest("VIEWER",b),"viewer");d.add(gfc_Kd("VIEWER","ADMINS"),
"isViewerAdmin");d.add(d.newFetchPersonRequest("OWNER",b),"owner");this.lb||d.add(gfc_Ed(),"siteSettings");d.add(gfc_Kd(c,"ADMINS"),"isAdmin");d.add(gfc_Kd(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&d.add(gfc_Fd(c),"canMessage");d[gfc_E](a)};
gfc_7[gfc_].Wf=function(a,b){var c=b.person[gfc_B](),d=gfc_i[gfc_Kc]({userId:c}),e=gfc_i[gfc_I]();if(this.d[gfc_r].viewer&&c!=this.d[gfc_r].viewer[gfc_B]()||this.Mb())e.add(gfc_Jd(b.person[gfc_B](),"VIEWER"),"isProfileFriend");e.add(e[gfc_qb](d,{}),"activities");e[gfc_E](a)};
gfc_7[gfc_].rd=function(a,b){if(a.get("activities")[gfc_s]()!=gfc_c)this.d[gfc_r][gfc_F].activities=a.get("activities")[gfc_s]();if(a=a.get("isProfileFriend"))if(b&&this.d[gfc_r].viewer!=gfc_c&&this.d[gfc_r].viewer[gfc_B]()!=b.person[gfc_B]())this.d[gfc_r][gfc_F].isFriend=a[gfc_s]()[gfc_t]};
gfc_7[gfc_].tt=function(a,b){var c=a.get("profile")[gfc_s]();this.d[gfc_r][gfc_F].person=c;this.d[gfc_r][gfc_F].person.externalProfileUrl=gfc_c;var d=c[gfc_K](gfc_i[gfc_u][gfc_J].URLS),e=[];if(d)for(var f=0;f<d[gfc_n];f++){var g=d[f];g[gfc_K](gfc_i.Url[gfc_J].TYPE)!="profile"&&g[gfc_K](gfc_i.Url[gfc_J].TYPE)!="externalProfile"&&e[gfc_m](g);if(g[gfc_K](gfc_i.Url[gfc_J].TYPE)=="externalProfile")this.d[gfc_r][gfc_F].person.externalProfileUrl=g[gfc_K](gfc_i.Url[gfc_J].ADDRESS)}this.d[gfc_r][gfc_F].links=
new gfc_fm(e,this.Kf,0);this.d[gfc_r].owner=a.get("owner")[gfc_s]();this.d[gfc_r].viewer=a.get("viewer")[gfc_s]();if((d=this.d[gfc_r].viewer)&&b.person[gfc_B]()!=this.d[gfc_r].viewer[gfc_B]()){this.d[gfc_r][gfc_F].isAdmin=a.get("isAdmin")[gfc_s]();if(this.d[gfc_r][gfc_F].isAdmin)this.d[gfc_r][gfc_F].isAdmin=this.d[gfc_r][gfc_F].isAdmin[gfc_1a]();this.d[gfc_r][gfc_F].isBlocked=a.get("isBlocked")[gfc_s]();if(this.d[gfc_r][gfc_F].isBlocked)this.d[gfc_r][gfc_F].isBlocked=this.d[gfc_r][gfc_F].isBlocked[gfc_1a]()}b=
c[gfc_K]("profileExtensions");b=this.Pb.Df(b,this.Pb.Fi);c=[];for(f in b){d=b[f];e={};e.title=d.title;g=gfc_d;if(d.entryType=="SHORT_TEXT"||d.entryType=="LONG_TEXT"){if(d[gfc_t]&&d[gfc_t][gfc_4a]){e.body=[];e[gfc_y][gfc_m](d[gfc_t][gfc_4a]);g=gfc_b}}else if(d[gfc_t]&&d[gfc_t].choice&&d[gfc_t].choice[gfc_n]>0){e.body=[];for(g=0;g<d[gfc_t].choice[gfc_n];++g)e[gfc_y][gfc_m](d[gfc_t].choice[g][gfc_yc]);g=gfc_b}g&&c[gfc_m](e)}this.d[gfc_r][gfc_F].profileExtensions=c;if(!this.lb)this.lb=a.get("siteSettings")[gfc_s]();
if(this.isMessagingEnabled){f=(f=a.get("canMessage"))&&f[gfc_s]().canSendMessage;this.d[gfc_r][gfc_F].canSendMessage=f}this.Lm(a)};gfc_7[gfc_].lj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].vw=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[];b=gfc_N(function(d,e,f){d[gfc_m](e(f))},this,c,b);a.each(b);return c};gfc_7[gfc_].Iv=function(){this.ia();this.z("members-page")};
gfc_7[gfc_].Mv=function(){this.ia();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].cw=function(){this.Ni()};gfc_7[gfc_].ss=function(a){this.render(["member-page"],"members-page",{start:this.ta+a.getOffset()})};gfc_7[gfc_].$s=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.ta})};gfc_7[gfc_].ns=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.ta+a.getOffset()})};
gfc_7[gfc_].Ys=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.ta})};gfc_7[gfc_].Lv=function(){this.ia();this.z("viewer-friends-page")};gfc_7[gfc_].zs=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.ta+a.getOffset()})};gfc_7[gfc_].gt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.ta})};gfc_7[gfc_].Jv=function(){this.ia();this.z("profile-friends-page")};
gfc_7[gfc_].xs=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.ta+a.getOffset(),person:this.d[gfc_r][gfc_F].person})};gfc_7[gfc_].et=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.ta,person:this.d[gfc_r][gfc_F].person})};gfc_7[gfc_].Hv=function(){this.ia();this.z("links")};gfc_7[gfc_].rs=function(a){var b=this.Kf+a.getOffset();this.d[gfc_r][gfc_F].links=new gfc_fm(a.all(),this.Kf,b);this.z("links")};
gfc_7[gfc_].Zs=function(a){var b=a.getOffset()-this.Kf;this.d[gfc_r][gfc_F].links=new gfc_fm(a.all(),this.Kf,b);this.z("links")};gfc_7[gfc_].Kv=function(){this.ia();this.z("sites")};gfc_7[gfc_].ys=function(a){this.render(["sitesData"],"sites",{start:this.jn+a.getOffset()})};gfc_7[gfc_].ft=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.jn})};gfc_7[gfc_].Fv=function(){this.ia();this.z("activities")};
gfc_7[gfc_].ms=function(a){this.render(["activityData"],"activities",{start:this.Fa+a.getOffset()})};gfc_7[gfc_].Xs=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Fa})};gfc_7[gfc_].qf=function(a){this.render(["deleteActivity"],this.d[gfc_Hb],{activity:a})};gfc_7[gfc_].ou=function(a,b){var c=gfc_i[gfc_I]();c.add(gfc_Ld(b.person[gfc_B](),["BLOCKED"],[]),"block");this.kd();c[gfc_E](a)};
gfc_7[gfc_].kt=function(a){if(a=!a.get("block")[gfc_tb]())this.d[gfc_r][gfc_F].isBlocked=gfc_b};gfc_7[gfc_].Mu=function(a,b){var c=gfc_i[gfc_I]();c.add(gfc_Ld(b.person[gfc_B](),[],["BLOCKED"]),"unblock");this.kd();c[gfc_E](a)};gfc_7[gfc_].zt=function(a){if(a=!a.get("unblock")[gfc_tb]())this.d[gfc_r][gfc_F].isBlocked=gfc_d};
gfc_7[gfc_].Xf=function(a,b){var c=b.activity;b=c[gfc_K](gfc_i[gfc_Xb][gfc_J].ID);c=gfc_i[gfc_Kc]({userId:c[gfc_K](gfc_i[gfc_Xb][gfc_J][gfc_Db])});var d=gfc_i[gfc_I]();d.add(gfc_vd(b),"delete");d.add(d[gfc_qb](c,{}),"activities");d[gfc_E](a)};
gfc_7[gfc_].gc=function(a){var b=gfc_3l,c=function(f){return f=f[gfc_q](/<a/g,"<a target='_top'")},d=gfc_c,e=this.d[gfc_r].viewer;if(e!=gfc_c&&a[gfc_K](gfc_i[gfc_Xb][gfc_J][gfc_Db])==this.d[gfc_r].viewer[gfc_B]())d=gfc_N(this.qf,this,a);(e=a[gfc_K](gfc_i[gfc_Xb][gfc_J].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_h.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ea(a[gfc_K](gfc_i[gfc_Xb][gfc_J].POSTED_TIME))),link:a[gfc_K](gfc_i[gfc_Xb][gfc_J].STREAM_URL,{escapeType:"none"}),
siteTitle:a[gfc_K](gfc_i[gfc_Xb][gfc_J].STREAM_TITLE,{escapeType:"none"}),innerHTML:c(a[gfc_K](gfc_i[gfc_Xb][gfc_J].TITLE,{escapeType:"none"})),body:c(a[gfc_K](gfc_i[gfc_Xb][gfc_J].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].tw=function(a){var b=gfc_e[gfc_fc].unescapeString,c=gfc_dm;return{icon:c(a[gfc_K](gfc_i[gfc_u][gfc_J][gfc_3b])),link:a[gfc_K](gfc_i[gfc_u][gfc_J][gfc_3b]),title:b(a[gfc_Eb]())}};
gfc_7[gfc_].sw=function(a){var b=gfc_e[gfc_fc].unescapeString,c=gfc_dm,d=a[gfc_K](gfc_i.Url[gfc_J].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_K](gfc_i.Url[gfc_J].LINK_TEXT))||d}};
gfc_7[gfc_].Cu=function(a,b){var c=gfc_i[gfc_I]();b=b.person[gfc_B]();var d={},e=gfc_i[gfc_z][gfc_gc];d[e[gfc_jc]]=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Ua]];var f=this.Ol(b),g={};g[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c.add(c[gfc_Ub](f,g),"friends");f={};f[e.FIRST]=this.zx;f[e.MAX]=this.yx;c.add(gfc_Md(gfc_i[gfc_Kc]({userId:b}),f),"profileSites");d[e[gfc_jc]]=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Ua],gfc_i[gfc_u][gfc_J][gfc_Cc],gfc_i[gfc_u][gfc_J].ABOUT_ME];
d[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c[gfc_E](a)};gfc_7[gfc_].cr=function(a){a={user:a[gfc_B](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_N(this.Jg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Jg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].Iu=function(a,b){var c=b[gfc_F],d=gfc_i[gfc_I]();d.add(gfc_wd(c[gfc_B](),b[gfc_Ab]),"friendRequest");this.kd();d[gfc_E](a)};
gfc_7[gfc_].xt=function(a){if(!a.get("friendRequest")[gfc_tb]())this.d[gfc_r][gfc_F].isInvited=gfc_b};gfc_7[gfc_].su=function(a,b){var c=gfc_bm.newBatch();b=b.friendRequestResponses;c.add("updateFriendRequest",gfc_bm.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_e[gfc_0b].stringify(b)+"}"}));c.add("friendRequests",gfc_bm.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.kd();c.execute(a)};gfc_7[gfc_].nq=function(){this.ia();this.z("invite-friend")};
gfc_7[gfc_].cv=function(a){if(this.isMessagingEnabled){a=a[gfc_K](gfc_i[gfc_u][gfc_J].ID);this.dv(a)}};gfc_7[gfc_].dv=function(a){if(this.isMessagingEnabled){a="/friendconnect/messaging/compose?recipientId="+a;var b=570,c=395;gfc_Nl(a,gfc_g(b),gfc_g(c))}};gfc_2[gfc_].Kn=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_Nl(a,gfc_g(b),gfc_g(c));return gfc_d};gfc_7[gfc_].mq=function(){this.ia();this.z("block-member")};gfc_7[gfc_].oq=function(){this.An(this.d[gfc_r].viewer)};
gfc_7[gfc_].bv=function(a){this.Pf();a={profile:a};var b=gfc_T("inviteMessage");if(b)a.message=gfc_nf(b);this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].co=function(a){this.Pf();this.lj(a)};gfc_7[gfc_].im=function(a,b,c){c=c||gfc_d;this.d[gfc_r].friendRequests=gfc_Hd(a.friendRequests,gfc_yd);b["next-view"]=this.d[gfc_r].friendRequests[gfc_1a]()>0?"friend-requests":"faces";c||gfc_yl("friend")};
gfc_7[gfc_].vt=function(a){this.d[gfc_r][gfc_F].sites=a.get("profileSites")[gfc_s]();this.d[gfc_r][gfc_F].friends=a.get("friends")[gfc_s]()};gfc_7[gfc_].cq=function(){return this.Uv};gfc_7[gfc_].W=function(){this.$w.rebuild();this.Rn();gfc_e[gfc_Qa].adjustHeight()};gfc_7[gfc_].Ps=function(a){return a=gfc_U("span",{"class":"fc-cap-link-big"},gfc_U("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Og())};
gfc_7[gfc_].Os=function(){var a=[];a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_n]]=this.isSocialShareEnabled?gfc_U("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_U("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);if(this.d[gfc_r].isViewerAdmin&&!this.Mb())a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE);a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-signout"},
this.lb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_U("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].Qs=function(a){a[gfc_mb]();a=a[gfc_C].h()[gfc__a];if(a[gfc_Pb]("menuaction-settings"))this.Bb();else if(a[gfc_Pb]("menuaction-invite"))this.invite();else if(a[gfc_Pb]("menuaction-share"))this.share();else if(a[gfc_Pb]("menuaction-signout"))this.signout();else if(a[gfc_Pb]("menuaction-manage"))this.sq();else if(a[gfc_Pb]("menuaction-aboutfc")){a=gfc_h[gfc_Va](gfc_Fl()+"/friendconnect");a[gfc_Yb]()}};
gfc_7[gfc_].sq=function(){var a={},b=gfc_e[gfc_o][gfc_fb]().canvas;gfc_yl("lightbox");gfc_e[gfc_o].requestNavigateTo(b,a);return gfc_d};var gfc_em=function(a){for(var b={},c=0;c<a[gfc_n];++c)b[a[c]]=a[c];return b}(["HEIGHT","BORDER_COLOR","CONTENT_BG_COLOR","CONTENT_HEADLINE_COLOR","CONTENT_LINK_COLOR","CONTENT_SECONDARY_TEXT_COLOR","CONTENT_SECONDARY_LINK_COLOR","CONTENT_TEXT_COLOR","ENDCAP_BG_COLOR","ENDCAP_LINK_COLOR","ENDCAP_TEXT_COLOR","FACE_SIZE","NUMBER_ROWS"]);
gfc_7[gfc_].r=function(){var a=gfc_em,b=[],c=0;gfc_ea(this.f(a.HEIGHT));if(this.Ph())b[c++]=this.i(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE));b[c++]=this.i(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.Im);b[c++]=this.i(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));if(this.Af())if(this.Vk("profile"))b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n";else if(this.Rh())b[c++]=".fc-topcap {height: 0px;}\n";else b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n";if(this.Mb())b[c++]=".fc-userpic-caption {margin-left: 59px;}\n";else b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";if(this.Rh())b[c++]=".fc-topcap-color {background-color: white;}\n";else b[c++]=this.i(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));
if(this.kl())b[c++]=".fc-botcap-short {background-color: white;}\n";else b[c++]=this.i(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.i(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.i(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.i(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",
this.f(a.ENDCAP_TEXT_COLOR));b[c++]=this.i(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.i(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.i(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.i(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.i(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.i(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.i(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.j.r[gfc_D](this)+b[gfc_M]("\n")};gfc_O("goog.peoplesense.gadget.Members",gfc_7);gfc_O("goog.peoplesense.gadget.Members.start",gfc_7[gfc_Wb]);var gfc_fm=function(a,b,c){gfc_i.Collection[gfc_D](this,a[gfc_9a](c,c+b),c,a[gfc_n]);this.Nw=a;this.ha=b};gfc_fm.inherits(gfc_i.Collection);gfc_fm[gfc_].all=function(){return this.Nw};gfc_fm[gfc_].qb=function(){return this.ha};gfc_O("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_fm[gfc_].all);
gfc_O("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_fm[gfc_].qb);
