#
# Makefile
#
# $Id: //poco/1.3/Util/samples/SampleApp/Makefile#1 $
#
# Makefile for Poco SampleApp
#

POCO_BASE=/usr/local/poco
PROJECT_BASE=.


include $(POCO_BASE)/build/rules/global

objects = configuracao

target         = configuracao
target_version = 1
target_libs    = PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
