#
# Makefile for gerar_log based on Poco
#
#

POCO_BASE=/usr/local/poco
PROJECT_BASE=.

include $(POCO_BASE)/build/rules/global

INCLUDE += -I$(POCO_BASE)Foundation/include/Poco

objects = gera_log

target         = gera_log
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec


