#
# Makefile
#
# $Id: //poco/1.3/Net/samples/httpget/Makefile#1 $
#
# Makefile for Poco httpget
#

PROJECT_BASE=.
POCO_BASE=/usr/local/poco

include $(POCO_BASE)/build/rules/global

objects = httpget

target         = httpget
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
