#
# Makefile
#
# $Id: //poco/1.3/Net/samples/HTTPTimeServer/Makefile#1 $
#
# Makefile for Poco HTTPTimeServer
#

PROJECT_BASE=.
include $(POCO_BASE)/build/rules/global

objects = MeuWebServerXml_RetornoXml

target         = MeuWebServerXml_RetornoXml
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
