function OAS_RICH(position) {
if (position == 'Top') {
document.write ('<script type="text/javascript">\n');
document.write (' var OAS_width = ');
document.write ("'");
document.write ('728');
document.write ("'");
document.write (';\n');
document.write (' var OAS_height = ');
document.write ("'");
document.write ('90');
document.write ("'");
document.write (';\n');
document.write (' var OAS_banner_flash = ');
document.write ("'");
document.write ('super_banner.swf');
document.write ("'");
document.write (';\n');
document.write (' var OAS_camp = ');
document.write ("'");
document.write ('090331_calhau_guj_pages1_top');
document.write ("'");
document.write (';\n');
document.write (' var clickTag = ');
document.write ("'");
document.write ('oas');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('var WMODE = ');
document.write ("'");
document.write ('opaque');
document.write ("'");
document.write (';\n');
document.write ('var BGCOLOR = ');
document.write ("'");
document.write ('#FFFFFF');
document.write ("'");
document.write (';\n');
document.write (' \n');
document.write ('var PAGE = ');
document.write ("'");
document.write ('guj/internas');
document.write ("'");
document.write (';\n');
document.write ('var RAND = ');
document.write ("'");
document.write ('840133585');
document.write ("'");
document.write (';\n');
document.write ('var POS  = ');
document.write ("'");
document.write ('Top');
document.write ("'");
document.write (';\n');
document.write ('var CAMP = ');
document.write ("'");
document.write ('rmlanetwork/090331_calhau_guj_pages1_top');
document.write ("'");
document.write (';\n');
document.write ('var IMAGE= ');
document.write ("'");
document.write ('090331_calhau_guj_pages5_top.html');
document.write ("'");
document.write (';\n');
document.write ('var USER = ');
document.write ("'");
document.write ('62643465373665343461383830363430');
document.write ("'");
document.write (';\n');
document.write ('var adServer = ');
document.write ("'");
document.write ('www.icover.com.br');
document.write ("'");
document.write (';\n');
document.write ('var accountId = ');
document.write ("'");
document.write ('rmlanetwork');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('var localBannerFlash = ');
document.write ("'");
document.write ('http://');
document.write ("'");
document.write (' + adServer + ');
document.write ("'");
document.write ('/RealMedia/ads/Creatives/');
document.write ("'");
document.write (' + accountId + ');
document.write ("'");
document.write ('/');
document.write ("'");
document.write (' + OAS_camp + ');
document.write ("'");
document.write ('/');
document.write ("'");
document.write (' + OAS_banner_flash + ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write (' \n');
document.write ('document.write("<scr" + "ipt src=');
document.write ("'");
document.write ('http://www.icover.com.br/RealMedia/ads/Creatives/rmlanetwork/javascript/flashestatico_flash6_as1.js');
document.write ("'");
document.write ('>" + "</scr" + "ipt>");\n');
document.write ('\n');
document.write ('</script>');
}
if (position == 'Right') {
document.write ('<A HREF="http://media.realmedia.com.br/RealMedia/ads/click_lx.ads/guj/internas/1792765211/Right/rmlanetwork/090331_calhau_guj_pages2_right/formato_300x250.gif/62643465373665343461383830363430" target="_blank"><IMG SRC="http://media.realmedia.com.br/RealMedia/ads/Creatives/rmlanetwork/090331_calhau_guj_pages2_right/formato_300x250.gif"  ALT=""  BORDER="0"></A>');
}
if (position == 'x01') {
document.write ('<A HREF="http://media.realmedia.com.br/RealMedia/ads/click_lx.ads/guj/internas/908674915/x01/default/empty.gif/62643465373665343461383830363430" target="_blank"><IMG SRC="http://media.realmedia.com.br/RealMedia/ads/Creatives/default/empty.gif"  WIDTH=2 HEIGHT=2 ALT="" BORDER=0 BORDER="0"></A>');
}
if (position == 'x04') {
document.write ('<A HREF="http://media.realmedia.com.br/RealMedia/ads/click_lx.ads/guj/internas/1802067195/x04/rmlanetwork/090331_calhau_guj_pages_x04/120X600_INSTITUCIONAL_GUJ.gif/62643465373665343461383830363430" target="_blank"><IMG SRC="http://media.realmedia.com.br/RealMedia/ads/Creatives/rmlanetwork/090331_calhau_guj_pages_x04/120X600_INSTITUCIONAL_GUJ.gif"  ALT=""  BORDER="0"></A>');
}
}
