#
# Makefile
#
# $Id: //poco/1.3/Foundation/samples/md5/Makefile#1 $
#
# Makefile for Poco cksum
#

PROJECT_BASE=.

include $(POCO_BASE)/build/rules/global

objects = cksum

target         = cksum
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
