window.defaultStatus="SGS - Sistema de Gerenciamento do Site";function preenche(a,d){obj=document.getElementById(d);val=obj.value;fim=val+a;obj.value="";obj.value=fim}function testaSenha(a,d,e){if(erro==true)return true;obj1=eval("document."+e+"."+a);obj2=eval("document."+e+"."+d);if(obj1.value!=obj2.value){alert("Sua senha n\ufffdo foi confirmada!");document.formulario.senha.focus();return true}else return false}
function testaVazio(a,d,e,b,f){if(f==true)return true;obj1=eval("document."+e+"."+a);if(obj1.value==d){alert(b);obj1.focus();return true}else return false}function testaNumero(a,d,e,b){if(b==true)return true;obj1=eval("document."+d+"."+a);if(isNaN(obj1.value)){obj1.value="";alert(e);obj1.focus();return true}else return false}function mostraConteudo(a,d){obj_cont=document.getElementById(a);obj_local=document.getElementById(d);obj_local.innerHTML=obj_cont.innerHTML}
function verDados(a,d){if(a=="")alert("Voc\ufffd deve escolher um valor v\ufffdlido!");else if(a==0)alert("Voc\ufffd deve escolher um valor, n\ufffdo uma categoria!");else document.location="principal.php?m="+d+"&action=ver&valor="+a}function closeObj(a,d){obj=document.getElementById(a);if(d=="display")obj.style.display="none";else obj.style.visibility="hidden"}function openObj(a,d){obj=document.getElementById(a);if(d=="display")obj.style.display="block";else obj.style.visibility="visible"}
function gerenciaAbas(a,d){document.getElementById("aba").value=a;for(x=1;x<=d;x++){document.getElementById("aba_bt_"+x).className="";document.getElementById("abas_cad_"+x).style.display="none"}document.getElementById("aba_bt_"+a).className="selected";document.getElementById("abas_cad_"+a).style.display="block"}
function changeAba(a,d,e){for(x=1;x<=e;x++){$("#"+a+"aba_"+x).removeClass("choose");$("#"+a+"aba_"+x).addClass("aba");$("#"+a+"div_"+x).hide()}$("#"+a+"aba_"+d).removeClass("aba");$("#"+a+"aba_"+d).addClass("choose");$("#"+a+"div_"+d).show()}var lastzoekstr="J29dWTNVQV8TugOoCaLplUHwWPTgbWE8";
function selectSearch(a,d){a=a.toLowerCase();if(a!=lastzoekstr&&a!=""){lastzoekstr=a;var e=d.options.length,b=0;for(b=0;b<e;b++){var f=d.options[b].value;f=d.options[b].text;if(a==""||f.toLowerCase().indexOf(a)>=0){d.options[b].selected=true;d.options[b].style.display="block"}else d.options[b].style.display="none"}}}function resetaSelectSearch(a){var d=a.options.length,e=0;for(e=0;e<d;e++)a.options[e].style.display="block";a.options[0].selected=true}
function FormataValor(a,d,e){if(window.event)var b=e.keyCode;else if(e.which)b=e.which;vr=document.getElementById(a).value;vr=vr.toString().replace("/","");vr=vr.toString().replace("/","");vr=vr.toString().replace(",","");vr=vr.toString().replace(".","");vr=vr.toString().replace(".","");vr=vr.toString().replace(".","");vr=vr.toString().replace(".","");tam=vr.length;if(tam<d&&b!=8)tam=vr.length+1;if(b==8)tam-=1;if(b==8||b>=48&&b<=57||b>=96&&b<=105){if(tam<=2)document.getElementById(a).value=vr;if(tam>
2&&tam<=5)document.getElementById(a).value=vr.substr(0,tam-2)+","+vr.substr(tam-2,tam);if(tam>=6&&tam<=8)document.getElementById(a).value=vr.substr(0,tam-5)+"."+vr.substr(tam-5,3)+","+vr.substr(tam-2,tam);if(tam>=9&&tam<=11)document.getElementById(a).value=vr.substr(0,tam-8)+"."+vr.substr(tam-8,3)+"."+vr.substr(tam-5,3)+","+vr.substr(tam-2,tam);if(tam>=12&&tam<=14)document.getElementById(a).value=vr.substr(0,tam-11)+"."+vr.substr(tam-11,3)+"."+vr.substr(tam-8,3)+"."+vr.substr(tam-5,3)+","+vr.substr(tam-
2,tam);if(tam>=15&&tam<=17)document.getElementById(a).value=vr.substr(0,tam-14)+"."+vr.substr(tam-14,3)+"."+vr.substr(tam-11,3)+"."+vr.substr(tam-8,3)+"."+vr.substr(tam-5,3)+","+vr.substr(tam-2,tam)}}function checkAll(a,d,e){if(e==true)for(x=0;x<d;x++)document.getElementById(a+x).checked=true;else for(x=0;x<d;x++)document.getElementById(a+x).checked=false}
function relogio(){momentoAtual=new Date;hora=momentoAtual.getHours();minuto=momentoAtual.getMinutes();segundo=momentoAtual.getSeconds();hora=hora.toString();minuto=minuto.toString();segundo=segundo.toString();if(hora.length==1)hora="0"+hora;if(minuto.length==1)minuto="0"+minuto;if(segundo.length==1)segundo="0"+segundo;horaImprimivel=hora+":"+minuto+":"+segundo;$("#hr").html(horaImprimivel);setTimeout("relogio()",1E3)}
function alerta(a,d){$("#alerta").html(a);$("#alerta").removeClass("error");$("#alerta").removeClass("ok");$("#alerta").addClass(d);$("#alerta").slideDown();setTimeout("$('#alerta').slideUp();",2E3)}function fechaSessao(a){}
function FormataCNPJ(a,d){var e=d.keyCode,b=new String(a.value);b=b.replace(".","");b=b.replace(".","");b=b.replace("/","");b=b.replace("-","");tam=b.length+1;if(e!=9&&e!=8){if(tam>2&&tam<6)a.value=b.substr(0,2)+"."+b.substr(2,tam);if(tam>=6&&tam<9)a.value=b.substr(0,2)+"."+b.substr(2,3)+"."+b.substr(5,tam-5);if(tam>=9&&tam<13)a.value=b.substr(0,2)+"."+b.substr(2,3)+"."+b.substr(5,3)+"/"+b.substr(8,tam-8);if(tam>=13&&tam<15)a.value=b.substr(0,2)+"."+b.substr(2,3)+"."+b.substr(5,3)+"/"+b.substr(8,
4)+"-"+b.substr(12,tam-12)}}function mascara_cpf(a,d,e){var b="";b+=d;if(b.length==3){b+=".";ct_campo=eval("document."+e+"."+a+".value = mydata")}if(b.length==7){b+=".";ct_campo=eval("document."+e+"."+a+".value = mydata")}if(b.length==11){b+="-";ct_campo1=eval("document."+e+"."+a+".value = mydata")}b.length==14&&valida_cpf(e,a)}
function valida_cnpj(a,d){pri=eval("document."+a+"."+d+".value.substring(0,2)");seg=eval("document."+a+"."+d+".value.substring(3,6)");ter=eval("document."+a+"."+d+".value.substring(7,10)");qua=eval("document."+a+"."+d+".value.substring(11,15)");qui=eval("document."+a+"."+d+".value.substring(16,18)");var e;e="";s=pri+seg+ter+qua+qui;c=s.substr(0,12);var b=s.substr(12,2),f=0;for(e=0;e<12;e++)f+=c.charAt(11-e)*(2+e%8);if(f==0)var g="falso";f=11-f%11;if(f>9)f=0;if(b.charAt(0)!=f)g="falso";f*=2;for(e=
0;e<12;e++)f+=c.charAt(11-e)*(2+(e+1)%8);f=11-f%11;if(f>9)f=0;if(b.charAt(1)!=f)g="falso";if(g=="falso"){alert("CNPJ inv\ufffdlido!");aux1=eval("document."+a+"."+d+".focus");aux2=eval("document."+a+"."+d+".value = ''")}}
function valida_cpf(a,d){pri=eval("document."+a+"."+d+".value.substring(0,3)");seg=eval("document."+a+"."+d+".value.substring(4,7)");ter=eval("document."+a+"."+d+".value.substring(8,11)");qua=eval("document."+a+"."+d+".value.substring(12,14)");var e;s=pri+seg+ter+qua;c=s.substr(0,9);var b=s.substr(9,2),f=0;for(e=0;e<9;e++)f+=c.charAt(e)*(10-e);if(f==0)var g="falso";f=11-f%11;if(f>9)f=0;if(b.charAt(0)!=f)g="falso";f*=2;for(e=0;e<9;e++)f+=c.charAt(e)*(11-e);f=11-f%11;if(f>9)f=0;if(b.charAt(1)!=f)g=
"falso";if(g=="falso"){alert("CPF inv\ufffdlido!");aux1=eval("document."+a+"."+d+".focus");aux2=eval("document."+a+"."+d+".value = ''")}}function formatar(a,d){var e=a.value.length,b=d.substring(0,1);e=d.substring(e);if(e.substring(0,1)!=b)a.value+=e.substring(0,1)};function ajax(a,d,e,b,f,g){g||(g="POST");$.ajax({type:g,url:a,data:d,success:function(h){$("#pg_tit").html(e);$("#in_page").html(h);b&&$("#page_over").css("width",b);f||$("#page_over").toggle()}})}function ajaxDireto(a,d,e,b){b||(b="POST");$.ajax({type:b,url:a,data:d,success:function(f){$("#"+e).html(f)}})}
function sendPost(a,d,e,b,f){forme=eval("document."+a);var g;for(x=0;x<forme.elements.length;x++)if(forme.elements[x].name.search(d)!="-1")if(forme.elements[x].type=="radio"&&forme.elements[x].checked)g+="&"+forme.elements[x].name.replace(d,"")+"="+forme.elements[x].value;else if(forme.elements[x].type!="radio"&&forme.elements[x].type!="checkbox")g+="&"+forme.elements[x].name.replace(d,"")+"="+forme.elements[x].value;g=g.replace("undefined","");ajaxDireto(e,b+g,f)};