var gfc_4l=osapi,gfc_5l="ceil";gfc_2[gfc_].share=gfc_Pc(24,function(){gfc_Pl();return gfc_d});gfc_Te[gfc_].ceil=gfc_Pc(20,function(){gfc_oa(this,gfc_k[gfc_5l](this[gfc_p]));gfc_Ja(this,gfc_k[gfc_5l](this[gfc_L]));return this});gfc_2[gfc_].Ni=gfc_Pc(19,function(){var a=this.Hd;if(a.valid){this.d=this.Lg(this.Hd);this.Th(a[gfc_Eb])}else{this.Hd=gfc_c;this.render(a.actions,a[gfc_Eb],a.params)}this.Kg()});gfc_2[gfc_].Of=gfc_Pc(14,function(){return this.Fb.pop()});
gfc_2[gfc_].pi=gfc_Pc(5,function(a,b,c){return a?c<b?[]:a[gfc_9a](gfc_k.min(b,a[gfc_n]),gfc_k.min(c,a[gfc_n])):[]});
var gfc_6l=function(a){return a=gfc_h.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ia();this.gr();var d=new gfc_Q;d.set("members",{action:this.Au,callback:this.ut});d.set("member-page",{action:this.zu,callback:this.tt});d.set("blocked-member-page",{action:this.tu,callback:this.pt});d.set("profile-friends-page",{action:this.Fu,callback:this.yt});d.set("sitesData",{action:this.Nu,callback:this.Ct});d.set("viewerFriends",{action:this.Su,callback:this.Et});
d.set("profileData",{action:this.Eu,callback:this.xt});d.set("blockUser",{action:this.su,callback:this.ot});d.set("unblockUser",{action:this.Qu,callback:this.Dt});d.set("profileFriends",{action:this.Gu,callback:this.zt});d.set("activityData",{action:this.Vf,callback:this.qd});d.set("sendFriendRequest",{action:this.Mu,callback:this.Bt});d.set("sendFriendRequestResponse",{action:this.wu,callback:this.jm});d.set("deleteActivity",{action:this.Wf,callback:this.qd});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.Tu,callback:this.Gt});d.set("requestPromo",{action:this.Hu,callback:this.At});this.kb=gfc_c;this.dx=new gfc_Xl("fc-members-options-menu",gfc_N(this.Ts,this),gfc_N(this.Ss,this),gfc_N(this.Us,this),0,gfc_h.friendconnect_serverBase,this.g("ENDCAP_LINK_COLOR")||"0000cc",this.g("CONTENT_TEXT_COLOR")||"000000");this.Yv=gfc_d;this.Ea=10;this.Jf=15;this.kn=10;var e=gfc_8g(gfc_Xg()),f=gfc_7l;this.Wb=3;this.nc=8;this.Jm=gfc_c;this.sa=this.nc*this.Wb;this.slimTopCapHeight=19;this.tinyTopCapHeight=
8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=gfc_c;this.Ob=new gfc_Tl;if(this.Oh()){a=(a=this.g(f.FACE_SIZE))?gfc_ea(a):32;a=a+6;this.Wb=gfc_k[gfc_eb]((e[gfc_p]-10)/a);e=340;e=this.g(f.HEIGHT);b=this.g(f.NUMBER_ROWS);f=27;if(b){this.nc=gfc_ea(b);e=this.nc*a;this.Jm=e+f}else if(e){e=gfc_ea(e)-96;this.nc=gfc_k.max(2,gfc_k[gfc_eb](e/a));this.Jm=this.nc*a+f}this.sa=this.nc*this.Wb}gfc_2[gfc_D](this,d)};gfc_7.inherits(gfc_2);
gfc_za(gfc_7[gfc_],function(){gfc_ql("start");var a=gfc_e[gfc_o][gfc_Hb](),b=gfc_ia();if(a=b.profileId||a.profileId){b={};b[gfc_i[gfc_u][gfc_J].ID]=a;a=new gfc_i[gfc_u](b);this.render(["profileData","profileFriends","activityData"],"profile",{person:a})}else{a=["members","viewerFriends"];this.isMessagingEnabled&&a[gfc_m]("requestAndProcessViewerNumWaitingMessages");this.isPromosEnabled&&!this.Lb()&&a[gfc_m]("requestPromo");this.render(a,"faces")}});gfc_7[gfc_].e={};
gfc_7[gfc_].Ia=function(){this.e.MSG_SITE_MEMBERS="Membros";this.e.MSG_BE_THE_FIRST="Seja o primeiro!";this.e.MSG_NO_SITE_MEMBERS="Ainda n\u00e3o h\u00e1 membros.";this.e.MSG_ALL_SITE_MEMBERS="Todos os membros";this.e.MSG_ALL_BLOCKED_MEMBERS="Todos os membros bloqueados";this.e.MSG_NO_BLOCKED_MEMBERS="Voc\u00ea n\u00e3o bloqueou nenhum membro";this.e.MSG_YOUR_FRIENDS="Seus amigos";this.e.MSG_ALL_YOUR_FRIENDS="Todos os seus amigos";this.e.MSG_JFJ="Participe e conecte-se com as pessoas!";this.e.MSG_MANAGE=
"Gerenciar membros";this.e.MSG_SETTINGS="Configura\u00e7\u00f5es";this.e.MSG_OPTIONS="Op\u00e7\u00f5es";this.e.MSG_INVITE="Convidar";this.e.MSG_MEMBERS_SHARE="Share this page";this.e.MSG_BACK="Voltar";this.e.MSG_BACK_TO_TOP="P\u00e1gina inicial";this.e.MSG_VIEW_MY_PROFILE="Visualizar meu perfil";this.e.MSG_ABOUT_ME="Sobre mim";this.e.MSG_MORE="Mais \u00bb";this.e.MSG_SHOW_BLOCKED="Mostrar membros bloqueados \u00bb";this.e.MSG_SHOW_ALL="\u00ab Mostrar todos os membros";this.e.MSG_INVITE_YOUR_FRIENDS=
"Convide seus amigos";this.e.MSG_LINK_IN_NETWORKS="Vincular suas redes sociais";this.e.MSG_ACTIVITIES="Atividades";this.e.MSG_ALL_ACTIVITIES="Mais atividades";this.e.MSG_DELETE_THIS="Excluir";this.e.MSG_SITES="Sites dos quais eu participo";this.e.MSG_ALL_SITES="Mais sites dos quais eu participo";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="Mais links";this.e.MSG_NO_ACTIVITIES="Nenhuma atividade a ser exibida";this.e.MSG_ADD_AS_FRIEND="Adicionar como amigo(a)";this.e.MSG_SEND_MESSAGE="Enviar mensagem";
this.e.MSG_BLOCK_USER="Bloquear este usu\u00e1rio";this.e.MSG_UNBLOCK_USER="Desbloquear este usu\u00e1rio";this.e.MSG_USER_IS_ADMIN="Administrador";this.e.MSG_JOIN="Participar deste site";this.e.MSG_OR="ou";this.e.MSG_SIGN_IN="Fazer login";this.e.MSG_SIGN_OUT="Sair";this.e.MSG_PREVIOUS="\u00ab Anterior";this.e.MSG_NEXT="Pr\u00f3xima \u00bb";this.e.MSG_NEWER="\u00ab Mais recentes";this.e.MSG_OLDER="Mais antigos \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Aceitar tudo";this.e.MSG_HELP_FRIENDREQUEST=
"Voc\u00ea e seus amigos ver\u00e3o uns aos outros em todos os sites do Google Friend Connect.";this.e.MSG_HELP_FRIENDINVITE="Depois de se tornarem amigos, voc\u00eas ver\u00e3o um ao outro em todos os sites do Google Friend Connect.";this.e.MSG_HELP_BLOCKMEMBER="Bloquear um visitante o remove da lista de membros e impede que ele interaja com outros visitantes no seu site";this.e.MSG_INVITATION="Convite:";this.e.MSG_SEND="Enviar";this.e.MSG_BLOCK="Bloquear";this.e.MSG_IGNORE="Ignorar";this.e.MSG_CANCEL=
"Cancelar";this.e.MSG_SITE_SETTINGS="Configura\u00e7\u00f5es do site";this.e.MSG_INVITE_FRIENDS="Convidar amigos";this.e.MSG_ABOUT_FC="Sobre o Google Friend Connect";this.e.MSG_ALREADY_MEMBER="J\u00e1 \u00e9 um membro?";this.e.MSG_EDIT_PROFILE="Editar perfil"};gfc_7[gfc_].va={};
gfc_7[gfc_].gr=function(){this.va.MSG_SITE_MEMBERS="Seguidores";this.va.MSG_NO_SITE_MEMBERS="Ainda n\u00e3o h\u00e1 seguidores.";this.va.MSG_SHOW_BLOCKED="Mostrar seguidores bloqueados \u00bb";this.va.MSG_SHOW_ALL="\u00ab Mostrar todos os seguidores";this.va.MSG_ALL_SITE_MEMBERS="Todos os seguidores";this.va.MSG_ALL_BLOCKED_MEMBERS="Todos os seguidores bloqueados";this.va.MSG_NO_BLOCKED_MEMBERS="Voc\u00ea n\u00e3o bloqueou nenhum seguidor";this.va.MSG_LIKE_THIS_SITE="Gostou deste blog?";this.va.MSG_JOIN=
"Seguir";this.va.MSG_BACK_TO_TOP="Membros";this.va.MSG_JFJ="Participe e conecte-se aos seus amigos!";this.va.MSG_HELP_FRIENDREQUEST="Voc\u00ea e seus amigos ver\u00e3o uns aos outros em todos os blogs que estiverem seguindo e sites do Google Friend Connect.";this.va.MSG_HELP_FRIENDINVITE="Depois de se tornarem amigos, voc\u00eas ver\u00e3o um ao outro em todos os blogs que estiverem seguindo e sites do Google Friend Connect."};
gfc_7[gfc_].N=function(a,b){var c=gfc_b;if(b[gfc_F]&&b[gfc_F].person){var d={},e=b[gfc_F].person[gfc_Bb]()+" \u00e9 seu(sua) amigo(a)";d.MSG_IS_FRIEND=e;e="Voc\u00ea convidou "+(b[gfc_F].person[gfc_Bb]()+" para ser seu(sua) amigo(a)");d.MSG_IS_INVITED=e;e="Amigos de "+b[gfc_F].person[gfc_Bb]();d.MSG_PROFILE_FRIENDS=e;e="Todos os amigos de "+b[gfc_F].person[gfc_Bb]();d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.f(a,f,d[f])}if(b.invitedBy&&b.invitedBy[gfc_Bb]()){d=gfc_j[gfc_p]?gfc_j[gfc_p]:gfc_j[gfc_y][gfc_5a]+
2;c=(d-135)/8;d=(d-175)/8;c="Visualizar perfil de "+gfc_el(b.invitedBy[gfc_Bb](),c);d=gfc_el(b.invitedBy[gfc_Bb](),d)+" convidou voc\u00ea para este site";this.f(a,"MSG_VIEW_INVITER_PROFILE",c);this.f(a,"MSG_INVITED_YOU",d);this.Yv=gfc_b;c=gfc_d}d=this.numWaitingMessages+" mensagens aguardando voc\u00ea.";if(this.isMessagingEnabled&&this.numWaitingMessages>0){c=gfc_d;this.f(a,"showWaitingMessages",gfc_b);if(this.isMessagingEnabled){this.f(a,"MSG_NUM_WAITING_MESSAGES",d);this.f(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING",
"Visualizar mensagens")}}if(b.friendRequests){if(b.friendRequests[gfc_1a]()>0)c=gfc_d;if(b.friendRequests[gfc_1a]()==1)d="Solicita\u00e7\u00e3o de novo amigo \u00bb";else d=d="Solicita\u00e7\u00f5es de novos amigos ("+(b.friendRequests[gfc_1a]()+") \u00bb");this.f(a,"MSG_NEW_FRIEND_REQUESTS",d)}if(this.kb){if(this.kl(this.kb.themeId))for(f in this.va)this.f(a,f,this.va[f]);this.kb.signInPrompt&&this.f(a,"MSG_JOIN",this.kb.signInPrompt);this.kb.signOutPrompt&&this.f(a,"MSG_SIGN_OUT",this.kb.signOutPrompt)}this.f(a,
"isViewerAdmin",b.isViewerAdmin);this.f(a,"isMessagingEnabled",this.isMessagingEnabled);this.f(a,"acceptMessages",this.Ln);this.f(a,"isViewingSelf",b.viewer&&b[gfc_F]&&b[gfc_F].person&&b.viewer[gfc_B]()==b[gfc_F].person[gfc_B]());d=gfc_d;if(b.owner)if(b=b.owner[gfc_K]("profileExtensions"))for(f in b)d=gfc_b;this.f(a,"communityHasProfile",d);this.f(a,"promoHtml",c?this.promoHtml:gfc_c);this.f(a,"insertHtml",function(g,h){gfc_qa(g,h)})};gfc_7[gfc_].kl=function(a){return a=="blogger"};
gfc_7[gfc_].ah=function(a,b,c,d){gfc_Nl({id:a,text:b,version:this.kl(this.kb.themeId)?1:gfc_c,style:c},d)};
gfc_7[gfc_].Q=function(a){this.f(a,"facesPerRow",this.Wb);for(var b in this.e)this.f(a,b,this.e[b]);this.f(a,"getThumbnail",gfc_N(this.sc,this));this.f(a,"map",gfc_N(this.map,this));this.f(a,"elide",gfc_N(gfc_el,this));this.f(a,"safeSlice",gfc_N(this.pi,this));this.f(a,"showAllActivities",gfc_N(this.Jv,this));this.f(a,"transformActivity",gfc_N(this.fc,this));this.f(a,"nextActivities",gfc_N(this.rs,this));this.f(a,"previousActivities",gfc_N(this.at,this));this.f(a,"showAllLinks",gfc_N(this.Lv,this));
this.f(a,"transformLink",gfc_N(this.ww,this));this.f(a,"nextLinks",gfc_N(this.vs,this));this.f(a,"previousLinks",gfc_N(this.dt,this));this.f(a,"showAllSites",gfc_N(this.Ov,this));this.f(a,"transformSite",gfc_N(this.xw,this));this.f(a,"nextSites",gfc_N(this.Cs,this));this.f(a,"previousSites",gfc_N(this.jt,this));this.f(a,"showAllMembers",gfc_N(this.Mv,this));this.f(a,"showBlockedMembers",gfc_N(this.Qv,this));this.f(a,"showUnblockedMembers",gfc_N(this.gw,this));this.f(a,"nextMembers",gfc_N(this.ws,
this));this.f(a,"nextBlockedMembers",gfc_N(this.ss,this));this.f(a,"previousMembers",gfc_N(this.et,this));this.f(a,"previousBlockedMembers",gfc_N(this.bt,this));this.f(a,"showAllProfileFriends",gfc_N(this.Nv,this));this.f(a,"nextProfileFriends",gfc_N(this.Bs,this));this.f(a,"previousProfileFriends",gfc_N(this.it,this));this.f(a,"showAllViewerFriends",gfc_N(this.Pv,this));this.f(a,"nextViewerFriends",gfc_N(this.Ds,this));this.f(a,"previousViewerFriends",gfc_N(this.kt,this));this.f(a,"isHome",gfc_N(this.Lh,
this));this.f(a,"goBack",gfc_N(this.ph,this));this.f(a,"goBackToHome",gfc_N(this.Zv,this));this.f(a,"invite",gfc_N(this.invite,this));this.f(a,"editSettings",gfc_N(this.Ab,this));this.f(a,"signout",gfc_N(this.signout,this));this.f(a,"signin",gfc_N(this.signin,this));this.f(a,"viewProfile",gfc_N(this.Bn,this));this.f(a,"blockUser",gfc_N(this.mj,this));this.f(a,"unblockUser",gfc_N(this.zw,this));this.f(a,"goToInviteFriend",gfc_N(this.pq,this));this.f(a,"sendMessageDialog",gfc_N(this.gv,this));this.f(a,
"goToBlockMember",gfc_N(this.oq,this));this.f(a,"goToEditProfile",gfc_N(this.Ab,this));this.f(a,"goToViewerProfile",gfc_N(this.qq,this));this.f(a,"sendInvite",gfc_N(this.fv,this));this.f(a,"blockMember",gfc_N(this.eo,this));this.f(a,"acceptFriendRequest",gfc_N(this.Kn,this));this.f(a,"ignoreFriendRequest",gfc_N(this.fr,this));this.f(a,"viewFriendRequests",gfc_N(this.Jw,this));this.f(a,"acceptAllFriendRequests",gfc_N(this.Jn,this));this.f(a,"numPreviewFriends",gfc_N(this.Xp,this));this.f(a,"numPreviewMembers",
gfc_N(this.Yp,this));this.f(a,"showInvitedBy",gfc_N(this.dq,this))};
gfc_7[gfc_].Ek=function(a){a=gfc_k.max(1,a?this.nc-1:this.nc);var b=this.d[gfc_r].members?this.d[gfc_r].members[gfc_1a]():0,c=this.d[gfc_r].friends?this.d[gfc_r].friends[gfc_1a]():0;b=gfc_k[gfc_5l](b/this.Wb);c=gfc_k[gfc_5l](c/this.Wb);if(b>gfc_k[gfc_5l](a/2))if(c>gfc_k[gfc_eb](a/2)){b=gfc_k[gfc_5l](a/2);c=gfc_k[gfc_eb](a/2)}else b=gfc_k.max(0,a-c);else if(c>gfc_k[gfc_eb](a/2))c=gfc_k.max(0,a-b);b=b*this.Wb;c=c*this.Wb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].Yp=function(a){return this.Ek(a).numMembers};
gfc_7[gfc_].Xp=function(a){return this.Ek(a).numFriends};gfc_7[gfc_].f=function(a,b,c){a.p(b,c)};gfc_7[gfc_].zu=function(a,b){var c=gfc_i[gfc_I](),d={},e=gfc_i[gfc_z][gfc_dc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_Tb];d[e.MAX]=b.pageSize?b.pageSize:this.sa;b=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Va],gfc_i[gfc_u][gfc_J][gfc_zc]];d[e[gfc_gc]]=b;d[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c.add(c[gfc_Rb](gfc_Md(),d),"ownerFriends");c[gfc_E](a)};
gfc_7[gfc_].tt=function(a){this.d[gfc_r].members=a.get("ownerFriends")[gfc_s]()};gfc_7[gfc_].tu=function(a,b){var c=gfc_i[gfc_I](),d={},e=gfc_i[gfc_z][gfc_dc];d[e.FIRST]=b[gfc_Tb];d[e.MAX]=b.pageSize?b.pageSize:this.sa;d[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;b={};b[gfc_i[gfc_Qa][gfc_J][gfc_Ab]]=gfc_i[gfc_Qa].PersonId.OWNER;b[gfc_i[gfc_Qa][gfc_J][gfc_gb]]="BLOCKED";b[gfc_i[gfc_Qa][gfc_J][gfc_Ua]]=1;b=gfc_i[gfc_Hc](b);c.add(c[gfc_Rb](b,d),"blockedMembers");c[gfc_E](a)};
gfc_7[gfc_].pt=function(a){this.d[gfc_r].blockedMembers=a.get("blockedMembers")[gfc_s]()};gfc_7[gfc_].Fu=function(a,b){var c=gfc_i[gfc_I](),d=b&&b.person&&b.person[gfc_B]()||this.H[gfc_F].person[gfc_B](),e={},f=gfc_i[gfc_z][gfc_dc];e[f.FIRST]=b[gfc_Tb];e[f.MAX]=b.pageSize?b.pageSize:this.sa;b=this.Pl(d);e[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c.add(c[gfc_Rb](b,e),"profileFriends");c[gfc_E](a)};
gfc_7[gfc_].Pl=function(a){var b={};b[gfc_i[gfc_Qa][gfc_J][gfc_Ab]]=a;b[gfc_i[gfc_Qa][gfc_J][gfc_gb]]="FRIENDS";b[gfc_i[gfc_Qa][gfc_J][gfc_Ua]]=1;return gfc_i[gfc_Hc](b)};gfc_7[gfc_].yt=function(a){this.d[gfc_r][gfc_F].friends=a.get("profileFriends")[gfc_s]()};gfc_7[gfc_].ej=function(a){for(var b=gfc_i[gfc_r].getDataContext(),c=0;c<a[gfc_n];c++){var d=a[c];d=b.getDataSet(d);if(!d||d.code)return gfc_d}return gfc_b};
gfc_7[gfc_].Au=function(a){var b=this.sa,c=!b||b==24;if(c&&gfc_i[gfc_r])if(this.ej(["ownerFriends","viewer","siteSettings","friendRequests"])){a(gfc_i[gfc_r].getDataContext()[gfc_s]());return}c=gfc_4l.newBatch();b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"};c.add("ownerFriends",gfc_4l.people.get(b));c.add("viewer",gfc_4l.people.getViewer());c.add("siteSettings",gfc_4l.extensions.get({command:"GetSiteSettings"}));c.add("friendRequests",gfc_4l.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'}));(b=gfc_ia().psinvite)&&c.add("invitedBy",gfc_4l.extensions.get({command:"DecodeInvitation",params:{token:b}}));c.execute(a)};gfc_7[gfc_].ut=function(a,b){this.d[gfc_r].members=gfc_Ed(a.ownerFriends,gfc_zd);this.d[gfc_r].viewer=gfc_zd(a.viewer);this.jm(a,b,gfc_b);this.kb=a[gfc_hc];b=gfc_ia();if(b.psinvite)if(this.d[gfc_r].viewer==gfc_c||this.d[gfc_r].viewer==""){if(a.invitedBy)a.invitedBy.nickname=a.invitedBy.displayName;this.d[gfc_r].invitedBy=new gfc_i[gfc_u](a.invitedBy)}};
gfc_7[gfc_].Su=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_Tb]||b[gfc_Tb]==0,e=!c||c==20;if(d&&e&&gfc_i[gfc_r])if(this.ej(["friends","isViewerAdmin"])){a(gfc_i[gfc_r].getDataContext()[gfc_s]());return}d=gfc_4l.newBatch();c={userId:"@viewer",groupId:"@friends",count:c};if(b[gfc_Tb])c.startIndex=b[gfc_Tb];d.add("friends",gfc_4l.people.get(c));d.add("isViewerAdmin",gfc_4l.people.get({userId:"@viewer",groupId:"ADMINS"}));d.execute(a)};
gfc_7[gfc_].Et=function(a){var b=a.friends;if(b&&!b.error)this.d[gfc_r].friends=gfc_Ed(b,gfc_zd);this.Mm(a)};gfc_7[gfc_].Tu=function(a){var b=gfc_i[gfc_I]();b.add(gfc_Cd("VIEWER"),"numWaitingMessages");b[gfc_E](a)};gfc_7[gfc_].Gt=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_s]().numberOfWaitingMessages};
gfc_7[gfc_].Hu=function(a){this.log("requesting promo");var b=new gfc_e[gfc_vb];b=b.getLang()+(b[gfc_$b]()?"_"+b[gfc_$b]():"");var c=gfc_i[gfc_I]();c.add(gfc_rd("GetPromo",{hl:b}),"promo");c[gfc_E](a)};gfc_7[gfc_].At=function(a){this.log("processing promo");if((a=a.get("promo")[gfc_s]())&&a.promoCode!=-1){this.promoCode=a.promoCode;this.promoHtml=a.promoHtml}};
gfc_7[gfc_].Sn=function(){for(var a=function(){this.promoHtml=gfc_c;for(var f=gfc_Lf("div","fc-promo-main",gfc_T("peg")),g=0;g<f[gfc_n];g++)gfc_bh(f[g],gfc_d);this.V();this.log("Dismissing promo "+this.promoCode);f=gfc_i[gfc_I]();f.add(gfc_rd("DismissPromo",{promoCode:this.promoCode}));f[gfc_E](gfc_N(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_Lf("a","fc-promo-dismiss-link",gfc_T("peg")),c=0;c<b[gfc_n];c++){var d=b[c],e="click";gfc_Jg(d,e);gfc_Dg(d,e,gfc_N(a,
this))}};gfc_7[gfc_].Mm=function(a){var b=a.isViewerAdmin;if(b&&!b.error)this.d[gfc_r].isViewerAdmin=b.list[gfc_n];else if(a.get&&a.get("isViewerAdmin"))if((a=a.get("isViewerAdmin"))&&!a[gfc_rb]())this.d[gfc_r].isViewerAdmin=a[gfc_s]()[gfc_1a]()};gfc_7[gfc_].Jn=function(a){var b=[];a.each(function(c){c={user:c[gfc_K](goog.opensocial.peoplesense.Invite[gfc_J].INVITER)[gfc_B](),action:"ACCEPT"};b[gfc_m](c)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_N(this.Ig,this),{friendRequestResponses:b})};
gfc_7[gfc_].Zv=function(){this.ga();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].Kn=function(a){a={user:a[gfc_B](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_N(this.Ig,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Jw=function(){this.ga();this.A("friend-requests")};gfc_7[gfc_].Bn=function(a){if(this.Lb()){this.ga();this.Lw(a)}else gfc_nd(a[gfc_B]())};
gfc_7[gfc_].Lw=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].Nu=function(a,b){var c=gfc_i[gfc_I](),d=gfc_i[gfc_z][gfc_dc],e={};e[d.FIRST]=b&&b[gfc_Tb]?b[gfc_Tb]:0;b=this.d[gfc_r][gfc_F].person[gfc_B]();e[d.MAX]=this.kn;c.add(gfc_Jd(gfc_i[gfc_Hc]({userId:b}),e),"profileSites");c[gfc_E](a)};gfc_7[gfc_].Ct=function(a){this.d[gfc_r][gfc_F].sites=a.get("profileSites")[gfc_s]()};
gfc_7[gfc_].Eu=function(a,b){this.d[gfc_r].profile={};b=b||{};var c=b.person;b={};c=c[gfc_B]();var d=gfc_i[gfc_I](),e=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Va],gfc_i[gfc_u][gfc_J][gfc_zc],gfc_i[gfc_u][gfc_J].ABOUT_ME,gfc_i[gfc_u][gfc_J].URLS,"profileExtensions"],f=gfc_i[gfc_z][gfc_dc];b[f[gfc_gc]]=e;b[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;d.add(d.newFetchPersonRequest(c,b),"profile");d.add(d.newFetchPersonRequest("VIEWER",b),"viewer");d.add(gfc_Hd("VIEWER","ADMINS"),
"isViewerAdmin");d.add(d.newFetchPersonRequest("OWNER",b),"owner");this.kb||d.add(gfc_Bd(),"siteSettings");d.add(gfc_Hd(c,"ADMINS"),"isAdmin");d.add(gfc_Hd(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&d.add(gfc_Cd(c),"canMessage");d[gfc_E](a)};
gfc_7[gfc_].Vf=function(a,b){var c=b.person[gfc_B](),d=gfc_i[gfc_Hc]({userId:c}),e=gfc_i[gfc_I]();if(this.d[gfc_r].viewer&&c!=this.d[gfc_r].viewer[gfc_B]()||this.Lb())e.add(gfc_Gd(b.person[gfc_B](),"VIEWER"),"isProfileFriend");e.add(e[gfc_ob](d,{}),"activities");e[gfc_E](a)};
gfc_7[gfc_].qd=function(a,b){if(a.get("activities")[gfc_s]()!=gfc_c)this.d[gfc_r][gfc_F].activities=a.get("activities")[gfc_s]();if(a=a.get("isProfileFriend"))if(b&&this.d[gfc_r].viewer!=gfc_c&&this.d[gfc_r].viewer[gfc_B]()!=b.person[gfc_B]())this.d[gfc_r][gfc_F].isFriend=a[gfc_s]()[gfc_t]};
gfc_7[gfc_].xt=function(a,b){var c=a.get("profile")[gfc_s]();this.d[gfc_r][gfc_F].person=c;this.d[gfc_r][gfc_F].person.externalProfileUrl=gfc_c;var d=c[gfc_K](gfc_i[gfc_u][gfc_J].URLS),e=[];if(d)for(var f=0;f<d[gfc_n];f++){var g=d[f];g[gfc_K](gfc_i.Url[gfc_J].TYPE)!="profile"&&g[gfc_K](gfc_i.Url[gfc_J].TYPE)!="externalProfile"&&e[gfc_m](g);if(g[gfc_K](gfc_i.Url[gfc_J].TYPE)=="externalProfile")this.d[gfc_r][gfc_F].person.externalProfileUrl=g[gfc_K](gfc_i.Url[gfc_J].ADDRESS)}this.d[gfc_r][gfc_F].links=
new gfc_8l(e,this.Jf,0);this.d[gfc_r].owner=a.get("owner")[gfc_s]();this.d[gfc_r].viewer=a.get("viewer")[gfc_s]();if((d=this.d[gfc_r].viewer)&&b.person[gfc_B]()!=this.d[gfc_r].viewer[gfc_B]()){this.d[gfc_r][gfc_F].isAdmin=a.get("isAdmin")[gfc_s]();if(this.d[gfc_r][gfc_F].isAdmin)this.d[gfc_r][gfc_F].isAdmin=this.d[gfc_r][gfc_F].isAdmin[gfc_1a]();this.d[gfc_r][gfc_F].isBlocked=a.get("isBlocked")[gfc_s]();if(this.d[gfc_r][gfc_F].isBlocked)this.d[gfc_r][gfc_F].isBlocked=this.d[gfc_r][gfc_F].isBlocked[gfc_1a]()}b=
c[gfc_K]("profileExtensions");b=this.Ob.Cf(b,this.Ob.Fi);c=[];for(f in b){d=b[f];e={};e.title=d.title;g=gfc_d;if(d.entryType=="SHORT_TEXT"||d.entryType=="LONG_TEXT"){if(d[gfc_t]&&d[gfc_t][gfc_4a]){e.body=[];e[gfc_y][gfc_m](d[gfc_t][gfc_4a]);g=gfc_b}}else if(d[gfc_t]&&d[gfc_t].choice&&d[gfc_t].choice[gfc_n]>0){e.body=[];for(g=0;g<d[gfc_t].choice[gfc_n];++g)e[gfc_y][gfc_m](d[gfc_t].choice[g][gfc_vc]);g=gfc_b}g&&c[gfc_m](e)}this.d[gfc_r][gfc_F].profileExtensions=c;if(!this.kb)this.kb=a.get("siteSettings")[gfc_s]();
if(this.isMessagingEnabled){f=(f=a.get("canMessage"))&&f[gfc_s]().canSendMessage;this.d[gfc_r][gfc_F].canSendMessage=f}this.Mm(a)};gfc_7[gfc_].mj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].zw=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[];b=gfc_N(function(d,e,f){d[gfc_m](e(f))},this,c,b);a.each(b);return c};gfc_7[gfc_].Mv=function(){this.ga();this.A("members-page")};
gfc_7[gfc_].Qv=function(){this.ga();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].gw=function(){this.Ni()};gfc_7[gfc_].ws=function(a){this.render(["member-page"],"members-page",{start:this.sa+a.getOffset()})};gfc_7[gfc_].et=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.sa})};gfc_7[gfc_].ss=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.sa+a.getOffset()})};
gfc_7[gfc_].bt=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.sa})};gfc_7[gfc_].Pv=function(){this.ga();this.A("viewer-friends-page")};gfc_7[gfc_].Ds=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.sa+a.getOffset()})};gfc_7[gfc_].kt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.sa})};gfc_7[gfc_].Nv=function(){this.ga();this.A("profile-friends-page")};
gfc_7[gfc_].Bs=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.sa+a.getOffset(),person:this.d[gfc_r][gfc_F].person})};gfc_7[gfc_].it=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.sa,person:this.d[gfc_r][gfc_F].person})};gfc_7[gfc_].Lv=function(){this.ga();this.A("links")};gfc_7[gfc_].vs=function(a){var b=this.Jf+a.getOffset();this.d[gfc_r][gfc_F].links=new gfc_8l(a.all(),this.Jf,b);this.A("links")};
gfc_7[gfc_].dt=function(a){var b=a.getOffset()-this.Jf;this.d[gfc_r][gfc_F].links=new gfc_8l(a.all(),this.Jf,b);this.A("links")};gfc_7[gfc_].Ov=function(){this.ga();this.A("sites")};gfc_7[gfc_].Cs=function(a){this.render(["sitesData"],"sites",{start:this.kn+a.getOffset()})};gfc_7[gfc_].jt=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.kn})};gfc_7[gfc_].Jv=function(){this.ga();this.A("activities")};
gfc_7[gfc_].rs=function(a){this.render(["activityData"],"activities",{start:this.Ea+a.getOffset()})};gfc_7[gfc_].at=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ea})};gfc_7[gfc_].pf=function(a){this.render(["deleteActivity"],this.d[gfc_Eb],{activity:a})};gfc_7[gfc_].su=function(a,b){var c=gfc_i[gfc_I]();c.add(gfc_Id(b.person[gfc_B](),["BLOCKED"],[]),"block");this.jd();c[gfc_E](a)};
gfc_7[gfc_].ot=function(a){if(a=!a.get("block")[gfc_rb]())this.d[gfc_r][gfc_F].isBlocked=gfc_b};gfc_7[gfc_].Qu=function(a,b){var c=gfc_i[gfc_I]();c.add(gfc_Id(b.person[gfc_B](),[],["BLOCKED"]),"unblock");this.jd();c[gfc_E](a)};gfc_7[gfc_].Dt=function(a){if(a=!a.get("unblock")[gfc_rb]())this.d[gfc_r][gfc_F].isBlocked=gfc_d};
gfc_7[gfc_].Wf=function(a,b){var c=b.activity;b=c[gfc_K](gfc_i[gfc_Ub][gfc_J].ID);c=gfc_i[gfc_Hc]({userId:c[gfc_K](gfc_i[gfc_Ub][gfc_J][gfc_Ab])});var d=gfc_i[gfc_I]();d.add(gfc_sd(b),"delete");d.add(d[gfc_ob](c,{}),"activities");d[gfc_E](a)};
gfc_7[gfc_].fc=function(a){var b=gfc_Wl,c=function(f){return f=f[gfc_q](/<a/g,"<a target='_top'")},d=gfc_c,e=this.d[gfc_r].viewer;if(e!=gfc_c&&a[gfc_K](gfc_i[gfc_Ub][gfc_J][gfc_Ab])==this.d[gfc_r].viewer[gfc_B]())d=gfc_N(this.pf,this,a);(e=a[gfc_K](gfc_i[gfc_Ub][gfc_J].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_h.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ea(a[gfc_K](gfc_i[gfc_Ub][gfc_J].POSTED_TIME))),link:a[gfc_K](gfc_i[gfc_Ub][gfc_J].STREAM_URL,{escapeType:"none"}),
siteTitle:a[gfc_K](gfc_i[gfc_Ub][gfc_J].STREAM_TITLE,{escapeType:"none"}),innerHTML:c(a[gfc_K](gfc_i[gfc_Ub][gfc_J].TITLE,{escapeType:"none"})),body:c(a[gfc_K](gfc_i[gfc_Ub][gfc_J].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].xw=function(a){var b=gfc_e[gfc_cc].unescapeString,c=gfc_6l;return{icon:c(a[gfc_K](gfc_i[gfc_u][gfc_J][gfc_0b])),link:a[gfc_K](gfc_i[gfc_u][gfc_J][gfc_0b]),title:b(a[gfc_Bb]())}};
gfc_7[gfc_].ww=function(a){var b=gfc_e[gfc_cc].unescapeString,c=gfc_6l,d=a[gfc_K](gfc_i.Url[gfc_J].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_K](gfc_i.Url[gfc_J].LINK_TEXT))||d}};
gfc_7[gfc_].Gu=function(a,b){var c=gfc_i[gfc_I]();b=b.person[gfc_B]();var d={},e=gfc_i[gfc_z][gfc_dc];d[e[gfc_gc]]=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Va]];var f=this.Pl(b),g={};g[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c.add(c[gfc_Rb](f,g),"friends");f={};f[e.FIRST]=this.Dx;f[e.MAX]=this.Cx;c.add(gfc_Jd(gfc_i[gfc_Hc]({userId:b}),f),"profileSites");d[e[gfc_gc]]=[gfc_i[gfc_u][gfc_J].ID,gfc_i[gfc_u][gfc_J][gfc_Va],gfc_i[gfc_u][gfc_J][gfc_zc],gfc_i[gfc_u][gfc_J].ABOUT_ME];
d[gfc_i[gfc_z].DataRequestFields.ESCAPE_TYPE]=gfc_i.EscapeType.NONE;c[gfc_E](a)};gfc_7[gfc_].fr=function(a){a={user:a[gfc_B](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_N(this.Ig,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Ig=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].Mu=function(a,b){var c=b[gfc_F],d=gfc_i[gfc_I]();d.add(gfc_td(c[gfc_B](),b[gfc_xb]),"friendRequest");this.jd();d[gfc_E](a)};
gfc_7[gfc_].Bt=function(a){if(!a.get("friendRequest")[gfc_rb]())this.d[gfc_r][gfc_F].isInvited=gfc_b};gfc_7[gfc_].wu=function(a,b){var c=gfc_4l.newBatch();b=b.friendRequestResponses;c.add("updateFriendRequest",gfc_4l.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_e[gfc_Yb].stringify(b)+"}"}));c.add("friendRequests",gfc_4l.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.jd();c.execute(a)};gfc_7[gfc_].pq=function(){this.ga();this.A("invite-friend")};
gfc_7[gfc_].gv=function(a){if(this.isMessagingEnabled){a=a[gfc_K](gfc_i[gfc_u][gfc_J].ID);this.hv(a)}};gfc_7[gfc_].hv=function(a){if(this.isMessagingEnabled){a="/friendconnect/messaging/compose?recipientId="+a;var b=570,c=395;gfc_Fl(a,gfc_g(b),gfc_g(c))}};gfc_2[gfc_].Ln=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_Fl(a,gfc_g(b),gfc_g(c));return gfc_d};gfc_7[gfc_].oq=function(){this.ga();this.A("block-member")};gfc_7[gfc_].qq=function(){this.Bn(this.d[gfc_r].viewer)};
gfc_7[gfc_].fv=function(a){this.Of();a={profile:a};var b=gfc_T("inviteMessage");if(b)a.message=gfc_9e(b);this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].eo=function(a){this.Of();this.mj(a)};gfc_7[gfc_].jm=function(a,b,c){c=c||gfc_d;this.d[gfc_r].friendRequests=gfc_Ed(a.friendRequests,gfc_vd);b["next-view"]=this.d[gfc_r].friendRequests[gfc_1a]()>0?"friend-requests":"faces";c||gfc_ql("friend")};
gfc_7[gfc_].zt=function(a){this.d[gfc_r][gfc_F].sites=a.get("profileSites")[gfc_s]();this.d[gfc_r][gfc_F].friends=a.get("friends")[gfc_s]()};gfc_7[gfc_].dq=function(){return this.Yv};gfc_7[gfc_].V=function(){this.dx.rebuild();this.Sn();gfc_e[gfc_Ra].adjustHeight()};gfc_7[gfc_].Ts=function(a){return a=gfc_U("span",{"class":"fc-cap-link-big"},gfc_U("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Ng())};
gfc_7[gfc_].Ss=function(){var a=[];a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_n]]=this.isSocialShareEnabled?gfc_U("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_U("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);if(this.d[gfc_r].isViewerAdmin&&!this.Lb())a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE);a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-signout"},
this.kb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_n]]=gfc_U("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_U("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].Us=function(a){a[gfc_mb]();a=a[gfc_C].h()[gfc__a];if(a[gfc_Mb]("menuaction-settings"))this.Ab();else if(a[gfc_Mb]("menuaction-invite"))this.invite();else if(a[gfc_Mb]("menuaction-share"))this.share();else if(a[gfc_Mb]("menuaction-signout"))this.signout();else if(a[gfc_Mb]("menuaction-manage"))this.uq();else if(a[gfc_Mb]("menuaction-aboutfc")){a=gfc_h[gfc_Wa](gfc_xl()+"/friendconnect");a[gfc_Vb]()}};
gfc_7[gfc_].uq=function(){var a={},b=gfc_e[gfc_o][gfc_fb]().canvas;gfc_ql("lightbox");gfc_e[gfc_o].requestNavigateTo(b,a);return gfc_d};var gfc_7l=function(a){for(var b={},c=0;c<a[gfc_n];++c)b[a[c]]=a[c];return b}(["HEIGHT","BORDER_COLOR","CONTENT_BG_COLOR","CONTENT_HEADLINE_COLOR","CONTENT_LINK_COLOR","CONTENT_SECONDARY_TEXT_COLOR","CONTENT_SECONDARY_LINK_COLOR","CONTENT_TEXT_COLOR","ENDCAP_BG_COLOR","ENDCAP_LINK_COLOR","ENDCAP_TEXT_COLOR","FACE_SIZE","NUMBER_ROWS"]);
gfc_7[gfc_].s=function(){var a=gfc_7l,b=[],c=0;gfc_ea(this.g(a.HEIGHT));if(this.Oh())b[c++]=this.i(".fc-thumbnail img {height:%spx;width:%spx}",this.g(a.FACE_SIZE));b[c++]=this.i(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.Jm);b[c++]=this.i(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.g(a.BORDER_COLOR));if(this.zf())if(this.Wk("profile"))b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n";else if(this.Qh())b[c++]=".fc-topcap {height: 0px;}\n";else b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n";if(this.Lb())b[c++]=".fc-userpic-caption {margin-left: 59px;}\n";else b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";if(this.Qh())b[c++]=".fc-topcap-color {background-color: white;}\n";else b[c++]=this.i(".fc-topcap-color {background-color: %s;}\n",this.g(a.ENDCAP_BG_COLOR));
if(this.ll())b[c++]=".fc-botcap-short {background-color: white;}\n";else b[c++]=this.i(".fc-botcap-short {background-color: %s;}\n",this.g(a.ENDCAP_BG_COLOR));b[c++]=this.i(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.g(a.ENDCAP_BG_COLOR));b[c++]=this.i(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.g(a.ENDCAP_BG_COLOR));b[c++]=this.i(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",
this.g(a.ENDCAP_TEXT_COLOR));b[c++]=this.i(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.g(a.ENDCAP_LINK_COLOR));b[c++]=this.i(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.g(a.CONTENT_BG_COLOR));b[c++]=this.i(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.g(a.CONTENT_LINK_COLOR));b[c++]=this.i(".fc-members,.fc-members-canvas {color:%s;}\n",this.g(a.CONTENT_TEXT_COLOR));b[c++]=this.i(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.g(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.i(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.g(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.i(".fc-sectitle {color: %s;}\n",
this.g(a.CONTENT_HEADLINE_COLOR));return gfc_7.j.s[gfc_D](this)+b[gfc_M]("\n")};gfc_O("goog.peoplesense.gadget.Members",gfc_7);gfc_O("goog.peoplesense.gadget.Members.start",gfc_7[gfc_Tb]);var gfc_8l=function(a,b,c){gfc_i.Collection[gfc_D](this,a[gfc_9a](c,c+b),c,a[gfc_n]);this.Rw=a;this.fa=b};gfc_8l.inherits(gfc_i.Collection);gfc_8l[gfc_].all=function(){return this.Rw};gfc_8l[gfc_].pb=function(){return this.fa};gfc_O("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_8l[gfc_].all);
gfc_O("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_8l[gfc_].pb);
