#
# Makefile
#
# $Id: //poco/1.3/XML/samples/DOMWriter/Makefile#1 $
#
# Makefile for Poco MeuWebServerXml
#

PROJECT_BASE=.
POCO_BASE=/usr/local/poco

include $(POCO_BASE)/build/rules/global

objects = MeuWebServerXml_Leitura

target         = MeuWebServerXml_Leitura
target_version = 1
target_libs    = PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
