#
# Makefile
#
# $Id: //poco/1.3/Foundation/samples/Timer/Makefile#1 $
#
# Makefile for Poco Timer
#


PROJECT_BASE=.

include $(POCO_BASE)/build/rules/global

objects = Timer

target         = Timer
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
