#
# Makefile
#
# $Id: //poco/1.3/Foundation/samples/deflate/Makefile#1 $
#
# Makefile for Poco deflate
#

PROJECT_BASE=.
POCO_BASE=/usr/local/poco

include $(POCO_BASE)/build/rules/global

objects = deflate

target         = deflate
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
