#
# Makefile
#
# $Id: //poco/1.3/Foundation/samples/LogRotation/Makefile#1 $
#
# Makefile for Poco LogRotation
#

PROJECT_BASE=.
POCO_BASE=/usr/local/poco


include $(POCO_BASE)/build/rules/global

objects = LogRotation

target         = LogRotation
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
