#
# Makefile
#
# $Id: //poco/1.3/Foundation/samples/uuidgen/Makefile#1 $
#
# Makefile for Poco uuidgen
#

PROJECT_BASE=.
POCO_BASE=/usr/local/poco

include $(POCO_BASE)/build/rules/global

objects = uuidgen

target         = uuidgen
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
