

all:
	gcc  -L/usr/lib  -lpthread   threads_0.c -o threads_0
	gcc  -L/usr/lib  -lpthread   threads_1.c -o threads_1
	gcc  -L/usr/lib  -lpthread   threads_2.c -o threads_2
	gcc  -L/usr/lib  -lpthread   threads_3.c -o threads_3
	g++  -L/usr/lib  -lpthread   threads_4.c -o threads_4
	gcc  -L/usr/lib  -lpthread   threads_5.c -o threads_5
	gcc  -L/usr/lib  -lpthread   threads_6.c -o threads_6
	gcc  -L/usr/lib  -lpthread   threads_7.c -o threads_7
	gcc  -L/usr/lib  -lpthread   threads_8.c -o threads_8

clean:
	rm -rf threads_0 threads_1 threads_2 threads_3 threads_4 threads_5 threads_6 threads_7 threads_8 


